version: "3.8"

x-postgres-common: &postgres-common
  image: postgres:16-alpine
  user: postgres
  restart: always
  healthcheck:
    test: 'pg_isready -U loms --dbname=loms'
    interval: 10s
    timeout: 5s
    retries: 5

services:
  postgres_primary:
    <<: *postgres-common
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: loms
      POSTGRES_DB: loms
      POSTGRES_PASSWORD: loms
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication all 0.0.0.0/0 md5"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    command: |
      postgres
      -c wal_level=replica
      -c hot_standby=on
      -c max_wal_senders=10
      -c max_replication_slots=10
      -c hot_standby_feedback=on
    volumes:
      - ./postgres/00_init.sql:/docker-entrypoint-initdb.d/00_init.sql

  postgres_replica:
    <<: *postgres-common
    ports:
      - "5433:5432"
    environment:
      PGUSER: replicator
      PGPASSWORD: replicator_password
    command: |
      bash -c "
      until pg_basebackup --pgdata=/var/lib/postgresql/data -R --slot=replication_slot --host=postgres_primary --port=5432
      do
        echo 'Waiting for primary to connect...'
        sleep 1s
      done
      echo 'Backup done, starting replica...'
      chmod 0700 /var/lib/postgresql/data
      postgres
      "
    depends_on:
      - postgres_primary

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka0:29092
      DYNAMIC_CONFIG_ENABLED: "true"
  kafka0:
    container_name: kafka
    image: confluentinc/cp-kafka:7.7.1.arm64
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka0:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka0:29093
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "kafka0:29092"]
      interval: 1s
      timeout: 10s
      retries: 10

  kafka-init-topics:
    container_name: init-topics
    image: confluentinc/cp-kafka:7.5.4.arm64
    depends_on:
      kafka0:
        condition: service_healthy
    command:
      - "bash"
      - "-c"
      - |
        echo 'Waiting for Kafka to be ready...'
        cub kafka-ready -b kafka0:29092 1 30
        kafka-topics --create --topic loms.order-events \
          --partitions 2 \
          --replication-factor 1 \
          --if-not-exists \
          --bootstrap-server kafka0:29092

  loms:
    build:
      context: ./loms
      dockerfile: Dockerfile
    working_dir: /app
    command:
      - sh
      - -c
      - |
        echo "Waiting for databases to be ready..."
        while ! nc -z postgres_primary 5432; do sleep 1; done
        while ! nc -z postgres_replica 5432; do sleep 1; done
        
        echo "Running migrations..."
        bin/goose -dir migrations postgres "postgresql://loms:loms@postgres_primary:5432/loms?sslmode=disable" up
        
        echo "Starting application..."
        exec ./lomsbuild
    depends_on:
      postgres_primary:
        condition: service_healthy
      postgres_replica:
        condition: service_healthy
      kafka0:
        condition: service_healthy
    environment:
      DB_MASTER_URL: "postgres://loms:loms@postgres_primary:5432/loms?sslmode=disable"
      DB_REPLICA_URL: "postgres://loms:loms@postgres_replica:5432/loms?sslmode=disable"
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 50051 || exit 1" ]
      interval: 1s
      timeout: 3s
      retries: 30

  product:
    build:
      context: ./product
      dockerfile: Dockerfile
    working_dir: /app
    command: [ "./productbuild" ]
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8081/health || exit 1"]
      interval: 1s
      timeout: 3s
      retries: 30

  cart:
    build:
      context: ./cart
      dockerfile: Dockerfile
    working_dir: /app
    command: [ "./cartbuild" ]
    depends_on:
      loms:
        condition: service_healthy
      product:
        condition: service_healthy
    ports:
      - "8082:8082"

  notifier:
    build: ./notifier
    working_dir: /app
    command: ["./notifierbuild"]
    environment:
      KAFKA_BROKERS: "kafka0:29092"
      KAFKA_GROUP_ID: "notifier-group"
      KAFKA_TOPIC: "loms.order-events"
    depends_on:
      kafka0:
        condition: service_healthy
      kafka-init-topics:
        condition: service_completed_successfully
    deploy:
      replicas: 3

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  jaeger:
    image: jaegertracing/all-in-one:1.56
    ports:
      - "16686:16686" #ui
      - "4317:4317" #collector grpc

volumes:
  prometheus_data:
  grafana_data:

