// Code generated by http://github.com/gojuno/minimock (v3.4.0). DO NOT EDIT.

package mocks

//go:generate minimock -i route256/cart/internal/handler.cartService -o cart_service_mock.go -n CartServiceMock -p mocks

import (
	"context"
	"route256/cart/internal/model"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// CartServiceMock implements mm_handler.cartService
type CartServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcAddItemToCart          func(ctx context.Context, userId int64, skuId int64, count uint32) (err error)
	funcAddItemToCartOrigin    string
	inspectFuncAddItemToCart   func(ctx context.Context, userId int64, skuId int64, count uint32)
	afterAddItemToCartCounter  uint64
	beforeAddItemToCartCounter uint64
	AddItemToCartMock          mCartServiceMockAddItemToCart

	funcCancelOrder          func(ctx context.Context, orderId int64) (err error)
	funcCancelOrderOrigin    string
	inspectFuncCancelOrder   func(ctx context.Context, orderId int64)
	afterCancelOrderCounter  uint64
	beforeCancelOrderCounter uint64
	CancelOrderMock          mCartServiceMockCancelOrder

	funcCheckout          func(ctx context.Context, userId int64) (i1 int64, err error)
	funcCheckoutOrigin    string
	inspectFuncCheckout   func(ctx context.Context, userId int64)
	afterCheckoutCounter  uint64
	beforeCheckoutCounter uint64
	CheckoutMock          mCartServiceMockCheckout

	funcDeleteFromCart          func(ctx context.Context, userId int64, skuId int64) (err error)
	funcDeleteFromCartOrigin    string
	inspectFuncDeleteFromCart   func(ctx context.Context, userId int64, skuId int64)
	afterDeleteFromCartCounter  uint64
	beforeDeleteFromCartCounter uint64
	DeleteFromCartMock          mCartServiceMockDeleteFromCart

	funcGetItems          func(ctx context.Context, userId int64) (up1 *model.UserData, err error)
	funcGetItemsOrigin    string
	inspectFuncGetItems   func(ctx context.Context, userId int64)
	afterGetItemsCounter  uint64
	beforeGetItemsCounter uint64
	GetItemsMock          mCartServiceMockGetItems

	funcPayOrder          func(ctx context.Context, orderId int64) (err error)
	funcPayOrderOrigin    string
	inspectFuncPayOrder   func(ctx context.Context, orderId int64)
	afterPayOrderCounter  uint64
	beforePayOrderCounter uint64
	PayOrderMock          mCartServiceMockPayOrder
}

// NewCartServiceMock returns a mock for mm_handler.cartService
func NewCartServiceMock(t minimock.Tester) *CartServiceMock {
	m := &CartServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.AddItemToCartMock = mCartServiceMockAddItemToCart{mock: m}
	m.AddItemToCartMock.callArgs = []*CartServiceMockAddItemToCartParams{}

	m.CancelOrderMock = mCartServiceMockCancelOrder{mock: m}
	m.CancelOrderMock.callArgs = []*CartServiceMockCancelOrderParams{}

	m.CheckoutMock = mCartServiceMockCheckout{mock: m}
	m.CheckoutMock.callArgs = []*CartServiceMockCheckoutParams{}

	m.DeleteFromCartMock = mCartServiceMockDeleteFromCart{mock: m}
	m.DeleteFromCartMock.callArgs = []*CartServiceMockDeleteFromCartParams{}

	m.GetItemsMock = mCartServiceMockGetItems{mock: m}
	m.GetItemsMock.callArgs = []*CartServiceMockGetItemsParams{}

	m.PayOrderMock = mCartServiceMockPayOrder{mock: m}
	m.PayOrderMock.callArgs = []*CartServiceMockPayOrderParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mCartServiceMockAddItemToCart struct {
	optional           bool
	mock               *CartServiceMock
	defaultExpectation *CartServiceMockAddItemToCartExpectation
	expectations       []*CartServiceMockAddItemToCartExpectation

	callArgs []*CartServiceMockAddItemToCartParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CartServiceMockAddItemToCartExpectation specifies expectation struct of the cartService.AddItemToCart
type CartServiceMockAddItemToCartExpectation struct {
	mock               *CartServiceMock
	params             *CartServiceMockAddItemToCartParams
	paramPtrs          *CartServiceMockAddItemToCartParamPtrs
	expectationOrigins CartServiceMockAddItemToCartExpectationOrigins
	results            *CartServiceMockAddItemToCartResults
	returnOrigin       string
	Counter            uint64
}

// CartServiceMockAddItemToCartParams contains parameters of the cartService.AddItemToCart
type CartServiceMockAddItemToCartParams struct {
	ctx    context.Context
	userId int64
	skuId  int64
	count  uint32
}

// CartServiceMockAddItemToCartParamPtrs contains pointers to parameters of the cartService.AddItemToCart
type CartServiceMockAddItemToCartParamPtrs struct {
	ctx    *context.Context
	userId *int64
	skuId  *int64
	count  *uint32
}

// CartServiceMockAddItemToCartResults contains results of the cartService.AddItemToCart
type CartServiceMockAddItemToCartResults struct {
	err error
}

// CartServiceMockAddItemToCartOrigins contains origins of expectations of the cartService.AddItemToCart
type CartServiceMockAddItemToCartExpectationOrigins struct {
	origin       string
	originCtx    string
	originUserId string
	originSkuId  string
	originCount  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmAddItemToCart *mCartServiceMockAddItemToCart) Optional() *mCartServiceMockAddItemToCart {
	mmAddItemToCart.optional = true
	return mmAddItemToCart
}

// Expect sets up expected params for cartService.AddItemToCart
func (mmAddItemToCart *mCartServiceMockAddItemToCart) Expect(ctx context.Context, userId int64, skuId int64, count uint32) *mCartServiceMockAddItemToCart {
	if mmAddItemToCart.mock.funcAddItemToCart != nil {
		mmAddItemToCart.mock.t.Fatalf("CartServiceMock.AddItemToCart mock is already set by Set")
	}

	if mmAddItemToCart.defaultExpectation == nil {
		mmAddItemToCart.defaultExpectation = &CartServiceMockAddItemToCartExpectation{}
	}

	if mmAddItemToCart.defaultExpectation.paramPtrs != nil {
		mmAddItemToCart.mock.t.Fatalf("CartServiceMock.AddItemToCart mock is already set by ExpectParams functions")
	}

	mmAddItemToCart.defaultExpectation.params = &CartServiceMockAddItemToCartParams{ctx, userId, skuId, count}
	mmAddItemToCart.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmAddItemToCart.expectations {
		if minimock.Equal(e.params, mmAddItemToCart.defaultExpectation.params) {
			mmAddItemToCart.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmAddItemToCart.defaultExpectation.params)
		}
	}

	return mmAddItemToCart
}

// ExpectCtxParam1 sets up expected param ctx for cartService.AddItemToCart
func (mmAddItemToCart *mCartServiceMockAddItemToCart) ExpectCtxParam1(ctx context.Context) *mCartServiceMockAddItemToCart {
	if mmAddItemToCart.mock.funcAddItemToCart != nil {
		mmAddItemToCart.mock.t.Fatalf("CartServiceMock.AddItemToCart mock is already set by Set")
	}

	if mmAddItemToCart.defaultExpectation == nil {
		mmAddItemToCart.defaultExpectation = &CartServiceMockAddItemToCartExpectation{}
	}

	if mmAddItemToCart.defaultExpectation.params != nil {
		mmAddItemToCart.mock.t.Fatalf("CartServiceMock.AddItemToCart mock is already set by Expect")
	}

	if mmAddItemToCart.defaultExpectation.paramPtrs == nil {
		mmAddItemToCart.defaultExpectation.paramPtrs = &CartServiceMockAddItemToCartParamPtrs{}
	}
	mmAddItemToCart.defaultExpectation.paramPtrs.ctx = &ctx
	mmAddItemToCart.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmAddItemToCart
}

// ExpectUserIdParam2 sets up expected param userId for cartService.AddItemToCart
func (mmAddItemToCart *mCartServiceMockAddItemToCart) ExpectUserIdParam2(userId int64) *mCartServiceMockAddItemToCart {
	if mmAddItemToCart.mock.funcAddItemToCart != nil {
		mmAddItemToCart.mock.t.Fatalf("CartServiceMock.AddItemToCart mock is already set by Set")
	}

	if mmAddItemToCart.defaultExpectation == nil {
		mmAddItemToCart.defaultExpectation = &CartServiceMockAddItemToCartExpectation{}
	}

	if mmAddItemToCart.defaultExpectation.params != nil {
		mmAddItemToCart.mock.t.Fatalf("CartServiceMock.AddItemToCart mock is already set by Expect")
	}

	if mmAddItemToCart.defaultExpectation.paramPtrs == nil {
		mmAddItemToCart.defaultExpectation.paramPtrs = &CartServiceMockAddItemToCartParamPtrs{}
	}
	mmAddItemToCart.defaultExpectation.paramPtrs.userId = &userId
	mmAddItemToCart.defaultExpectation.expectationOrigins.originUserId = minimock.CallerInfo(1)

	return mmAddItemToCart
}

// ExpectSkuIdParam3 sets up expected param skuId for cartService.AddItemToCart
func (mmAddItemToCart *mCartServiceMockAddItemToCart) ExpectSkuIdParam3(skuId int64) *mCartServiceMockAddItemToCart {
	if mmAddItemToCart.mock.funcAddItemToCart != nil {
		mmAddItemToCart.mock.t.Fatalf("CartServiceMock.AddItemToCart mock is already set by Set")
	}

	if mmAddItemToCart.defaultExpectation == nil {
		mmAddItemToCart.defaultExpectation = &CartServiceMockAddItemToCartExpectation{}
	}

	if mmAddItemToCart.defaultExpectation.params != nil {
		mmAddItemToCart.mock.t.Fatalf("CartServiceMock.AddItemToCart mock is already set by Expect")
	}

	if mmAddItemToCart.defaultExpectation.paramPtrs == nil {
		mmAddItemToCart.defaultExpectation.paramPtrs = &CartServiceMockAddItemToCartParamPtrs{}
	}
	mmAddItemToCart.defaultExpectation.paramPtrs.skuId = &skuId
	mmAddItemToCart.defaultExpectation.expectationOrigins.originSkuId = minimock.CallerInfo(1)

	return mmAddItemToCart
}

// ExpectCountParam4 sets up expected param count for cartService.AddItemToCart
func (mmAddItemToCart *mCartServiceMockAddItemToCart) ExpectCountParam4(count uint32) *mCartServiceMockAddItemToCart {
	if mmAddItemToCart.mock.funcAddItemToCart != nil {
		mmAddItemToCart.mock.t.Fatalf("CartServiceMock.AddItemToCart mock is already set by Set")
	}

	if mmAddItemToCart.defaultExpectation == nil {
		mmAddItemToCart.defaultExpectation = &CartServiceMockAddItemToCartExpectation{}
	}

	if mmAddItemToCart.defaultExpectation.params != nil {
		mmAddItemToCart.mock.t.Fatalf("CartServiceMock.AddItemToCart mock is already set by Expect")
	}

	if mmAddItemToCart.defaultExpectation.paramPtrs == nil {
		mmAddItemToCart.defaultExpectation.paramPtrs = &CartServiceMockAddItemToCartParamPtrs{}
	}
	mmAddItemToCart.defaultExpectation.paramPtrs.count = &count
	mmAddItemToCart.defaultExpectation.expectationOrigins.originCount = minimock.CallerInfo(1)

	return mmAddItemToCart
}

// Inspect accepts an inspector function that has same arguments as the cartService.AddItemToCart
func (mmAddItemToCart *mCartServiceMockAddItemToCart) Inspect(f func(ctx context.Context, userId int64, skuId int64, count uint32)) *mCartServiceMockAddItemToCart {
	if mmAddItemToCart.mock.inspectFuncAddItemToCart != nil {
		mmAddItemToCart.mock.t.Fatalf("Inspect function is already set for CartServiceMock.AddItemToCart")
	}

	mmAddItemToCart.mock.inspectFuncAddItemToCart = f

	return mmAddItemToCart
}

// Return sets up results that will be returned by cartService.AddItemToCart
func (mmAddItemToCart *mCartServiceMockAddItemToCart) Return(err error) *CartServiceMock {
	if mmAddItemToCart.mock.funcAddItemToCart != nil {
		mmAddItemToCart.mock.t.Fatalf("CartServiceMock.AddItemToCart mock is already set by Set")
	}

	if mmAddItemToCart.defaultExpectation == nil {
		mmAddItemToCart.defaultExpectation = &CartServiceMockAddItemToCartExpectation{mock: mmAddItemToCart.mock}
	}
	mmAddItemToCart.defaultExpectation.results = &CartServiceMockAddItemToCartResults{err}
	mmAddItemToCart.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmAddItemToCart.mock
}

// Set uses given function f to mock the cartService.AddItemToCart method
func (mmAddItemToCart *mCartServiceMockAddItemToCart) Set(f func(ctx context.Context, userId int64, skuId int64, count uint32) (err error)) *CartServiceMock {
	if mmAddItemToCart.defaultExpectation != nil {
		mmAddItemToCart.mock.t.Fatalf("Default expectation is already set for the cartService.AddItemToCart method")
	}

	if len(mmAddItemToCart.expectations) > 0 {
		mmAddItemToCart.mock.t.Fatalf("Some expectations are already set for the cartService.AddItemToCart method")
	}

	mmAddItemToCart.mock.funcAddItemToCart = f
	mmAddItemToCart.mock.funcAddItemToCartOrigin = minimock.CallerInfo(1)
	return mmAddItemToCart.mock
}

// When sets expectation for the cartService.AddItemToCart which will trigger the result defined by the following
// Then helper
func (mmAddItemToCart *mCartServiceMockAddItemToCart) When(ctx context.Context, userId int64, skuId int64, count uint32) *CartServiceMockAddItemToCartExpectation {
	if mmAddItemToCart.mock.funcAddItemToCart != nil {
		mmAddItemToCart.mock.t.Fatalf("CartServiceMock.AddItemToCart mock is already set by Set")
	}

	expectation := &CartServiceMockAddItemToCartExpectation{
		mock:               mmAddItemToCart.mock,
		params:             &CartServiceMockAddItemToCartParams{ctx, userId, skuId, count},
		expectationOrigins: CartServiceMockAddItemToCartExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmAddItemToCart.expectations = append(mmAddItemToCart.expectations, expectation)
	return expectation
}

// Then sets up cartService.AddItemToCart return parameters for the expectation previously defined by the When method
func (e *CartServiceMockAddItemToCartExpectation) Then(err error) *CartServiceMock {
	e.results = &CartServiceMockAddItemToCartResults{err}
	return e.mock
}

// Times sets number of times cartService.AddItemToCart should be invoked
func (mmAddItemToCart *mCartServiceMockAddItemToCart) Times(n uint64) *mCartServiceMockAddItemToCart {
	if n == 0 {
		mmAddItemToCart.mock.t.Fatalf("Times of CartServiceMock.AddItemToCart mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmAddItemToCart.expectedInvocations, n)
	mmAddItemToCart.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmAddItemToCart
}

func (mmAddItemToCart *mCartServiceMockAddItemToCart) invocationsDone() bool {
	if len(mmAddItemToCart.expectations) == 0 && mmAddItemToCart.defaultExpectation == nil && mmAddItemToCart.mock.funcAddItemToCart == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmAddItemToCart.mock.afterAddItemToCartCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmAddItemToCart.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// AddItemToCart implements mm_handler.cartService
func (mmAddItemToCart *CartServiceMock) AddItemToCart(ctx context.Context, userId int64, skuId int64, count uint32) (err error) {
	mm_atomic.AddUint64(&mmAddItemToCart.beforeAddItemToCartCounter, 1)
	defer mm_atomic.AddUint64(&mmAddItemToCart.afterAddItemToCartCounter, 1)

	mmAddItemToCart.t.Helper()

	if mmAddItemToCart.inspectFuncAddItemToCart != nil {
		mmAddItemToCart.inspectFuncAddItemToCart(ctx, userId, skuId, count)
	}

	mm_params := CartServiceMockAddItemToCartParams{ctx, userId, skuId, count}

	// Record call args
	mmAddItemToCart.AddItemToCartMock.mutex.Lock()
	mmAddItemToCart.AddItemToCartMock.callArgs = append(mmAddItemToCart.AddItemToCartMock.callArgs, &mm_params)
	mmAddItemToCart.AddItemToCartMock.mutex.Unlock()

	for _, e := range mmAddItemToCart.AddItemToCartMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmAddItemToCart.AddItemToCartMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmAddItemToCart.AddItemToCartMock.defaultExpectation.Counter, 1)
		mm_want := mmAddItemToCart.AddItemToCartMock.defaultExpectation.params
		mm_want_ptrs := mmAddItemToCart.AddItemToCartMock.defaultExpectation.paramPtrs

		mm_got := CartServiceMockAddItemToCartParams{ctx, userId, skuId, count}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmAddItemToCart.t.Errorf("CartServiceMock.AddItemToCart got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAddItemToCart.AddItemToCartMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userId != nil && !minimock.Equal(*mm_want_ptrs.userId, mm_got.userId) {
				mmAddItemToCart.t.Errorf("CartServiceMock.AddItemToCart got unexpected parameter userId, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAddItemToCart.AddItemToCartMock.defaultExpectation.expectationOrigins.originUserId, *mm_want_ptrs.userId, mm_got.userId, minimock.Diff(*mm_want_ptrs.userId, mm_got.userId))
			}

			if mm_want_ptrs.skuId != nil && !minimock.Equal(*mm_want_ptrs.skuId, mm_got.skuId) {
				mmAddItemToCart.t.Errorf("CartServiceMock.AddItemToCart got unexpected parameter skuId, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAddItemToCart.AddItemToCartMock.defaultExpectation.expectationOrigins.originSkuId, *mm_want_ptrs.skuId, mm_got.skuId, minimock.Diff(*mm_want_ptrs.skuId, mm_got.skuId))
			}

			if mm_want_ptrs.count != nil && !minimock.Equal(*mm_want_ptrs.count, mm_got.count) {
				mmAddItemToCart.t.Errorf("CartServiceMock.AddItemToCart got unexpected parameter count, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAddItemToCart.AddItemToCartMock.defaultExpectation.expectationOrigins.originCount, *mm_want_ptrs.count, mm_got.count, minimock.Diff(*mm_want_ptrs.count, mm_got.count))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmAddItemToCart.t.Errorf("CartServiceMock.AddItemToCart got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmAddItemToCart.AddItemToCartMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmAddItemToCart.AddItemToCartMock.defaultExpectation.results
		if mm_results == nil {
			mmAddItemToCart.t.Fatal("No results are set for the CartServiceMock.AddItemToCart")
		}
		return (*mm_results).err
	}
	if mmAddItemToCart.funcAddItemToCart != nil {
		return mmAddItemToCart.funcAddItemToCart(ctx, userId, skuId, count)
	}
	mmAddItemToCart.t.Fatalf("Unexpected call to CartServiceMock.AddItemToCart. %v %v %v %v", ctx, userId, skuId, count)
	return
}

// AddItemToCartAfterCounter returns a count of finished CartServiceMock.AddItemToCart invocations
func (mmAddItemToCart *CartServiceMock) AddItemToCartAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAddItemToCart.afterAddItemToCartCounter)
}

// AddItemToCartBeforeCounter returns a count of CartServiceMock.AddItemToCart invocations
func (mmAddItemToCart *CartServiceMock) AddItemToCartBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAddItemToCart.beforeAddItemToCartCounter)
}

// Calls returns a list of arguments used in each call to CartServiceMock.AddItemToCart.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmAddItemToCart *mCartServiceMockAddItemToCart) Calls() []*CartServiceMockAddItemToCartParams {
	mmAddItemToCart.mutex.RLock()

	argCopy := make([]*CartServiceMockAddItemToCartParams, len(mmAddItemToCart.callArgs))
	copy(argCopy, mmAddItemToCart.callArgs)

	mmAddItemToCart.mutex.RUnlock()

	return argCopy
}

// MinimockAddItemToCartDone returns true if the count of the AddItemToCart invocations corresponds
// the number of defined expectations
func (m *CartServiceMock) MinimockAddItemToCartDone() bool {
	if m.AddItemToCartMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.AddItemToCartMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.AddItemToCartMock.invocationsDone()
}

// MinimockAddItemToCartInspect logs each unmet expectation
func (m *CartServiceMock) MinimockAddItemToCartInspect() {
	for _, e := range m.AddItemToCartMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CartServiceMock.AddItemToCart at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterAddItemToCartCounter := mm_atomic.LoadUint64(&m.afterAddItemToCartCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.AddItemToCartMock.defaultExpectation != nil && afterAddItemToCartCounter < 1 {
		if m.AddItemToCartMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CartServiceMock.AddItemToCart at\n%s", m.AddItemToCartMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CartServiceMock.AddItemToCart at\n%s with params: %#v", m.AddItemToCartMock.defaultExpectation.expectationOrigins.origin, *m.AddItemToCartMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAddItemToCart != nil && afterAddItemToCartCounter < 1 {
		m.t.Errorf("Expected call to CartServiceMock.AddItemToCart at\n%s", m.funcAddItemToCartOrigin)
	}

	if !m.AddItemToCartMock.invocationsDone() && afterAddItemToCartCounter > 0 {
		m.t.Errorf("Expected %d calls to CartServiceMock.AddItemToCart at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.AddItemToCartMock.expectedInvocations), m.AddItemToCartMock.expectedInvocationsOrigin, afterAddItemToCartCounter)
	}
}

type mCartServiceMockCancelOrder struct {
	optional           bool
	mock               *CartServiceMock
	defaultExpectation *CartServiceMockCancelOrderExpectation
	expectations       []*CartServiceMockCancelOrderExpectation

	callArgs []*CartServiceMockCancelOrderParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CartServiceMockCancelOrderExpectation specifies expectation struct of the cartService.CancelOrder
type CartServiceMockCancelOrderExpectation struct {
	mock               *CartServiceMock
	params             *CartServiceMockCancelOrderParams
	paramPtrs          *CartServiceMockCancelOrderParamPtrs
	expectationOrigins CartServiceMockCancelOrderExpectationOrigins
	results            *CartServiceMockCancelOrderResults
	returnOrigin       string
	Counter            uint64
}

// CartServiceMockCancelOrderParams contains parameters of the cartService.CancelOrder
type CartServiceMockCancelOrderParams struct {
	ctx     context.Context
	orderId int64
}

// CartServiceMockCancelOrderParamPtrs contains pointers to parameters of the cartService.CancelOrder
type CartServiceMockCancelOrderParamPtrs struct {
	ctx     *context.Context
	orderId *int64
}

// CartServiceMockCancelOrderResults contains results of the cartService.CancelOrder
type CartServiceMockCancelOrderResults struct {
	err error
}

// CartServiceMockCancelOrderOrigins contains origins of expectations of the cartService.CancelOrder
type CartServiceMockCancelOrderExpectationOrigins struct {
	origin        string
	originCtx     string
	originOrderId string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCancelOrder *mCartServiceMockCancelOrder) Optional() *mCartServiceMockCancelOrder {
	mmCancelOrder.optional = true
	return mmCancelOrder
}

// Expect sets up expected params for cartService.CancelOrder
func (mmCancelOrder *mCartServiceMockCancelOrder) Expect(ctx context.Context, orderId int64) *mCartServiceMockCancelOrder {
	if mmCancelOrder.mock.funcCancelOrder != nil {
		mmCancelOrder.mock.t.Fatalf("CartServiceMock.CancelOrder mock is already set by Set")
	}

	if mmCancelOrder.defaultExpectation == nil {
		mmCancelOrder.defaultExpectation = &CartServiceMockCancelOrderExpectation{}
	}

	if mmCancelOrder.defaultExpectation.paramPtrs != nil {
		mmCancelOrder.mock.t.Fatalf("CartServiceMock.CancelOrder mock is already set by ExpectParams functions")
	}

	mmCancelOrder.defaultExpectation.params = &CartServiceMockCancelOrderParams{ctx, orderId}
	mmCancelOrder.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCancelOrder.expectations {
		if minimock.Equal(e.params, mmCancelOrder.defaultExpectation.params) {
			mmCancelOrder.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCancelOrder.defaultExpectation.params)
		}
	}

	return mmCancelOrder
}

// ExpectCtxParam1 sets up expected param ctx for cartService.CancelOrder
func (mmCancelOrder *mCartServiceMockCancelOrder) ExpectCtxParam1(ctx context.Context) *mCartServiceMockCancelOrder {
	if mmCancelOrder.mock.funcCancelOrder != nil {
		mmCancelOrder.mock.t.Fatalf("CartServiceMock.CancelOrder mock is already set by Set")
	}

	if mmCancelOrder.defaultExpectation == nil {
		mmCancelOrder.defaultExpectation = &CartServiceMockCancelOrderExpectation{}
	}

	if mmCancelOrder.defaultExpectation.params != nil {
		mmCancelOrder.mock.t.Fatalf("CartServiceMock.CancelOrder mock is already set by Expect")
	}

	if mmCancelOrder.defaultExpectation.paramPtrs == nil {
		mmCancelOrder.defaultExpectation.paramPtrs = &CartServiceMockCancelOrderParamPtrs{}
	}
	mmCancelOrder.defaultExpectation.paramPtrs.ctx = &ctx
	mmCancelOrder.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCancelOrder
}

// ExpectOrderIdParam2 sets up expected param orderId for cartService.CancelOrder
func (mmCancelOrder *mCartServiceMockCancelOrder) ExpectOrderIdParam2(orderId int64) *mCartServiceMockCancelOrder {
	if mmCancelOrder.mock.funcCancelOrder != nil {
		mmCancelOrder.mock.t.Fatalf("CartServiceMock.CancelOrder mock is already set by Set")
	}

	if mmCancelOrder.defaultExpectation == nil {
		mmCancelOrder.defaultExpectation = &CartServiceMockCancelOrderExpectation{}
	}

	if mmCancelOrder.defaultExpectation.params != nil {
		mmCancelOrder.mock.t.Fatalf("CartServiceMock.CancelOrder mock is already set by Expect")
	}

	if mmCancelOrder.defaultExpectation.paramPtrs == nil {
		mmCancelOrder.defaultExpectation.paramPtrs = &CartServiceMockCancelOrderParamPtrs{}
	}
	mmCancelOrder.defaultExpectation.paramPtrs.orderId = &orderId
	mmCancelOrder.defaultExpectation.expectationOrigins.originOrderId = minimock.CallerInfo(1)

	return mmCancelOrder
}

// Inspect accepts an inspector function that has same arguments as the cartService.CancelOrder
func (mmCancelOrder *mCartServiceMockCancelOrder) Inspect(f func(ctx context.Context, orderId int64)) *mCartServiceMockCancelOrder {
	if mmCancelOrder.mock.inspectFuncCancelOrder != nil {
		mmCancelOrder.mock.t.Fatalf("Inspect function is already set for CartServiceMock.CancelOrder")
	}

	mmCancelOrder.mock.inspectFuncCancelOrder = f

	return mmCancelOrder
}

// Return sets up results that will be returned by cartService.CancelOrder
func (mmCancelOrder *mCartServiceMockCancelOrder) Return(err error) *CartServiceMock {
	if mmCancelOrder.mock.funcCancelOrder != nil {
		mmCancelOrder.mock.t.Fatalf("CartServiceMock.CancelOrder mock is already set by Set")
	}

	if mmCancelOrder.defaultExpectation == nil {
		mmCancelOrder.defaultExpectation = &CartServiceMockCancelOrderExpectation{mock: mmCancelOrder.mock}
	}
	mmCancelOrder.defaultExpectation.results = &CartServiceMockCancelOrderResults{err}
	mmCancelOrder.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCancelOrder.mock
}

// Set uses given function f to mock the cartService.CancelOrder method
func (mmCancelOrder *mCartServiceMockCancelOrder) Set(f func(ctx context.Context, orderId int64) (err error)) *CartServiceMock {
	if mmCancelOrder.defaultExpectation != nil {
		mmCancelOrder.mock.t.Fatalf("Default expectation is already set for the cartService.CancelOrder method")
	}

	if len(mmCancelOrder.expectations) > 0 {
		mmCancelOrder.mock.t.Fatalf("Some expectations are already set for the cartService.CancelOrder method")
	}

	mmCancelOrder.mock.funcCancelOrder = f
	mmCancelOrder.mock.funcCancelOrderOrigin = minimock.CallerInfo(1)
	return mmCancelOrder.mock
}

// When sets expectation for the cartService.CancelOrder which will trigger the result defined by the following
// Then helper
func (mmCancelOrder *mCartServiceMockCancelOrder) When(ctx context.Context, orderId int64) *CartServiceMockCancelOrderExpectation {
	if mmCancelOrder.mock.funcCancelOrder != nil {
		mmCancelOrder.mock.t.Fatalf("CartServiceMock.CancelOrder mock is already set by Set")
	}

	expectation := &CartServiceMockCancelOrderExpectation{
		mock:               mmCancelOrder.mock,
		params:             &CartServiceMockCancelOrderParams{ctx, orderId},
		expectationOrigins: CartServiceMockCancelOrderExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCancelOrder.expectations = append(mmCancelOrder.expectations, expectation)
	return expectation
}

// Then sets up cartService.CancelOrder return parameters for the expectation previously defined by the When method
func (e *CartServiceMockCancelOrderExpectation) Then(err error) *CartServiceMock {
	e.results = &CartServiceMockCancelOrderResults{err}
	return e.mock
}

// Times sets number of times cartService.CancelOrder should be invoked
func (mmCancelOrder *mCartServiceMockCancelOrder) Times(n uint64) *mCartServiceMockCancelOrder {
	if n == 0 {
		mmCancelOrder.mock.t.Fatalf("Times of CartServiceMock.CancelOrder mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCancelOrder.expectedInvocations, n)
	mmCancelOrder.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCancelOrder
}

func (mmCancelOrder *mCartServiceMockCancelOrder) invocationsDone() bool {
	if len(mmCancelOrder.expectations) == 0 && mmCancelOrder.defaultExpectation == nil && mmCancelOrder.mock.funcCancelOrder == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCancelOrder.mock.afterCancelOrderCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCancelOrder.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CancelOrder implements mm_handler.cartService
func (mmCancelOrder *CartServiceMock) CancelOrder(ctx context.Context, orderId int64) (err error) {
	mm_atomic.AddUint64(&mmCancelOrder.beforeCancelOrderCounter, 1)
	defer mm_atomic.AddUint64(&mmCancelOrder.afterCancelOrderCounter, 1)

	mmCancelOrder.t.Helper()

	if mmCancelOrder.inspectFuncCancelOrder != nil {
		mmCancelOrder.inspectFuncCancelOrder(ctx, orderId)
	}

	mm_params := CartServiceMockCancelOrderParams{ctx, orderId}

	// Record call args
	mmCancelOrder.CancelOrderMock.mutex.Lock()
	mmCancelOrder.CancelOrderMock.callArgs = append(mmCancelOrder.CancelOrderMock.callArgs, &mm_params)
	mmCancelOrder.CancelOrderMock.mutex.Unlock()

	for _, e := range mmCancelOrder.CancelOrderMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmCancelOrder.CancelOrderMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCancelOrder.CancelOrderMock.defaultExpectation.Counter, 1)
		mm_want := mmCancelOrder.CancelOrderMock.defaultExpectation.params
		mm_want_ptrs := mmCancelOrder.CancelOrderMock.defaultExpectation.paramPtrs

		mm_got := CartServiceMockCancelOrderParams{ctx, orderId}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCancelOrder.t.Errorf("CartServiceMock.CancelOrder got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCancelOrder.CancelOrderMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.orderId != nil && !minimock.Equal(*mm_want_ptrs.orderId, mm_got.orderId) {
				mmCancelOrder.t.Errorf("CartServiceMock.CancelOrder got unexpected parameter orderId, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCancelOrder.CancelOrderMock.defaultExpectation.expectationOrigins.originOrderId, *mm_want_ptrs.orderId, mm_got.orderId, minimock.Diff(*mm_want_ptrs.orderId, mm_got.orderId))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCancelOrder.t.Errorf("CartServiceMock.CancelOrder got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCancelOrder.CancelOrderMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCancelOrder.CancelOrderMock.defaultExpectation.results
		if mm_results == nil {
			mmCancelOrder.t.Fatal("No results are set for the CartServiceMock.CancelOrder")
		}
		return (*mm_results).err
	}
	if mmCancelOrder.funcCancelOrder != nil {
		return mmCancelOrder.funcCancelOrder(ctx, orderId)
	}
	mmCancelOrder.t.Fatalf("Unexpected call to CartServiceMock.CancelOrder. %v %v", ctx, orderId)
	return
}

// CancelOrderAfterCounter returns a count of finished CartServiceMock.CancelOrder invocations
func (mmCancelOrder *CartServiceMock) CancelOrderAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCancelOrder.afterCancelOrderCounter)
}

// CancelOrderBeforeCounter returns a count of CartServiceMock.CancelOrder invocations
func (mmCancelOrder *CartServiceMock) CancelOrderBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCancelOrder.beforeCancelOrderCounter)
}

// Calls returns a list of arguments used in each call to CartServiceMock.CancelOrder.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCancelOrder *mCartServiceMockCancelOrder) Calls() []*CartServiceMockCancelOrderParams {
	mmCancelOrder.mutex.RLock()

	argCopy := make([]*CartServiceMockCancelOrderParams, len(mmCancelOrder.callArgs))
	copy(argCopy, mmCancelOrder.callArgs)

	mmCancelOrder.mutex.RUnlock()

	return argCopy
}

// MinimockCancelOrderDone returns true if the count of the CancelOrder invocations corresponds
// the number of defined expectations
func (m *CartServiceMock) MinimockCancelOrderDone() bool {
	if m.CancelOrderMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CancelOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CancelOrderMock.invocationsDone()
}

// MinimockCancelOrderInspect logs each unmet expectation
func (m *CartServiceMock) MinimockCancelOrderInspect() {
	for _, e := range m.CancelOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CartServiceMock.CancelOrder at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCancelOrderCounter := mm_atomic.LoadUint64(&m.afterCancelOrderCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CancelOrderMock.defaultExpectation != nil && afterCancelOrderCounter < 1 {
		if m.CancelOrderMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CartServiceMock.CancelOrder at\n%s", m.CancelOrderMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CartServiceMock.CancelOrder at\n%s with params: %#v", m.CancelOrderMock.defaultExpectation.expectationOrigins.origin, *m.CancelOrderMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCancelOrder != nil && afterCancelOrderCounter < 1 {
		m.t.Errorf("Expected call to CartServiceMock.CancelOrder at\n%s", m.funcCancelOrderOrigin)
	}

	if !m.CancelOrderMock.invocationsDone() && afterCancelOrderCounter > 0 {
		m.t.Errorf("Expected %d calls to CartServiceMock.CancelOrder at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CancelOrderMock.expectedInvocations), m.CancelOrderMock.expectedInvocationsOrigin, afterCancelOrderCounter)
	}
}

type mCartServiceMockCheckout struct {
	optional           bool
	mock               *CartServiceMock
	defaultExpectation *CartServiceMockCheckoutExpectation
	expectations       []*CartServiceMockCheckoutExpectation

	callArgs []*CartServiceMockCheckoutParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CartServiceMockCheckoutExpectation specifies expectation struct of the cartService.Checkout
type CartServiceMockCheckoutExpectation struct {
	mock               *CartServiceMock
	params             *CartServiceMockCheckoutParams
	paramPtrs          *CartServiceMockCheckoutParamPtrs
	expectationOrigins CartServiceMockCheckoutExpectationOrigins
	results            *CartServiceMockCheckoutResults
	returnOrigin       string
	Counter            uint64
}

// CartServiceMockCheckoutParams contains parameters of the cartService.Checkout
type CartServiceMockCheckoutParams struct {
	ctx    context.Context
	userId int64
}

// CartServiceMockCheckoutParamPtrs contains pointers to parameters of the cartService.Checkout
type CartServiceMockCheckoutParamPtrs struct {
	ctx    *context.Context
	userId *int64
}

// CartServiceMockCheckoutResults contains results of the cartService.Checkout
type CartServiceMockCheckoutResults struct {
	i1  int64
	err error
}

// CartServiceMockCheckoutOrigins contains origins of expectations of the cartService.Checkout
type CartServiceMockCheckoutExpectationOrigins struct {
	origin       string
	originCtx    string
	originUserId string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCheckout *mCartServiceMockCheckout) Optional() *mCartServiceMockCheckout {
	mmCheckout.optional = true
	return mmCheckout
}

// Expect sets up expected params for cartService.Checkout
func (mmCheckout *mCartServiceMockCheckout) Expect(ctx context.Context, userId int64) *mCartServiceMockCheckout {
	if mmCheckout.mock.funcCheckout != nil {
		mmCheckout.mock.t.Fatalf("CartServiceMock.Checkout mock is already set by Set")
	}

	if mmCheckout.defaultExpectation == nil {
		mmCheckout.defaultExpectation = &CartServiceMockCheckoutExpectation{}
	}

	if mmCheckout.defaultExpectation.paramPtrs != nil {
		mmCheckout.mock.t.Fatalf("CartServiceMock.Checkout mock is already set by ExpectParams functions")
	}

	mmCheckout.defaultExpectation.params = &CartServiceMockCheckoutParams{ctx, userId}
	mmCheckout.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCheckout.expectations {
		if minimock.Equal(e.params, mmCheckout.defaultExpectation.params) {
			mmCheckout.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCheckout.defaultExpectation.params)
		}
	}

	return mmCheckout
}

// ExpectCtxParam1 sets up expected param ctx for cartService.Checkout
func (mmCheckout *mCartServiceMockCheckout) ExpectCtxParam1(ctx context.Context) *mCartServiceMockCheckout {
	if mmCheckout.mock.funcCheckout != nil {
		mmCheckout.mock.t.Fatalf("CartServiceMock.Checkout mock is already set by Set")
	}

	if mmCheckout.defaultExpectation == nil {
		mmCheckout.defaultExpectation = &CartServiceMockCheckoutExpectation{}
	}

	if mmCheckout.defaultExpectation.params != nil {
		mmCheckout.mock.t.Fatalf("CartServiceMock.Checkout mock is already set by Expect")
	}

	if mmCheckout.defaultExpectation.paramPtrs == nil {
		mmCheckout.defaultExpectation.paramPtrs = &CartServiceMockCheckoutParamPtrs{}
	}
	mmCheckout.defaultExpectation.paramPtrs.ctx = &ctx
	mmCheckout.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCheckout
}

// ExpectUserIdParam2 sets up expected param userId for cartService.Checkout
func (mmCheckout *mCartServiceMockCheckout) ExpectUserIdParam2(userId int64) *mCartServiceMockCheckout {
	if mmCheckout.mock.funcCheckout != nil {
		mmCheckout.mock.t.Fatalf("CartServiceMock.Checkout mock is already set by Set")
	}

	if mmCheckout.defaultExpectation == nil {
		mmCheckout.defaultExpectation = &CartServiceMockCheckoutExpectation{}
	}

	if mmCheckout.defaultExpectation.params != nil {
		mmCheckout.mock.t.Fatalf("CartServiceMock.Checkout mock is already set by Expect")
	}

	if mmCheckout.defaultExpectation.paramPtrs == nil {
		mmCheckout.defaultExpectation.paramPtrs = &CartServiceMockCheckoutParamPtrs{}
	}
	mmCheckout.defaultExpectation.paramPtrs.userId = &userId
	mmCheckout.defaultExpectation.expectationOrigins.originUserId = minimock.CallerInfo(1)

	return mmCheckout
}

// Inspect accepts an inspector function that has same arguments as the cartService.Checkout
func (mmCheckout *mCartServiceMockCheckout) Inspect(f func(ctx context.Context, userId int64)) *mCartServiceMockCheckout {
	if mmCheckout.mock.inspectFuncCheckout != nil {
		mmCheckout.mock.t.Fatalf("Inspect function is already set for CartServiceMock.Checkout")
	}

	mmCheckout.mock.inspectFuncCheckout = f

	return mmCheckout
}

// Return sets up results that will be returned by cartService.Checkout
func (mmCheckout *mCartServiceMockCheckout) Return(i1 int64, err error) *CartServiceMock {
	if mmCheckout.mock.funcCheckout != nil {
		mmCheckout.mock.t.Fatalf("CartServiceMock.Checkout mock is already set by Set")
	}

	if mmCheckout.defaultExpectation == nil {
		mmCheckout.defaultExpectation = &CartServiceMockCheckoutExpectation{mock: mmCheckout.mock}
	}
	mmCheckout.defaultExpectation.results = &CartServiceMockCheckoutResults{i1, err}
	mmCheckout.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCheckout.mock
}

// Set uses given function f to mock the cartService.Checkout method
func (mmCheckout *mCartServiceMockCheckout) Set(f func(ctx context.Context, userId int64) (i1 int64, err error)) *CartServiceMock {
	if mmCheckout.defaultExpectation != nil {
		mmCheckout.mock.t.Fatalf("Default expectation is already set for the cartService.Checkout method")
	}

	if len(mmCheckout.expectations) > 0 {
		mmCheckout.mock.t.Fatalf("Some expectations are already set for the cartService.Checkout method")
	}

	mmCheckout.mock.funcCheckout = f
	mmCheckout.mock.funcCheckoutOrigin = minimock.CallerInfo(1)
	return mmCheckout.mock
}

// When sets expectation for the cartService.Checkout which will trigger the result defined by the following
// Then helper
func (mmCheckout *mCartServiceMockCheckout) When(ctx context.Context, userId int64) *CartServiceMockCheckoutExpectation {
	if mmCheckout.mock.funcCheckout != nil {
		mmCheckout.mock.t.Fatalf("CartServiceMock.Checkout mock is already set by Set")
	}

	expectation := &CartServiceMockCheckoutExpectation{
		mock:               mmCheckout.mock,
		params:             &CartServiceMockCheckoutParams{ctx, userId},
		expectationOrigins: CartServiceMockCheckoutExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCheckout.expectations = append(mmCheckout.expectations, expectation)
	return expectation
}

// Then sets up cartService.Checkout return parameters for the expectation previously defined by the When method
func (e *CartServiceMockCheckoutExpectation) Then(i1 int64, err error) *CartServiceMock {
	e.results = &CartServiceMockCheckoutResults{i1, err}
	return e.mock
}

// Times sets number of times cartService.Checkout should be invoked
func (mmCheckout *mCartServiceMockCheckout) Times(n uint64) *mCartServiceMockCheckout {
	if n == 0 {
		mmCheckout.mock.t.Fatalf("Times of CartServiceMock.Checkout mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCheckout.expectedInvocations, n)
	mmCheckout.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCheckout
}

func (mmCheckout *mCartServiceMockCheckout) invocationsDone() bool {
	if len(mmCheckout.expectations) == 0 && mmCheckout.defaultExpectation == nil && mmCheckout.mock.funcCheckout == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCheckout.mock.afterCheckoutCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCheckout.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// Checkout implements mm_handler.cartService
func (mmCheckout *CartServiceMock) Checkout(ctx context.Context, userId int64) (i1 int64, err error) {
	mm_atomic.AddUint64(&mmCheckout.beforeCheckoutCounter, 1)
	defer mm_atomic.AddUint64(&mmCheckout.afterCheckoutCounter, 1)

	mmCheckout.t.Helper()

	if mmCheckout.inspectFuncCheckout != nil {
		mmCheckout.inspectFuncCheckout(ctx, userId)
	}

	mm_params := CartServiceMockCheckoutParams{ctx, userId}

	// Record call args
	mmCheckout.CheckoutMock.mutex.Lock()
	mmCheckout.CheckoutMock.callArgs = append(mmCheckout.CheckoutMock.callArgs, &mm_params)
	mmCheckout.CheckoutMock.mutex.Unlock()

	for _, e := range mmCheckout.CheckoutMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmCheckout.CheckoutMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCheckout.CheckoutMock.defaultExpectation.Counter, 1)
		mm_want := mmCheckout.CheckoutMock.defaultExpectation.params
		mm_want_ptrs := mmCheckout.CheckoutMock.defaultExpectation.paramPtrs

		mm_got := CartServiceMockCheckoutParams{ctx, userId}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCheckout.t.Errorf("CartServiceMock.Checkout got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCheckout.CheckoutMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userId != nil && !minimock.Equal(*mm_want_ptrs.userId, mm_got.userId) {
				mmCheckout.t.Errorf("CartServiceMock.Checkout got unexpected parameter userId, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCheckout.CheckoutMock.defaultExpectation.expectationOrigins.originUserId, *mm_want_ptrs.userId, mm_got.userId, minimock.Diff(*mm_want_ptrs.userId, mm_got.userId))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCheckout.t.Errorf("CartServiceMock.Checkout got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCheckout.CheckoutMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCheckout.CheckoutMock.defaultExpectation.results
		if mm_results == nil {
			mmCheckout.t.Fatal("No results are set for the CartServiceMock.Checkout")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmCheckout.funcCheckout != nil {
		return mmCheckout.funcCheckout(ctx, userId)
	}
	mmCheckout.t.Fatalf("Unexpected call to CartServiceMock.Checkout. %v %v", ctx, userId)
	return
}

// CheckoutAfterCounter returns a count of finished CartServiceMock.Checkout invocations
func (mmCheckout *CartServiceMock) CheckoutAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCheckout.afterCheckoutCounter)
}

// CheckoutBeforeCounter returns a count of CartServiceMock.Checkout invocations
func (mmCheckout *CartServiceMock) CheckoutBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCheckout.beforeCheckoutCounter)
}

// Calls returns a list of arguments used in each call to CartServiceMock.Checkout.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCheckout *mCartServiceMockCheckout) Calls() []*CartServiceMockCheckoutParams {
	mmCheckout.mutex.RLock()

	argCopy := make([]*CartServiceMockCheckoutParams, len(mmCheckout.callArgs))
	copy(argCopy, mmCheckout.callArgs)

	mmCheckout.mutex.RUnlock()

	return argCopy
}

// MinimockCheckoutDone returns true if the count of the Checkout invocations corresponds
// the number of defined expectations
func (m *CartServiceMock) MinimockCheckoutDone() bool {
	if m.CheckoutMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CheckoutMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CheckoutMock.invocationsDone()
}

// MinimockCheckoutInspect logs each unmet expectation
func (m *CartServiceMock) MinimockCheckoutInspect() {
	for _, e := range m.CheckoutMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CartServiceMock.Checkout at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCheckoutCounter := mm_atomic.LoadUint64(&m.afterCheckoutCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CheckoutMock.defaultExpectation != nil && afterCheckoutCounter < 1 {
		if m.CheckoutMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CartServiceMock.Checkout at\n%s", m.CheckoutMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CartServiceMock.Checkout at\n%s with params: %#v", m.CheckoutMock.defaultExpectation.expectationOrigins.origin, *m.CheckoutMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCheckout != nil && afterCheckoutCounter < 1 {
		m.t.Errorf("Expected call to CartServiceMock.Checkout at\n%s", m.funcCheckoutOrigin)
	}

	if !m.CheckoutMock.invocationsDone() && afterCheckoutCounter > 0 {
		m.t.Errorf("Expected %d calls to CartServiceMock.Checkout at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CheckoutMock.expectedInvocations), m.CheckoutMock.expectedInvocationsOrigin, afterCheckoutCounter)
	}
}

type mCartServiceMockDeleteFromCart struct {
	optional           bool
	mock               *CartServiceMock
	defaultExpectation *CartServiceMockDeleteFromCartExpectation
	expectations       []*CartServiceMockDeleteFromCartExpectation

	callArgs []*CartServiceMockDeleteFromCartParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CartServiceMockDeleteFromCartExpectation specifies expectation struct of the cartService.DeleteFromCart
type CartServiceMockDeleteFromCartExpectation struct {
	mock               *CartServiceMock
	params             *CartServiceMockDeleteFromCartParams
	paramPtrs          *CartServiceMockDeleteFromCartParamPtrs
	expectationOrigins CartServiceMockDeleteFromCartExpectationOrigins
	results            *CartServiceMockDeleteFromCartResults
	returnOrigin       string
	Counter            uint64
}

// CartServiceMockDeleteFromCartParams contains parameters of the cartService.DeleteFromCart
type CartServiceMockDeleteFromCartParams struct {
	ctx    context.Context
	userId int64
	skuId  int64
}

// CartServiceMockDeleteFromCartParamPtrs contains pointers to parameters of the cartService.DeleteFromCart
type CartServiceMockDeleteFromCartParamPtrs struct {
	ctx    *context.Context
	userId *int64
	skuId  *int64
}

// CartServiceMockDeleteFromCartResults contains results of the cartService.DeleteFromCart
type CartServiceMockDeleteFromCartResults struct {
	err error
}

// CartServiceMockDeleteFromCartOrigins contains origins of expectations of the cartService.DeleteFromCart
type CartServiceMockDeleteFromCartExpectationOrigins struct {
	origin       string
	originCtx    string
	originUserId string
	originSkuId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDeleteFromCart *mCartServiceMockDeleteFromCart) Optional() *mCartServiceMockDeleteFromCart {
	mmDeleteFromCart.optional = true
	return mmDeleteFromCart
}

// Expect sets up expected params for cartService.DeleteFromCart
func (mmDeleteFromCart *mCartServiceMockDeleteFromCart) Expect(ctx context.Context, userId int64, skuId int64) *mCartServiceMockDeleteFromCart {
	if mmDeleteFromCart.mock.funcDeleteFromCart != nil {
		mmDeleteFromCart.mock.t.Fatalf("CartServiceMock.DeleteFromCart mock is already set by Set")
	}

	if mmDeleteFromCart.defaultExpectation == nil {
		mmDeleteFromCart.defaultExpectation = &CartServiceMockDeleteFromCartExpectation{}
	}

	if mmDeleteFromCart.defaultExpectation.paramPtrs != nil {
		mmDeleteFromCart.mock.t.Fatalf("CartServiceMock.DeleteFromCart mock is already set by ExpectParams functions")
	}

	mmDeleteFromCart.defaultExpectation.params = &CartServiceMockDeleteFromCartParams{ctx, userId, skuId}
	mmDeleteFromCart.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDeleteFromCart.expectations {
		if minimock.Equal(e.params, mmDeleteFromCart.defaultExpectation.params) {
			mmDeleteFromCart.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDeleteFromCart.defaultExpectation.params)
		}
	}

	return mmDeleteFromCart
}

// ExpectCtxParam1 sets up expected param ctx for cartService.DeleteFromCart
func (mmDeleteFromCart *mCartServiceMockDeleteFromCart) ExpectCtxParam1(ctx context.Context) *mCartServiceMockDeleteFromCart {
	if mmDeleteFromCart.mock.funcDeleteFromCart != nil {
		mmDeleteFromCart.mock.t.Fatalf("CartServiceMock.DeleteFromCart mock is already set by Set")
	}

	if mmDeleteFromCart.defaultExpectation == nil {
		mmDeleteFromCart.defaultExpectation = &CartServiceMockDeleteFromCartExpectation{}
	}

	if mmDeleteFromCart.defaultExpectation.params != nil {
		mmDeleteFromCart.mock.t.Fatalf("CartServiceMock.DeleteFromCart mock is already set by Expect")
	}

	if mmDeleteFromCart.defaultExpectation.paramPtrs == nil {
		mmDeleteFromCart.defaultExpectation.paramPtrs = &CartServiceMockDeleteFromCartParamPtrs{}
	}
	mmDeleteFromCart.defaultExpectation.paramPtrs.ctx = &ctx
	mmDeleteFromCart.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmDeleteFromCart
}

// ExpectUserIdParam2 sets up expected param userId for cartService.DeleteFromCart
func (mmDeleteFromCart *mCartServiceMockDeleteFromCart) ExpectUserIdParam2(userId int64) *mCartServiceMockDeleteFromCart {
	if mmDeleteFromCart.mock.funcDeleteFromCart != nil {
		mmDeleteFromCart.mock.t.Fatalf("CartServiceMock.DeleteFromCart mock is already set by Set")
	}

	if mmDeleteFromCart.defaultExpectation == nil {
		mmDeleteFromCart.defaultExpectation = &CartServiceMockDeleteFromCartExpectation{}
	}

	if mmDeleteFromCart.defaultExpectation.params != nil {
		mmDeleteFromCart.mock.t.Fatalf("CartServiceMock.DeleteFromCart mock is already set by Expect")
	}

	if mmDeleteFromCart.defaultExpectation.paramPtrs == nil {
		mmDeleteFromCart.defaultExpectation.paramPtrs = &CartServiceMockDeleteFromCartParamPtrs{}
	}
	mmDeleteFromCart.defaultExpectation.paramPtrs.userId = &userId
	mmDeleteFromCart.defaultExpectation.expectationOrigins.originUserId = minimock.CallerInfo(1)

	return mmDeleteFromCart
}

// ExpectSkuIdParam3 sets up expected param skuId for cartService.DeleteFromCart
func (mmDeleteFromCart *mCartServiceMockDeleteFromCart) ExpectSkuIdParam3(skuId int64) *mCartServiceMockDeleteFromCart {
	if mmDeleteFromCart.mock.funcDeleteFromCart != nil {
		mmDeleteFromCart.mock.t.Fatalf("CartServiceMock.DeleteFromCart mock is already set by Set")
	}

	if mmDeleteFromCart.defaultExpectation == nil {
		mmDeleteFromCart.defaultExpectation = &CartServiceMockDeleteFromCartExpectation{}
	}

	if mmDeleteFromCart.defaultExpectation.params != nil {
		mmDeleteFromCart.mock.t.Fatalf("CartServiceMock.DeleteFromCart mock is already set by Expect")
	}

	if mmDeleteFromCart.defaultExpectation.paramPtrs == nil {
		mmDeleteFromCart.defaultExpectation.paramPtrs = &CartServiceMockDeleteFromCartParamPtrs{}
	}
	mmDeleteFromCart.defaultExpectation.paramPtrs.skuId = &skuId
	mmDeleteFromCart.defaultExpectation.expectationOrigins.originSkuId = minimock.CallerInfo(1)

	return mmDeleteFromCart
}

// Inspect accepts an inspector function that has same arguments as the cartService.DeleteFromCart
func (mmDeleteFromCart *mCartServiceMockDeleteFromCart) Inspect(f func(ctx context.Context, userId int64, skuId int64)) *mCartServiceMockDeleteFromCart {
	if mmDeleteFromCart.mock.inspectFuncDeleteFromCart != nil {
		mmDeleteFromCart.mock.t.Fatalf("Inspect function is already set for CartServiceMock.DeleteFromCart")
	}

	mmDeleteFromCart.mock.inspectFuncDeleteFromCart = f

	return mmDeleteFromCart
}

// Return sets up results that will be returned by cartService.DeleteFromCart
func (mmDeleteFromCart *mCartServiceMockDeleteFromCart) Return(err error) *CartServiceMock {
	if mmDeleteFromCart.mock.funcDeleteFromCart != nil {
		mmDeleteFromCart.mock.t.Fatalf("CartServiceMock.DeleteFromCart mock is already set by Set")
	}

	if mmDeleteFromCart.defaultExpectation == nil {
		mmDeleteFromCart.defaultExpectation = &CartServiceMockDeleteFromCartExpectation{mock: mmDeleteFromCart.mock}
	}
	mmDeleteFromCart.defaultExpectation.results = &CartServiceMockDeleteFromCartResults{err}
	mmDeleteFromCart.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDeleteFromCart.mock
}

// Set uses given function f to mock the cartService.DeleteFromCart method
func (mmDeleteFromCart *mCartServiceMockDeleteFromCart) Set(f func(ctx context.Context, userId int64, skuId int64) (err error)) *CartServiceMock {
	if mmDeleteFromCart.defaultExpectation != nil {
		mmDeleteFromCart.mock.t.Fatalf("Default expectation is already set for the cartService.DeleteFromCart method")
	}

	if len(mmDeleteFromCart.expectations) > 0 {
		mmDeleteFromCart.mock.t.Fatalf("Some expectations are already set for the cartService.DeleteFromCart method")
	}

	mmDeleteFromCart.mock.funcDeleteFromCart = f
	mmDeleteFromCart.mock.funcDeleteFromCartOrigin = minimock.CallerInfo(1)
	return mmDeleteFromCart.mock
}

// When sets expectation for the cartService.DeleteFromCart which will trigger the result defined by the following
// Then helper
func (mmDeleteFromCart *mCartServiceMockDeleteFromCart) When(ctx context.Context, userId int64, skuId int64) *CartServiceMockDeleteFromCartExpectation {
	if mmDeleteFromCart.mock.funcDeleteFromCart != nil {
		mmDeleteFromCart.mock.t.Fatalf("CartServiceMock.DeleteFromCart mock is already set by Set")
	}

	expectation := &CartServiceMockDeleteFromCartExpectation{
		mock:               mmDeleteFromCart.mock,
		params:             &CartServiceMockDeleteFromCartParams{ctx, userId, skuId},
		expectationOrigins: CartServiceMockDeleteFromCartExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDeleteFromCart.expectations = append(mmDeleteFromCart.expectations, expectation)
	return expectation
}

// Then sets up cartService.DeleteFromCart return parameters for the expectation previously defined by the When method
func (e *CartServiceMockDeleteFromCartExpectation) Then(err error) *CartServiceMock {
	e.results = &CartServiceMockDeleteFromCartResults{err}
	return e.mock
}

// Times sets number of times cartService.DeleteFromCart should be invoked
func (mmDeleteFromCart *mCartServiceMockDeleteFromCart) Times(n uint64) *mCartServiceMockDeleteFromCart {
	if n == 0 {
		mmDeleteFromCart.mock.t.Fatalf("Times of CartServiceMock.DeleteFromCart mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDeleteFromCart.expectedInvocations, n)
	mmDeleteFromCart.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDeleteFromCart
}

func (mmDeleteFromCart *mCartServiceMockDeleteFromCart) invocationsDone() bool {
	if len(mmDeleteFromCart.expectations) == 0 && mmDeleteFromCart.defaultExpectation == nil && mmDeleteFromCart.mock.funcDeleteFromCart == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDeleteFromCart.mock.afterDeleteFromCartCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDeleteFromCart.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DeleteFromCart implements mm_handler.cartService
func (mmDeleteFromCart *CartServiceMock) DeleteFromCart(ctx context.Context, userId int64, skuId int64) (err error) {
	mm_atomic.AddUint64(&mmDeleteFromCart.beforeDeleteFromCartCounter, 1)
	defer mm_atomic.AddUint64(&mmDeleteFromCart.afterDeleteFromCartCounter, 1)

	mmDeleteFromCart.t.Helper()

	if mmDeleteFromCart.inspectFuncDeleteFromCart != nil {
		mmDeleteFromCart.inspectFuncDeleteFromCart(ctx, userId, skuId)
	}

	mm_params := CartServiceMockDeleteFromCartParams{ctx, userId, skuId}

	// Record call args
	mmDeleteFromCart.DeleteFromCartMock.mutex.Lock()
	mmDeleteFromCart.DeleteFromCartMock.callArgs = append(mmDeleteFromCart.DeleteFromCartMock.callArgs, &mm_params)
	mmDeleteFromCart.DeleteFromCartMock.mutex.Unlock()

	for _, e := range mmDeleteFromCart.DeleteFromCartMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDeleteFromCart.DeleteFromCartMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDeleteFromCart.DeleteFromCartMock.defaultExpectation.Counter, 1)
		mm_want := mmDeleteFromCart.DeleteFromCartMock.defaultExpectation.params
		mm_want_ptrs := mmDeleteFromCart.DeleteFromCartMock.defaultExpectation.paramPtrs

		mm_got := CartServiceMockDeleteFromCartParams{ctx, userId, skuId}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmDeleteFromCart.t.Errorf("CartServiceMock.DeleteFromCart got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteFromCart.DeleteFromCartMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userId != nil && !minimock.Equal(*mm_want_ptrs.userId, mm_got.userId) {
				mmDeleteFromCart.t.Errorf("CartServiceMock.DeleteFromCart got unexpected parameter userId, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteFromCart.DeleteFromCartMock.defaultExpectation.expectationOrigins.originUserId, *mm_want_ptrs.userId, mm_got.userId, minimock.Diff(*mm_want_ptrs.userId, mm_got.userId))
			}

			if mm_want_ptrs.skuId != nil && !minimock.Equal(*mm_want_ptrs.skuId, mm_got.skuId) {
				mmDeleteFromCart.t.Errorf("CartServiceMock.DeleteFromCart got unexpected parameter skuId, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteFromCart.DeleteFromCartMock.defaultExpectation.expectationOrigins.originSkuId, *mm_want_ptrs.skuId, mm_got.skuId, minimock.Diff(*mm_want_ptrs.skuId, mm_got.skuId))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDeleteFromCart.t.Errorf("CartServiceMock.DeleteFromCart got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDeleteFromCart.DeleteFromCartMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDeleteFromCart.DeleteFromCartMock.defaultExpectation.results
		if mm_results == nil {
			mmDeleteFromCart.t.Fatal("No results are set for the CartServiceMock.DeleteFromCart")
		}
		return (*mm_results).err
	}
	if mmDeleteFromCart.funcDeleteFromCart != nil {
		return mmDeleteFromCart.funcDeleteFromCart(ctx, userId, skuId)
	}
	mmDeleteFromCart.t.Fatalf("Unexpected call to CartServiceMock.DeleteFromCart. %v %v %v", ctx, userId, skuId)
	return
}

// DeleteFromCartAfterCounter returns a count of finished CartServiceMock.DeleteFromCart invocations
func (mmDeleteFromCart *CartServiceMock) DeleteFromCartAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteFromCart.afterDeleteFromCartCounter)
}

// DeleteFromCartBeforeCounter returns a count of CartServiceMock.DeleteFromCart invocations
func (mmDeleteFromCart *CartServiceMock) DeleteFromCartBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteFromCart.beforeDeleteFromCartCounter)
}

// Calls returns a list of arguments used in each call to CartServiceMock.DeleteFromCart.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDeleteFromCart *mCartServiceMockDeleteFromCart) Calls() []*CartServiceMockDeleteFromCartParams {
	mmDeleteFromCart.mutex.RLock()

	argCopy := make([]*CartServiceMockDeleteFromCartParams, len(mmDeleteFromCart.callArgs))
	copy(argCopy, mmDeleteFromCart.callArgs)

	mmDeleteFromCart.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteFromCartDone returns true if the count of the DeleteFromCart invocations corresponds
// the number of defined expectations
func (m *CartServiceMock) MinimockDeleteFromCartDone() bool {
	if m.DeleteFromCartMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteFromCartMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteFromCartMock.invocationsDone()
}

// MinimockDeleteFromCartInspect logs each unmet expectation
func (m *CartServiceMock) MinimockDeleteFromCartInspect() {
	for _, e := range m.DeleteFromCartMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CartServiceMock.DeleteFromCart at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteFromCartCounter := mm_atomic.LoadUint64(&m.afterDeleteFromCartCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteFromCartMock.defaultExpectation != nil && afterDeleteFromCartCounter < 1 {
		if m.DeleteFromCartMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CartServiceMock.DeleteFromCart at\n%s", m.DeleteFromCartMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CartServiceMock.DeleteFromCart at\n%s with params: %#v", m.DeleteFromCartMock.defaultExpectation.expectationOrigins.origin, *m.DeleteFromCartMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDeleteFromCart != nil && afterDeleteFromCartCounter < 1 {
		m.t.Errorf("Expected call to CartServiceMock.DeleteFromCart at\n%s", m.funcDeleteFromCartOrigin)
	}

	if !m.DeleteFromCartMock.invocationsDone() && afterDeleteFromCartCounter > 0 {
		m.t.Errorf("Expected %d calls to CartServiceMock.DeleteFromCart at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteFromCartMock.expectedInvocations), m.DeleteFromCartMock.expectedInvocationsOrigin, afterDeleteFromCartCounter)
	}
}

type mCartServiceMockGetItems struct {
	optional           bool
	mock               *CartServiceMock
	defaultExpectation *CartServiceMockGetItemsExpectation
	expectations       []*CartServiceMockGetItemsExpectation

	callArgs []*CartServiceMockGetItemsParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CartServiceMockGetItemsExpectation specifies expectation struct of the cartService.GetItems
type CartServiceMockGetItemsExpectation struct {
	mock               *CartServiceMock
	params             *CartServiceMockGetItemsParams
	paramPtrs          *CartServiceMockGetItemsParamPtrs
	expectationOrigins CartServiceMockGetItemsExpectationOrigins
	results            *CartServiceMockGetItemsResults
	returnOrigin       string
	Counter            uint64
}

// CartServiceMockGetItemsParams contains parameters of the cartService.GetItems
type CartServiceMockGetItemsParams struct {
	ctx    context.Context
	userId int64
}

// CartServiceMockGetItemsParamPtrs contains pointers to parameters of the cartService.GetItems
type CartServiceMockGetItemsParamPtrs struct {
	ctx    *context.Context
	userId *int64
}

// CartServiceMockGetItemsResults contains results of the cartService.GetItems
type CartServiceMockGetItemsResults struct {
	up1 *model.UserData
	err error
}

// CartServiceMockGetItemsOrigins contains origins of expectations of the cartService.GetItems
type CartServiceMockGetItemsExpectationOrigins struct {
	origin       string
	originCtx    string
	originUserId string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetItems *mCartServiceMockGetItems) Optional() *mCartServiceMockGetItems {
	mmGetItems.optional = true
	return mmGetItems
}

// Expect sets up expected params for cartService.GetItems
func (mmGetItems *mCartServiceMockGetItems) Expect(ctx context.Context, userId int64) *mCartServiceMockGetItems {
	if mmGetItems.mock.funcGetItems != nil {
		mmGetItems.mock.t.Fatalf("CartServiceMock.GetItems mock is already set by Set")
	}

	if mmGetItems.defaultExpectation == nil {
		mmGetItems.defaultExpectation = &CartServiceMockGetItemsExpectation{}
	}

	if mmGetItems.defaultExpectation.paramPtrs != nil {
		mmGetItems.mock.t.Fatalf("CartServiceMock.GetItems mock is already set by ExpectParams functions")
	}

	mmGetItems.defaultExpectation.params = &CartServiceMockGetItemsParams{ctx, userId}
	mmGetItems.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetItems.expectations {
		if minimock.Equal(e.params, mmGetItems.defaultExpectation.params) {
			mmGetItems.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetItems.defaultExpectation.params)
		}
	}

	return mmGetItems
}

// ExpectCtxParam1 sets up expected param ctx for cartService.GetItems
func (mmGetItems *mCartServiceMockGetItems) ExpectCtxParam1(ctx context.Context) *mCartServiceMockGetItems {
	if mmGetItems.mock.funcGetItems != nil {
		mmGetItems.mock.t.Fatalf("CartServiceMock.GetItems mock is already set by Set")
	}

	if mmGetItems.defaultExpectation == nil {
		mmGetItems.defaultExpectation = &CartServiceMockGetItemsExpectation{}
	}

	if mmGetItems.defaultExpectation.params != nil {
		mmGetItems.mock.t.Fatalf("CartServiceMock.GetItems mock is already set by Expect")
	}

	if mmGetItems.defaultExpectation.paramPtrs == nil {
		mmGetItems.defaultExpectation.paramPtrs = &CartServiceMockGetItemsParamPtrs{}
	}
	mmGetItems.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetItems.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetItems
}

// ExpectUserIdParam2 sets up expected param userId for cartService.GetItems
func (mmGetItems *mCartServiceMockGetItems) ExpectUserIdParam2(userId int64) *mCartServiceMockGetItems {
	if mmGetItems.mock.funcGetItems != nil {
		mmGetItems.mock.t.Fatalf("CartServiceMock.GetItems mock is already set by Set")
	}

	if mmGetItems.defaultExpectation == nil {
		mmGetItems.defaultExpectation = &CartServiceMockGetItemsExpectation{}
	}

	if mmGetItems.defaultExpectation.params != nil {
		mmGetItems.mock.t.Fatalf("CartServiceMock.GetItems mock is already set by Expect")
	}

	if mmGetItems.defaultExpectation.paramPtrs == nil {
		mmGetItems.defaultExpectation.paramPtrs = &CartServiceMockGetItemsParamPtrs{}
	}
	mmGetItems.defaultExpectation.paramPtrs.userId = &userId
	mmGetItems.defaultExpectation.expectationOrigins.originUserId = minimock.CallerInfo(1)

	return mmGetItems
}

// Inspect accepts an inspector function that has same arguments as the cartService.GetItems
func (mmGetItems *mCartServiceMockGetItems) Inspect(f func(ctx context.Context, userId int64)) *mCartServiceMockGetItems {
	if mmGetItems.mock.inspectFuncGetItems != nil {
		mmGetItems.mock.t.Fatalf("Inspect function is already set for CartServiceMock.GetItems")
	}

	mmGetItems.mock.inspectFuncGetItems = f

	return mmGetItems
}

// Return sets up results that will be returned by cartService.GetItems
func (mmGetItems *mCartServiceMockGetItems) Return(up1 *model.UserData, err error) *CartServiceMock {
	if mmGetItems.mock.funcGetItems != nil {
		mmGetItems.mock.t.Fatalf("CartServiceMock.GetItems mock is already set by Set")
	}

	if mmGetItems.defaultExpectation == nil {
		mmGetItems.defaultExpectation = &CartServiceMockGetItemsExpectation{mock: mmGetItems.mock}
	}
	mmGetItems.defaultExpectation.results = &CartServiceMockGetItemsResults{up1, err}
	mmGetItems.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetItems.mock
}

// Set uses given function f to mock the cartService.GetItems method
func (mmGetItems *mCartServiceMockGetItems) Set(f func(ctx context.Context, userId int64) (up1 *model.UserData, err error)) *CartServiceMock {
	if mmGetItems.defaultExpectation != nil {
		mmGetItems.mock.t.Fatalf("Default expectation is already set for the cartService.GetItems method")
	}

	if len(mmGetItems.expectations) > 0 {
		mmGetItems.mock.t.Fatalf("Some expectations are already set for the cartService.GetItems method")
	}

	mmGetItems.mock.funcGetItems = f
	mmGetItems.mock.funcGetItemsOrigin = minimock.CallerInfo(1)
	return mmGetItems.mock
}

// When sets expectation for the cartService.GetItems which will trigger the result defined by the following
// Then helper
func (mmGetItems *mCartServiceMockGetItems) When(ctx context.Context, userId int64) *CartServiceMockGetItemsExpectation {
	if mmGetItems.mock.funcGetItems != nil {
		mmGetItems.mock.t.Fatalf("CartServiceMock.GetItems mock is already set by Set")
	}

	expectation := &CartServiceMockGetItemsExpectation{
		mock:               mmGetItems.mock,
		params:             &CartServiceMockGetItemsParams{ctx, userId},
		expectationOrigins: CartServiceMockGetItemsExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetItems.expectations = append(mmGetItems.expectations, expectation)
	return expectation
}

// Then sets up cartService.GetItems return parameters for the expectation previously defined by the When method
func (e *CartServiceMockGetItemsExpectation) Then(up1 *model.UserData, err error) *CartServiceMock {
	e.results = &CartServiceMockGetItemsResults{up1, err}
	return e.mock
}

// Times sets number of times cartService.GetItems should be invoked
func (mmGetItems *mCartServiceMockGetItems) Times(n uint64) *mCartServiceMockGetItems {
	if n == 0 {
		mmGetItems.mock.t.Fatalf("Times of CartServiceMock.GetItems mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetItems.expectedInvocations, n)
	mmGetItems.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetItems
}

func (mmGetItems *mCartServiceMockGetItems) invocationsDone() bool {
	if len(mmGetItems.expectations) == 0 && mmGetItems.defaultExpectation == nil && mmGetItems.mock.funcGetItems == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetItems.mock.afterGetItemsCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetItems.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetItems implements mm_handler.cartService
func (mmGetItems *CartServiceMock) GetItems(ctx context.Context, userId int64) (up1 *model.UserData, err error) {
	mm_atomic.AddUint64(&mmGetItems.beforeGetItemsCounter, 1)
	defer mm_atomic.AddUint64(&mmGetItems.afterGetItemsCounter, 1)

	mmGetItems.t.Helper()

	if mmGetItems.inspectFuncGetItems != nil {
		mmGetItems.inspectFuncGetItems(ctx, userId)
	}

	mm_params := CartServiceMockGetItemsParams{ctx, userId}

	// Record call args
	mmGetItems.GetItemsMock.mutex.Lock()
	mmGetItems.GetItemsMock.callArgs = append(mmGetItems.GetItemsMock.callArgs, &mm_params)
	mmGetItems.GetItemsMock.mutex.Unlock()

	for _, e := range mmGetItems.GetItemsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.up1, e.results.err
		}
	}

	if mmGetItems.GetItemsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetItems.GetItemsMock.defaultExpectation.Counter, 1)
		mm_want := mmGetItems.GetItemsMock.defaultExpectation.params
		mm_want_ptrs := mmGetItems.GetItemsMock.defaultExpectation.paramPtrs

		mm_got := CartServiceMockGetItemsParams{ctx, userId}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetItems.t.Errorf("CartServiceMock.GetItems got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetItems.GetItemsMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userId != nil && !minimock.Equal(*mm_want_ptrs.userId, mm_got.userId) {
				mmGetItems.t.Errorf("CartServiceMock.GetItems got unexpected parameter userId, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetItems.GetItemsMock.defaultExpectation.expectationOrigins.originUserId, *mm_want_ptrs.userId, mm_got.userId, minimock.Diff(*mm_want_ptrs.userId, mm_got.userId))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetItems.t.Errorf("CartServiceMock.GetItems got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetItems.GetItemsMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetItems.GetItemsMock.defaultExpectation.results
		if mm_results == nil {
			mmGetItems.t.Fatal("No results are set for the CartServiceMock.GetItems")
		}
		return (*mm_results).up1, (*mm_results).err
	}
	if mmGetItems.funcGetItems != nil {
		return mmGetItems.funcGetItems(ctx, userId)
	}
	mmGetItems.t.Fatalf("Unexpected call to CartServiceMock.GetItems. %v %v", ctx, userId)
	return
}

// GetItemsAfterCounter returns a count of finished CartServiceMock.GetItems invocations
func (mmGetItems *CartServiceMock) GetItemsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetItems.afterGetItemsCounter)
}

// GetItemsBeforeCounter returns a count of CartServiceMock.GetItems invocations
func (mmGetItems *CartServiceMock) GetItemsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetItems.beforeGetItemsCounter)
}

// Calls returns a list of arguments used in each call to CartServiceMock.GetItems.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetItems *mCartServiceMockGetItems) Calls() []*CartServiceMockGetItemsParams {
	mmGetItems.mutex.RLock()

	argCopy := make([]*CartServiceMockGetItemsParams, len(mmGetItems.callArgs))
	copy(argCopy, mmGetItems.callArgs)

	mmGetItems.mutex.RUnlock()

	return argCopy
}

// MinimockGetItemsDone returns true if the count of the GetItems invocations corresponds
// the number of defined expectations
func (m *CartServiceMock) MinimockGetItemsDone() bool {
	if m.GetItemsMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetItemsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetItemsMock.invocationsDone()
}

// MinimockGetItemsInspect logs each unmet expectation
func (m *CartServiceMock) MinimockGetItemsInspect() {
	for _, e := range m.GetItemsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CartServiceMock.GetItems at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetItemsCounter := mm_atomic.LoadUint64(&m.afterGetItemsCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetItemsMock.defaultExpectation != nil && afterGetItemsCounter < 1 {
		if m.GetItemsMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CartServiceMock.GetItems at\n%s", m.GetItemsMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CartServiceMock.GetItems at\n%s with params: %#v", m.GetItemsMock.defaultExpectation.expectationOrigins.origin, *m.GetItemsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetItems != nil && afterGetItemsCounter < 1 {
		m.t.Errorf("Expected call to CartServiceMock.GetItems at\n%s", m.funcGetItemsOrigin)
	}

	if !m.GetItemsMock.invocationsDone() && afterGetItemsCounter > 0 {
		m.t.Errorf("Expected %d calls to CartServiceMock.GetItems at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetItemsMock.expectedInvocations), m.GetItemsMock.expectedInvocationsOrigin, afterGetItemsCounter)
	}
}

type mCartServiceMockPayOrder struct {
	optional           bool
	mock               *CartServiceMock
	defaultExpectation *CartServiceMockPayOrderExpectation
	expectations       []*CartServiceMockPayOrderExpectation

	callArgs []*CartServiceMockPayOrderParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CartServiceMockPayOrderExpectation specifies expectation struct of the cartService.PayOrder
type CartServiceMockPayOrderExpectation struct {
	mock               *CartServiceMock
	params             *CartServiceMockPayOrderParams
	paramPtrs          *CartServiceMockPayOrderParamPtrs
	expectationOrigins CartServiceMockPayOrderExpectationOrigins
	results            *CartServiceMockPayOrderResults
	returnOrigin       string
	Counter            uint64
}

// CartServiceMockPayOrderParams contains parameters of the cartService.PayOrder
type CartServiceMockPayOrderParams struct {
	ctx     context.Context
	orderId int64
}

// CartServiceMockPayOrderParamPtrs contains pointers to parameters of the cartService.PayOrder
type CartServiceMockPayOrderParamPtrs struct {
	ctx     *context.Context
	orderId *int64
}

// CartServiceMockPayOrderResults contains results of the cartService.PayOrder
type CartServiceMockPayOrderResults struct {
	err error
}

// CartServiceMockPayOrderOrigins contains origins of expectations of the cartService.PayOrder
type CartServiceMockPayOrderExpectationOrigins struct {
	origin        string
	originCtx     string
	originOrderId string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmPayOrder *mCartServiceMockPayOrder) Optional() *mCartServiceMockPayOrder {
	mmPayOrder.optional = true
	return mmPayOrder
}

// Expect sets up expected params for cartService.PayOrder
func (mmPayOrder *mCartServiceMockPayOrder) Expect(ctx context.Context, orderId int64) *mCartServiceMockPayOrder {
	if mmPayOrder.mock.funcPayOrder != nil {
		mmPayOrder.mock.t.Fatalf("CartServiceMock.PayOrder mock is already set by Set")
	}

	if mmPayOrder.defaultExpectation == nil {
		mmPayOrder.defaultExpectation = &CartServiceMockPayOrderExpectation{}
	}

	if mmPayOrder.defaultExpectation.paramPtrs != nil {
		mmPayOrder.mock.t.Fatalf("CartServiceMock.PayOrder mock is already set by ExpectParams functions")
	}

	mmPayOrder.defaultExpectation.params = &CartServiceMockPayOrderParams{ctx, orderId}
	mmPayOrder.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmPayOrder.expectations {
		if minimock.Equal(e.params, mmPayOrder.defaultExpectation.params) {
			mmPayOrder.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmPayOrder.defaultExpectation.params)
		}
	}

	return mmPayOrder
}

// ExpectCtxParam1 sets up expected param ctx for cartService.PayOrder
func (mmPayOrder *mCartServiceMockPayOrder) ExpectCtxParam1(ctx context.Context) *mCartServiceMockPayOrder {
	if mmPayOrder.mock.funcPayOrder != nil {
		mmPayOrder.mock.t.Fatalf("CartServiceMock.PayOrder mock is already set by Set")
	}

	if mmPayOrder.defaultExpectation == nil {
		mmPayOrder.defaultExpectation = &CartServiceMockPayOrderExpectation{}
	}

	if mmPayOrder.defaultExpectation.params != nil {
		mmPayOrder.mock.t.Fatalf("CartServiceMock.PayOrder mock is already set by Expect")
	}

	if mmPayOrder.defaultExpectation.paramPtrs == nil {
		mmPayOrder.defaultExpectation.paramPtrs = &CartServiceMockPayOrderParamPtrs{}
	}
	mmPayOrder.defaultExpectation.paramPtrs.ctx = &ctx
	mmPayOrder.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmPayOrder
}

// ExpectOrderIdParam2 sets up expected param orderId for cartService.PayOrder
func (mmPayOrder *mCartServiceMockPayOrder) ExpectOrderIdParam2(orderId int64) *mCartServiceMockPayOrder {
	if mmPayOrder.mock.funcPayOrder != nil {
		mmPayOrder.mock.t.Fatalf("CartServiceMock.PayOrder mock is already set by Set")
	}

	if mmPayOrder.defaultExpectation == nil {
		mmPayOrder.defaultExpectation = &CartServiceMockPayOrderExpectation{}
	}

	if mmPayOrder.defaultExpectation.params != nil {
		mmPayOrder.mock.t.Fatalf("CartServiceMock.PayOrder mock is already set by Expect")
	}

	if mmPayOrder.defaultExpectation.paramPtrs == nil {
		mmPayOrder.defaultExpectation.paramPtrs = &CartServiceMockPayOrderParamPtrs{}
	}
	mmPayOrder.defaultExpectation.paramPtrs.orderId = &orderId
	mmPayOrder.defaultExpectation.expectationOrigins.originOrderId = minimock.CallerInfo(1)

	return mmPayOrder
}

// Inspect accepts an inspector function that has same arguments as the cartService.PayOrder
func (mmPayOrder *mCartServiceMockPayOrder) Inspect(f func(ctx context.Context, orderId int64)) *mCartServiceMockPayOrder {
	if mmPayOrder.mock.inspectFuncPayOrder != nil {
		mmPayOrder.mock.t.Fatalf("Inspect function is already set for CartServiceMock.PayOrder")
	}

	mmPayOrder.mock.inspectFuncPayOrder = f

	return mmPayOrder
}

// Return sets up results that will be returned by cartService.PayOrder
func (mmPayOrder *mCartServiceMockPayOrder) Return(err error) *CartServiceMock {
	if mmPayOrder.mock.funcPayOrder != nil {
		mmPayOrder.mock.t.Fatalf("CartServiceMock.PayOrder mock is already set by Set")
	}

	if mmPayOrder.defaultExpectation == nil {
		mmPayOrder.defaultExpectation = &CartServiceMockPayOrderExpectation{mock: mmPayOrder.mock}
	}
	mmPayOrder.defaultExpectation.results = &CartServiceMockPayOrderResults{err}
	mmPayOrder.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmPayOrder.mock
}

// Set uses given function f to mock the cartService.PayOrder method
func (mmPayOrder *mCartServiceMockPayOrder) Set(f func(ctx context.Context, orderId int64) (err error)) *CartServiceMock {
	if mmPayOrder.defaultExpectation != nil {
		mmPayOrder.mock.t.Fatalf("Default expectation is already set for the cartService.PayOrder method")
	}

	if len(mmPayOrder.expectations) > 0 {
		mmPayOrder.mock.t.Fatalf("Some expectations are already set for the cartService.PayOrder method")
	}

	mmPayOrder.mock.funcPayOrder = f
	mmPayOrder.mock.funcPayOrderOrigin = minimock.CallerInfo(1)
	return mmPayOrder.mock
}

// When sets expectation for the cartService.PayOrder which will trigger the result defined by the following
// Then helper
func (mmPayOrder *mCartServiceMockPayOrder) When(ctx context.Context, orderId int64) *CartServiceMockPayOrderExpectation {
	if mmPayOrder.mock.funcPayOrder != nil {
		mmPayOrder.mock.t.Fatalf("CartServiceMock.PayOrder mock is already set by Set")
	}

	expectation := &CartServiceMockPayOrderExpectation{
		mock:               mmPayOrder.mock,
		params:             &CartServiceMockPayOrderParams{ctx, orderId},
		expectationOrigins: CartServiceMockPayOrderExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmPayOrder.expectations = append(mmPayOrder.expectations, expectation)
	return expectation
}

// Then sets up cartService.PayOrder return parameters for the expectation previously defined by the When method
func (e *CartServiceMockPayOrderExpectation) Then(err error) *CartServiceMock {
	e.results = &CartServiceMockPayOrderResults{err}
	return e.mock
}

// Times sets number of times cartService.PayOrder should be invoked
func (mmPayOrder *mCartServiceMockPayOrder) Times(n uint64) *mCartServiceMockPayOrder {
	if n == 0 {
		mmPayOrder.mock.t.Fatalf("Times of CartServiceMock.PayOrder mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmPayOrder.expectedInvocations, n)
	mmPayOrder.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmPayOrder
}

func (mmPayOrder *mCartServiceMockPayOrder) invocationsDone() bool {
	if len(mmPayOrder.expectations) == 0 && mmPayOrder.defaultExpectation == nil && mmPayOrder.mock.funcPayOrder == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmPayOrder.mock.afterPayOrderCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmPayOrder.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// PayOrder implements mm_handler.cartService
func (mmPayOrder *CartServiceMock) PayOrder(ctx context.Context, orderId int64) (err error) {
	mm_atomic.AddUint64(&mmPayOrder.beforePayOrderCounter, 1)
	defer mm_atomic.AddUint64(&mmPayOrder.afterPayOrderCounter, 1)

	mmPayOrder.t.Helper()

	if mmPayOrder.inspectFuncPayOrder != nil {
		mmPayOrder.inspectFuncPayOrder(ctx, orderId)
	}

	mm_params := CartServiceMockPayOrderParams{ctx, orderId}

	// Record call args
	mmPayOrder.PayOrderMock.mutex.Lock()
	mmPayOrder.PayOrderMock.callArgs = append(mmPayOrder.PayOrderMock.callArgs, &mm_params)
	mmPayOrder.PayOrderMock.mutex.Unlock()

	for _, e := range mmPayOrder.PayOrderMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmPayOrder.PayOrderMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmPayOrder.PayOrderMock.defaultExpectation.Counter, 1)
		mm_want := mmPayOrder.PayOrderMock.defaultExpectation.params
		mm_want_ptrs := mmPayOrder.PayOrderMock.defaultExpectation.paramPtrs

		mm_got := CartServiceMockPayOrderParams{ctx, orderId}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmPayOrder.t.Errorf("CartServiceMock.PayOrder got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmPayOrder.PayOrderMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.orderId != nil && !minimock.Equal(*mm_want_ptrs.orderId, mm_got.orderId) {
				mmPayOrder.t.Errorf("CartServiceMock.PayOrder got unexpected parameter orderId, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmPayOrder.PayOrderMock.defaultExpectation.expectationOrigins.originOrderId, *mm_want_ptrs.orderId, mm_got.orderId, minimock.Diff(*mm_want_ptrs.orderId, mm_got.orderId))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmPayOrder.t.Errorf("CartServiceMock.PayOrder got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmPayOrder.PayOrderMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmPayOrder.PayOrderMock.defaultExpectation.results
		if mm_results == nil {
			mmPayOrder.t.Fatal("No results are set for the CartServiceMock.PayOrder")
		}
		return (*mm_results).err
	}
	if mmPayOrder.funcPayOrder != nil {
		return mmPayOrder.funcPayOrder(ctx, orderId)
	}
	mmPayOrder.t.Fatalf("Unexpected call to CartServiceMock.PayOrder. %v %v", ctx, orderId)
	return
}

// PayOrderAfterCounter returns a count of finished CartServiceMock.PayOrder invocations
func (mmPayOrder *CartServiceMock) PayOrderAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPayOrder.afterPayOrderCounter)
}

// PayOrderBeforeCounter returns a count of CartServiceMock.PayOrder invocations
func (mmPayOrder *CartServiceMock) PayOrderBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPayOrder.beforePayOrderCounter)
}

// Calls returns a list of arguments used in each call to CartServiceMock.PayOrder.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmPayOrder *mCartServiceMockPayOrder) Calls() []*CartServiceMockPayOrderParams {
	mmPayOrder.mutex.RLock()

	argCopy := make([]*CartServiceMockPayOrderParams, len(mmPayOrder.callArgs))
	copy(argCopy, mmPayOrder.callArgs)

	mmPayOrder.mutex.RUnlock()

	return argCopy
}

// MinimockPayOrderDone returns true if the count of the PayOrder invocations corresponds
// the number of defined expectations
func (m *CartServiceMock) MinimockPayOrderDone() bool {
	if m.PayOrderMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.PayOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.PayOrderMock.invocationsDone()
}

// MinimockPayOrderInspect logs each unmet expectation
func (m *CartServiceMock) MinimockPayOrderInspect() {
	for _, e := range m.PayOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CartServiceMock.PayOrder at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterPayOrderCounter := mm_atomic.LoadUint64(&m.afterPayOrderCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.PayOrderMock.defaultExpectation != nil && afterPayOrderCounter < 1 {
		if m.PayOrderMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CartServiceMock.PayOrder at\n%s", m.PayOrderMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CartServiceMock.PayOrder at\n%s with params: %#v", m.PayOrderMock.defaultExpectation.expectationOrigins.origin, *m.PayOrderMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcPayOrder != nil && afterPayOrderCounter < 1 {
		m.t.Errorf("Expected call to CartServiceMock.PayOrder at\n%s", m.funcPayOrderOrigin)
	}

	if !m.PayOrderMock.invocationsDone() && afterPayOrderCounter > 0 {
		m.t.Errorf("Expected %d calls to CartServiceMock.PayOrder at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.PayOrderMock.expectedInvocations), m.PayOrderMock.expectedInvocationsOrigin, afterPayOrderCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *CartServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockAddItemToCartInspect()

			m.MinimockCancelOrderInspect()

			m.MinimockCheckoutInspect()

			m.MinimockDeleteFromCartInspect()

			m.MinimockGetItemsInspect()

			m.MinimockPayOrderInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *CartServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *CartServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockAddItemToCartDone() &&
		m.MinimockCancelOrderDone() &&
		m.MinimockCheckoutDone() &&
		m.MinimockDeleteFromCartDone() &&
		m.MinimockGetItemsDone() &&
		m.MinimockPayOrderDone()
}
