// Code generated by http://github.com/gojuno/minimock (v3.4.0). DO NOT EDIT.

package mocks

//go:generate minimock -i route256/cart/internal/handler.cartService -o cart_service_mock.go -n CartServiceMock -p mocks

import (
	"route256/cart/internal/model"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// CartServiceMock implements mm_handler.cartService
type CartServiceMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcAddItemToCart          func(userId int64, item *model.Item) (err error)
	funcAddItemToCartOrigin    string
	inspectFuncAddItemToCart   func(userId int64, item *model.Item)
	afterAddItemToCartCounter  uint64
	beforeAddItemToCartCounter uint64
	AddItemToCartMock          mCartServiceMockAddItemToCart

	funcDeleteAllFromCart          func(userId int64) (err error)
	funcDeleteAllFromCartOrigin    string
	inspectFuncDeleteAllFromCart   func(userId int64)
	afterDeleteAllFromCartCounter  uint64
	beforeDeleteAllFromCartCounter uint64
	DeleteAllFromCartMock          mCartServiceMockDeleteAllFromCart

	funcDeleteFromCart          func(userId int64, skuId int64) (err error)
	funcDeleteFromCartOrigin    string
	inspectFuncDeleteFromCart   func(userId int64, skuId int64)
	afterDeleteFromCartCounter  uint64
	beforeDeleteFromCartCounter uint64
	DeleteFromCartMock          mCartServiceMockDeleteFromCart

	funcGetItems          func(userId int64) (up1 *model.UserData, err error)
	funcGetItemsOrigin    string
	inspectFuncGetItems   func(userId int64)
	afterGetItemsCounter  uint64
	beforeGetItemsCounter uint64
	GetItemsMock          mCartServiceMockGetItems

	funcGetProduct          func(productId int64) (pp1 *model.Product, err error)
	funcGetProductOrigin    string
	inspectFuncGetProduct   func(productId int64)
	afterGetProductCounter  uint64
	beforeGetProductCounter uint64
	GetProductMock          mCartServiceMockGetProduct
}

// NewCartServiceMock returns a mock for mm_handler.cartService
func NewCartServiceMock(t minimock.Tester) *CartServiceMock {
	m := &CartServiceMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.AddItemToCartMock = mCartServiceMockAddItemToCart{mock: m}
	m.AddItemToCartMock.callArgs = []*CartServiceMockAddItemToCartParams{}

	m.DeleteAllFromCartMock = mCartServiceMockDeleteAllFromCart{mock: m}
	m.DeleteAllFromCartMock.callArgs = []*CartServiceMockDeleteAllFromCartParams{}

	m.DeleteFromCartMock = mCartServiceMockDeleteFromCart{mock: m}
	m.DeleteFromCartMock.callArgs = []*CartServiceMockDeleteFromCartParams{}

	m.GetItemsMock = mCartServiceMockGetItems{mock: m}
	m.GetItemsMock.callArgs = []*CartServiceMockGetItemsParams{}

	m.GetProductMock = mCartServiceMockGetProduct{mock: m}
	m.GetProductMock.callArgs = []*CartServiceMockGetProductParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mCartServiceMockAddItemToCart struct {
	optional           bool
	mock               *CartServiceMock
	defaultExpectation *CartServiceMockAddItemToCartExpectation
	expectations       []*CartServiceMockAddItemToCartExpectation

	callArgs []*CartServiceMockAddItemToCartParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CartServiceMockAddItemToCartExpectation specifies expectation struct of the cartService.AddItemToCart
type CartServiceMockAddItemToCartExpectation struct {
	mock               *CartServiceMock
	params             *CartServiceMockAddItemToCartParams
	paramPtrs          *CartServiceMockAddItemToCartParamPtrs
	expectationOrigins CartServiceMockAddItemToCartExpectationOrigins
	results            *CartServiceMockAddItemToCartResults
	returnOrigin       string
	Counter            uint64
}

// CartServiceMockAddItemToCartParams contains parameters of the cartService.AddItemToCart
type CartServiceMockAddItemToCartParams struct {
	userId int64
	item   *model.Item
}

// CartServiceMockAddItemToCartParamPtrs contains pointers to parameters of the cartService.AddItemToCart
type CartServiceMockAddItemToCartParamPtrs struct {
	userId *int64
	item   **model.Item
}

// CartServiceMockAddItemToCartResults contains results of the cartService.AddItemToCart
type CartServiceMockAddItemToCartResults struct {
	err error
}

// CartServiceMockAddItemToCartOrigins contains origins of expectations of the cartService.AddItemToCart
type CartServiceMockAddItemToCartExpectationOrigins struct {
	origin       string
	originUserId string
	originItem   string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmAddItemToCart *mCartServiceMockAddItemToCart) Optional() *mCartServiceMockAddItemToCart {
	mmAddItemToCart.optional = true
	return mmAddItemToCart
}

// Expect sets up expected params for cartService.AddItemToCart
func (mmAddItemToCart *mCartServiceMockAddItemToCart) Expect(userId int64, item *model.Item) *mCartServiceMockAddItemToCart {
	if mmAddItemToCart.mock.funcAddItemToCart != nil {
		mmAddItemToCart.mock.t.Fatalf("CartServiceMock.AddItemToCart mock is already set by Set")
	}

	if mmAddItemToCart.defaultExpectation == nil {
		mmAddItemToCart.defaultExpectation = &CartServiceMockAddItemToCartExpectation{}
	}

	if mmAddItemToCart.defaultExpectation.paramPtrs != nil {
		mmAddItemToCart.mock.t.Fatalf("CartServiceMock.AddItemToCart mock is already set by ExpectParams functions")
	}

	mmAddItemToCart.defaultExpectation.params = &CartServiceMockAddItemToCartParams{userId, item}
	mmAddItemToCart.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmAddItemToCart.expectations {
		if minimock.Equal(e.params, mmAddItemToCart.defaultExpectation.params) {
			mmAddItemToCart.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmAddItemToCart.defaultExpectation.params)
		}
	}

	return mmAddItemToCart
}

// ExpectUserIdParam1 sets up expected param userId for cartService.AddItemToCart
func (mmAddItemToCart *mCartServiceMockAddItemToCart) ExpectUserIdParam1(userId int64) *mCartServiceMockAddItemToCart {
	if mmAddItemToCart.mock.funcAddItemToCart != nil {
		mmAddItemToCart.mock.t.Fatalf("CartServiceMock.AddItemToCart mock is already set by Set")
	}

	if mmAddItemToCart.defaultExpectation == nil {
		mmAddItemToCart.defaultExpectation = &CartServiceMockAddItemToCartExpectation{}
	}

	if mmAddItemToCart.defaultExpectation.params != nil {
		mmAddItemToCart.mock.t.Fatalf("CartServiceMock.AddItemToCart mock is already set by Expect")
	}

	if mmAddItemToCart.defaultExpectation.paramPtrs == nil {
		mmAddItemToCart.defaultExpectation.paramPtrs = &CartServiceMockAddItemToCartParamPtrs{}
	}
	mmAddItemToCart.defaultExpectation.paramPtrs.userId = &userId
	mmAddItemToCart.defaultExpectation.expectationOrigins.originUserId = minimock.CallerInfo(1)

	return mmAddItemToCart
}

// ExpectItemParam2 sets up expected param item for cartService.AddItemToCart
func (mmAddItemToCart *mCartServiceMockAddItemToCart) ExpectItemParam2(item *model.Item) *mCartServiceMockAddItemToCart {
	if mmAddItemToCart.mock.funcAddItemToCart != nil {
		mmAddItemToCart.mock.t.Fatalf("CartServiceMock.AddItemToCart mock is already set by Set")
	}

	if mmAddItemToCart.defaultExpectation == nil {
		mmAddItemToCart.defaultExpectation = &CartServiceMockAddItemToCartExpectation{}
	}

	if mmAddItemToCart.defaultExpectation.params != nil {
		mmAddItemToCart.mock.t.Fatalf("CartServiceMock.AddItemToCart mock is already set by Expect")
	}

	if mmAddItemToCart.defaultExpectation.paramPtrs == nil {
		mmAddItemToCart.defaultExpectation.paramPtrs = &CartServiceMockAddItemToCartParamPtrs{}
	}
	mmAddItemToCart.defaultExpectation.paramPtrs.item = &item
	mmAddItemToCart.defaultExpectation.expectationOrigins.originItem = minimock.CallerInfo(1)

	return mmAddItemToCart
}

// Inspect accepts an inspector function that has same arguments as the cartService.AddItemToCart
func (mmAddItemToCart *mCartServiceMockAddItemToCart) Inspect(f func(userId int64, item *model.Item)) *mCartServiceMockAddItemToCart {
	if mmAddItemToCart.mock.inspectFuncAddItemToCart != nil {
		mmAddItemToCart.mock.t.Fatalf("Inspect function is already set for CartServiceMock.AddItemToCart")
	}

	mmAddItemToCart.mock.inspectFuncAddItemToCart = f

	return mmAddItemToCart
}

// Return sets up results that will be returned by cartService.AddItemToCart
func (mmAddItemToCart *mCartServiceMockAddItemToCart) Return(err error) *CartServiceMock {
	if mmAddItemToCart.mock.funcAddItemToCart != nil {
		mmAddItemToCart.mock.t.Fatalf("CartServiceMock.AddItemToCart mock is already set by Set")
	}

	if mmAddItemToCart.defaultExpectation == nil {
		mmAddItemToCart.defaultExpectation = &CartServiceMockAddItemToCartExpectation{mock: mmAddItemToCart.mock}
	}
	mmAddItemToCart.defaultExpectation.results = &CartServiceMockAddItemToCartResults{err}
	mmAddItemToCart.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmAddItemToCart.mock
}

// Set uses given function f to mock the cartService.AddItemToCart method
func (mmAddItemToCart *mCartServiceMockAddItemToCart) Set(f func(userId int64, item *model.Item) (err error)) *CartServiceMock {
	if mmAddItemToCart.defaultExpectation != nil {
		mmAddItemToCart.mock.t.Fatalf("Default expectation is already set for the cartService.AddItemToCart method")
	}

	if len(mmAddItemToCart.expectations) > 0 {
		mmAddItemToCart.mock.t.Fatalf("Some expectations are already set for the cartService.AddItemToCart method")
	}

	mmAddItemToCart.mock.funcAddItemToCart = f
	mmAddItemToCart.mock.funcAddItemToCartOrigin = minimock.CallerInfo(1)
	return mmAddItemToCart.mock
}

// When sets expectation for the cartService.AddItemToCart which will trigger the result defined by the following
// Then helper
func (mmAddItemToCart *mCartServiceMockAddItemToCart) When(userId int64, item *model.Item) *CartServiceMockAddItemToCartExpectation {
	if mmAddItemToCart.mock.funcAddItemToCart != nil {
		mmAddItemToCart.mock.t.Fatalf("CartServiceMock.AddItemToCart mock is already set by Set")
	}

	expectation := &CartServiceMockAddItemToCartExpectation{
		mock:               mmAddItemToCart.mock,
		params:             &CartServiceMockAddItemToCartParams{userId, item},
		expectationOrigins: CartServiceMockAddItemToCartExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmAddItemToCart.expectations = append(mmAddItemToCart.expectations, expectation)
	return expectation
}

// Then sets up cartService.AddItemToCart return parameters for the expectation previously defined by the When method
func (e *CartServiceMockAddItemToCartExpectation) Then(err error) *CartServiceMock {
	e.results = &CartServiceMockAddItemToCartResults{err}
	return e.mock
}

// Times sets number of times cartService.AddItemToCart should be invoked
func (mmAddItemToCart *mCartServiceMockAddItemToCart) Times(n uint64) *mCartServiceMockAddItemToCart {
	if n == 0 {
		mmAddItemToCart.mock.t.Fatalf("Times of CartServiceMock.AddItemToCart mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmAddItemToCart.expectedInvocations, n)
	mmAddItemToCart.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmAddItemToCart
}

func (mmAddItemToCart *mCartServiceMockAddItemToCart) invocationsDone() bool {
	if len(mmAddItemToCart.expectations) == 0 && mmAddItemToCart.defaultExpectation == nil && mmAddItemToCart.mock.funcAddItemToCart == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmAddItemToCart.mock.afterAddItemToCartCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmAddItemToCart.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// AddItemToCart implements mm_handler.cartService
func (mmAddItemToCart *CartServiceMock) AddItemToCart(userId int64, item *model.Item) (err error) {
	mm_atomic.AddUint64(&mmAddItemToCart.beforeAddItemToCartCounter, 1)
	defer mm_atomic.AddUint64(&mmAddItemToCart.afterAddItemToCartCounter, 1)

	mmAddItemToCart.t.Helper()

	if mmAddItemToCart.inspectFuncAddItemToCart != nil {
		mmAddItemToCart.inspectFuncAddItemToCart(userId, item)
	}

	mm_params := CartServiceMockAddItemToCartParams{userId, item}

	// Record call args
	mmAddItemToCart.AddItemToCartMock.mutex.Lock()
	mmAddItemToCart.AddItemToCartMock.callArgs = append(mmAddItemToCart.AddItemToCartMock.callArgs, &mm_params)
	mmAddItemToCart.AddItemToCartMock.mutex.Unlock()

	for _, e := range mmAddItemToCart.AddItemToCartMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmAddItemToCart.AddItemToCartMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmAddItemToCart.AddItemToCartMock.defaultExpectation.Counter, 1)
		mm_want := mmAddItemToCart.AddItemToCartMock.defaultExpectation.params
		mm_want_ptrs := mmAddItemToCart.AddItemToCartMock.defaultExpectation.paramPtrs

		mm_got := CartServiceMockAddItemToCartParams{userId, item}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.userId != nil && !minimock.Equal(*mm_want_ptrs.userId, mm_got.userId) {
				mmAddItemToCart.t.Errorf("CartServiceMock.AddItemToCart got unexpected parameter userId, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAddItemToCart.AddItemToCartMock.defaultExpectation.expectationOrigins.originUserId, *mm_want_ptrs.userId, mm_got.userId, minimock.Diff(*mm_want_ptrs.userId, mm_got.userId))
			}

			if mm_want_ptrs.item != nil && !minimock.Equal(*mm_want_ptrs.item, mm_got.item) {
				mmAddItemToCart.t.Errorf("CartServiceMock.AddItemToCart got unexpected parameter item, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAddItemToCart.AddItemToCartMock.defaultExpectation.expectationOrigins.originItem, *mm_want_ptrs.item, mm_got.item, minimock.Diff(*mm_want_ptrs.item, mm_got.item))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmAddItemToCart.t.Errorf("CartServiceMock.AddItemToCart got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmAddItemToCart.AddItemToCartMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmAddItemToCart.AddItemToCartMock.defaultExpectation.results
		if mm_results == nil {
			mmAddItemToCart.t.Fatal("No results are set for the CartServiceMock.AddItemToCart")
		}
		return (*mm_results).err
	}
	if mmAddItemToCart.funcAddItemToCart != nil {
		return mmAddItemToCart.funcAddItemToCart(userId, item)
	}
	mmAddItemToCart.t.Fatalf("Unexpected call to CartServiceMock.AddItemToCart. %v %v", userId, item)
	return
}

// AddItemToCartAfterCounter returns a count of finished CartServiceMock.AddItemToCart invocations
func (mmAddItemToCart *CartServiceMock) AddItemToCartAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAddItemToCart.afterAddItemToCartCounter)
}

// AddItemToCartBeforeCounter returns a count of CartServiceMock.AddItemToCart invocations
func (mmAddItemToCart *CartServiceMock) AddItemToCartBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAddItemToCart.beforeAddItemToCartCounter)
}

// Calls returns a list of arguments used in each call to CartServiceMock.AddItemToCart.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmAddItemToCart *mCartServiceMockAddItemToCart) Calls() []*CartServiceMockAddItemToCartParams {
	mmAddItemToCart.mutex.RLock()

	argCopy := make([]*CartServiceMockAddItemToCartParams, len(mmAddItemToCart.callArgs))
	copy(argCopy, mmAddItemToCart.callArgs)

	mmAddItemToCart.mutex.RUnlock()

	return argCopy
}

// MinimockAddItemToCartDone returns true if the count of the AddItemToCart invocations corresponds
// the number of defined expectations
func (m *CartServiceMock) MinimockAddItemToCartDone() bool {
	if m.AddItemToCartMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.AddItemToCartMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.AddItemToCartMock.invocationsDone()
}

// MinimockAddItemToCartInspect logs each unmet expectation
func (m *CartServiceMock) MinimockAddItemToCartInspect() {
	for _, e := range m.AddItemToCartMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CartServiceMock.AddItemToCart at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterAddItemToCartCounter := mm_atomic.LoadUint64(&m.afterAddItemToCartCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.AddItemToCartMock.defaultExpectation != nil && afterAddItemToCartCounter < 1 {
		if m.AddItemToCartMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CartServiceMock.AddItemToCart at\n%s", m.AddItemToCartMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CartServiceMock.AddItemToCart at\n%s with params: %#v", m.AddItemToCartMock.defaultExpectation.expectationOrigins.origin, *m.AddItemToCartMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAddItemToCart != nil && afterAddItemToCartCounter < 1 {
		m.t.Errorf("Expected call to CartServiceMock.AddItemToCart at\n%s", m.funcAddItemToCartOrigin)
	}

	if !m.AddItemToCartMock.invocationsDone() && afterAddItemToCartCounter > 0 {
		m.t.Errorf("Expected %d calls to CartServiceMock.AddItemToCart at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.AddItemToCartMock.expectedInvocations), m.AddItemToCartMock.expectedInvocationsOrigin, afterAddItemToCartCounter)
	}
}

type mCartServiceMockDeleteAllFromCart struct {
	optional           bool
	mock               *CartServiceMock
	defaultExpectation *CartServiceMockDeleteAllFromCartExpectation
	expectations       []*CartServiceMockDeleteAllFromCartExpectation

	callArgs []*CartServiceMockDeleteAllFromCartParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CartServiceMockDeleteAllFromCartExpectation specifies expectation struct of the cartService.DeleteAllFromCart
type CartServiceMockDeleteAllFromCartExpectation struct {
	mock               *CartServiceMock
	params             *CartServiceMockDeleteAllFromCartParams
	paramPtrs          *CartServiceMockDeleteAllFromCartParamPtrs
	expectationOrigins CartServiceMockDeleteAllFromCartExpectationOrigins
	results            *CartServiceMockDeleteAllFromCartResults
	returnOrigin       string
	Counter            uint64
}

// CartServiceMockDeleteAllFromCartParams contains parameters of the cartService.DeleteAllFromCart
type CartServiceMockDeleteAllFromCartParams struct {
	userId int64
}

// CartServiceMockDeleteAllFromCartParamPtrs contains pointers to parameters of the cartService.DeleteAllFromCart
type CartServiceMockDeleteAllFromCartParamPtrs struct {
	userId *int64
}

// CartServiceMockDeleteAllFromCartResults contains results of the cartService.DeleteAllFromCart
type CartServiceMockDeleteAllFromCartResults struct {
	err error
}

// CartServiceMockDeleteAllFromCartOrigins contains origins of expectations of the cartService.DeleteAllFromCart
type CartServiceMockDeleteAllFromCartExpectationOrigins struct {
	origin       string
	originUserId string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDeleteAllFromCart *mCartServiceMockDeleteAllFromCart) Optional() *mCartServiceMockDeleteAllFromCart {
	mmDeleteAllFromCart.optional = true
	return mmDeleteAllFromCart
}

// Expect sets up expected params for cartService.DeleteAllFromCart
func (mmDeleteAllFromCart *mCartServiceMockDeleteAllFromCart) Expect(userId int64) *mCartServiceMockDeleteAllFromCart {
	if mmDeleteAllFromCart.mock.funcDeleteAllFromCart != nil {
		mmDeleteAllFromCart.mock.t.Fatalf("CartServiceMock.DeleteAllFromCart mock is already set by Set")
	}

	if mmDeleteAllFromCart.defaultExpectation == nil {
		mmDeleteAllFromCart.defaultExpectation = &CartServiceMockDeleteAllFromCartExpectation{}
	}

	if mmDeleteAllFromCart.defaultExpectation.paramPtrs != nil {
		mmDeleteAllFromCart.mock.t.Fatalf("CartServiceMock.DeleteAllFromCart mock is already set by ExpectParams functions")
	}

	mmDeleteAllFromCart.defaultExpectation.params = &CartServiceMockDeleteAllFromCartParams{userId}
	mmDeleteAllFromCart.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDeleteAllFromCart.expectations {
		if minimock.Equal(e.params, mmDeleteAllFromCart.defaultExpectation.params) {
			mmDeleteAllFromCart.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDeleteAllFromCart.defaultExpectation.params)
		}
	}

	return mmDeleteAllFromCart
}

// ExpectUserIdParam1 sets up expected param userId for cartService.DeleteAllFromCart
func (mmDeleteAllFromCart *mCartServiceMockDeleteAllFromCart) ExpectUserIdParam1(userId int64) *mCartServiceMockDeleteAllFromCart {
	if mmDeleteAllFromCart.mock.funcDeleteAllFromCart != nil {
		mmDeleteAllFromCart.mock.t.Fatalf("CartServiceMock.DeleteAllFromCart mock is already set by Set")
	}

	if mmDeleteAllFromCart.defaultExpectation == nil {
		mmDeleteAllFromCart.defaultExpectation = &CartServiceMockDeleteAllFromCartExpectation{}
	}

	if mmDeleteAllFromCart.defaultExpectation.params != nil {
		mmDeleteAllFromCart.mock.t.Fatalf("CartServiceMock.DeleteAllFromCart mock is already set by Expect")
	}

	if mmDeleteAllFromCart.defaultExpectation.paramPtrs == nil {
		mmDeleteAllFromCart.defaultExpectation.paramPtrs = &CartServiceMockDeleteAllFromCartParamPtrs{}
	}
	mmDeleteAllFromCart.defaultExpectation.paramPtrs.userId = &userId
	mmDeleteAllFromCart.defaultExpectation.expectationOrigins.originUserId = minimock.CallerInfo(1)

	return mmDeleteAllFromCart
}

// Inspect accepts an inspector function that has same arguments as the cartService.DeleteAllFromCart
func (mmDeleteAllFromCart *mCartServiceMockDeleteAllFromCart) Inspect(f func(userId int64)) *mCartServiceMockDeleteAllFromCart {
	if mmDeleteAllFromCart.mock.inspectFuncDeleteAllFromCart != nil {
		mmDeleteAllFromCart.mock.t.Fatalf("Inspect function is already set for CartServiceMock.DeleteAllFromCart")
	}

	mmDeleteAllFromCart.mock.inspectFuncDeleteAllFromCart = f

	return mmDeleteAllFromCart
}

// Return sets up results that will be returned by cartService.DeleteAllFromCart
func (mmDeleteAllFromCart *mCartServiceMockDeleteAllFromCart) Return(err error) *CartServiceMock {
	if mmDeleteAllFromCart.mock.funcDeleteAllFromCart != nil {
		mmDeleteAllFromCart.mock.t.Fatalf("CartServiceMock.DeleteAllFromCart mock is already set by Set")
	}

	if mmDeleteAllFromCart.defaultExpectation == nil {
		mmDeleteAllFromCart.defaultExpectation = &CartServiceMockDeleteAllFromCartExpectation{mock: mmDeleteAllFromCart.mock}
	}
	mmDeleteAllFromCart.defaultExpectation.results = &CartServiceMockDeleteAllFromCartResults{err}
	mmDeleteAllFromCart.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDeleteAllFromCart.mock
}

// Set uses given function f to mock the cartService.DeleteAllFromCart method
func (mmDeleteAllFromCart *mCartServiceMockDeleteAllFromCart) Set(f func(userId int64) (err error)) *CartServiceMock {
	if mmDeleteAllFromCart.defaultExpectation != nil {
		mmDeleteAllFromCart.mock.t.Fatalf("Default expectation is already set for the cartService.DeleteAllFromCart method")
	}

	if len(mmDeleteAllFromCart.expectations) > 0 {
		mmDeleteAllFromCart.mock.t.Fatalf("Some expectations are already set for the cartService.DeleteAllFromCart method")
	}

	mmDeleteAllFromCart.mock.funcDeleteAllFromCart = f
	mmDeleteAllFromCart.mock.funcDeleteAllFromCartOrigin = minimock.CallerInfo(1)
	return mmDeleteAllFromCart.mock
}

// When sets expectation for the cartService.DeleteAllFromCart which will trigger the result defined by the following
// Then helper
func (mmDeleteAllFromCart *mCartServiceMockDeleteAllFromCart) When(userId int64) *CartServiceMockDeleteAllFromCartExpectation {
	if mmDeleteAllFromCart.mock.funcDeleteAllFromCart != nil {
		mmDeleteAllFromCart.mock.t.Fatalf("CartServiceMock.DeleteAllFromCart mock is already set by Set")
	}

	expectation := &CartServiceMockDeleteAllFromCartExpectation{
		mock:               mmDeleteAllFromCart.mock,
		params:             &CartServiceMockDeleteAllFromCartParams{userId},
		expectationOrigins: CartServiceMockDeleteAllFromCartExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDeleteAllFromCart.expectations = append(mmDeleteAllFromCart.expectations, expectation)
	return expectation
}

// Then sets up cartService.DeleteAllFromCart return parameters for the expectation previously defined by the When method
func (e *CartServiceMockDeleteAllFromCartExpectation) Then(err error) *CartServiceMock {
	e.results = &CartServiceMockDeleteAllFromCartResults{err}
	return e.mock
}

// Times sets number of times cartService.DeleteAllFromCart should be invoked
func (mmDeleteAllFromCart *mCartServiceMockDeleteAllFromCart) Times(n uint64) *mCartServiceMockDeleteAllFromCart {
	if n == 0 {
		mmDeleteAllFromCart.mock.t.Fatalf("Times of CartServiceMock.DeleteAllFromCart mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDeleteAllFromCart.expectedInvocations, n)
	mmDeleteAllFromCart.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDeleteAllFromCart
}

func (mmDeleteAllFromCart *mCartServiceMockDeleteAllFromCart) invocationsDone() bool {
	if len(mmDeleteAllFromCart.expectations) == 0 && mmDeleteAllFromCart.defaultExpectation == nil && mmDeleteAllFromCart.mock.funcDeleteAllFromCart == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDeleteAllFromCart.mock.afterDeleteAllFromCartCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDeleteAllFromCart.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DeleteAllFromCart implements mm_handler.cartService
func (mmDeleteAllFromCart *CartServiceMock) DeleteAllFromCart(userId int64) (err error) {
	mm_atomic.AddUint64(&mmDeleteAllFromCart.beforeDeleteAllFromCartCounter, 1)
	defer mm_atomic.AddUint64(&mmDeleteAllFromCart.afterDeleteAllFromCartCounter, 1)

	mmDeleteAllFromCart.t.Helper()

	if mmDeleteAllFromCart.inspectFuncDeleteAllFromCart != nil {
		mmDeleteAllFromCart.inspectFuncDeleteAllFromCart(userId)
	}

	mm_params := CartServiceMockDeleteAllFromCartParams{userId}

	// Record call args
	mmDeleteAllFromCart.DeleteAllFromCartMock.mutex.Lock()
	mmDeleteAllFromCart.DeleteAllFromCartMock.callArgs = append(mmDeleteAllFromCart.DeleteAllFromCartMock.callArgs, &mm_params)
	mmDeleteAllFromCart.DeleteAllFromCartMock.mutex.Unlock()

	for _, e := range mmDeleteAllFromCart.DeleteAllFromCartMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDeleteAllFromCart.DeleteAllFromCartMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDeleteAllFromCart.DeleteAllFromCartMock.defaultExpectation.Counter, 1)
		mm_want := mmDeleteAllFromCart.DeleteAllFromCartMock.defaultExpectation.params
		mm_want_ptrs := mmDeleteAllFromCart.DeleteAllFromCartMock.defaultExpectation.paramPtrs

		mm_got := CartServiceMockDeleteAllFromCartParams{userId}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.userId != nil && !minimock.Equal(*mm_want_ptrs.userId, mm_got.userId) {
				mmDeleteAllFromCart.t.Errorf("CartServiceMock.DeleteAllFromCart got unexpected parameter userId, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteAllFromCart.DeleteAllFromCartMock.defaultExpectation.expectationOrigins.originUserId, *mm_want_ptrs.userId, mm_got.userId, minimock.Diff(*mm_want_ptrs.userId, mm_got.userId))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDeleteAllFromCart.t.Errorf("CartServiceMock.DeleteAllFromCart got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDeleteAllFromCart.DeleteAllFromCartMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDeleteAllFromCart.DeleteAllFromCartMock.defaultExpectation.results
		if mm_results == nil {
			mmDeleteAllFromCart.t.Fatal("No results are set for the CartServiceMock.DeleteAllFromCart")
		}
		return (*mm_results).err
	}
	if mmDeleteAllFromCart.funcDeleteAllFromCart != nil {
		return mmDeleteAllFromCart.funcDeleteAllFromCart(userId)
	}
	mmDeleteAllFromCart.t.Fatalf("Unexpected call to CartServiceMock.DeleteAllFromCart. %v", userId)
	return
}

// DeleteAllFromCartAfterCounter returns a count of finished CartServiceMock.DeleteAllFromCart invocations
func (mmDeleteAllFromCart *CartServiceMock) DeleteAllFromCartAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteAllFromCart.afterDeleteAllFromCartCounter)
}

// DeleteAllFromCartBeforeCounter returns a count of CartServiceMock.DeleteAllFromCart invocations
func (mmDeleteAllFromCart *CartServiceMock) DeleteAllFromCartBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteAllFromCart.beforeDeleteAllFromCartCounter)
}

// Calls returns a list of arguments used in each call to CartServiceMock.DeleteAllFromCart.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDeleteAllFromCart *mCartServiceMockDeleteAllFromCart) Calls() []*CartServiceMockDeleteAllFromCartParams {
	mmDeleteAllFromCart.mutex.RLock()

	argCopy := make([]*CartServiceMockDeleteAllFromCartParams, len(mmDeleteAllFromCart.callArgs))
	copy(argCopy, mmDeleteAllFromCart.callArgs)

	mmDeleteAllFromCart.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteAllFromCartDone returns true if the count of the DeleteAllFromCart invocations corresponds
// the number of defined expectations
func (m *CartServiceMock) MinimockDeleteAllFromCartDone() bool {
	if m.DeleteAllFromCartMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteAllFromCartMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteAllFromCartMock.invocationsDone()
}

// MinimockDeleteAllFromCartInspect logs each unmet expectation
func (m *CartServiceMock) MinimockDeleteAllFromCartInspect() {
	for _, e := range m.DeleteAllFromCartMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CartServiceMock.DeleteAllFromCart at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteAllFromCartCounter := mm_atomic.LoadUint64(&m.afterDeleteAllFromCartCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteAllFromCartMock.defaultExpectation != nil && afterDeleteAllFromCartCounter < 1 {
		if m.DeleteAllFromCartMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CartServiceMock.DeleteAllFromCart at\n%s", m.DeleteAllFromCartMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CartServiceMock.DeleteAllFromCart at\n%s with params: %#v", m.DeleteAllFromCartMock.defaultExpectation.expectationOrigins.origin, *m.DeleteAllFromCartMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDeleteAllFromCart != nil && afterDeleteAllFromCartCounter < 1 {
		m.t.Errorf("Expected call to CartServiceMock.DeleteAllFromCart at\n%s", m.funcDeleteAllFromCartOrigin)
	}

	if !m.DeleteAllFromCartMock.invocationsDone() && afterDeleteAllFromCartCounter > 0 {
		m.t.Errorf("Expected %d calls to CartServiceMock.DeleteAllFromCart at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteAllFromCartMock.expectedInvocations), m.DeleteAllFromCartMock.expectedInvocationsOrigin, afterDeleteAllFromCartCounter)
	}
}

type mCartServiceMockDeleteFromCart struct {
	optional           bool
	mock               *CartServiceMock
	defaultExpectation *CartServiceMockDeleteFromCartExpectation
	expectations       []*CartServiceMockDeleteFromCartExpectation

	callArgs []*CartServiceMockDeleteFromCartParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CartServiceMockDeleteFromCartExpectation specifies expectation struct of the cartService.DeleteFromCart
type CartServiceMockDeleteFromCartExpectation struct {
	mock               *CartServiceMock
	params             *CartServiceMockDeleteFromCartParams
	paramPtrs          *CartServiceMockDeleteFromCartParamPtrs
	expectationOrigins CartServiceMockDeleteFromCartExpectationOrigins
	results            *CartServiceMockDeleteFromCartResults
	returnOrigin       string
	Counter            uint64
}

// CartServiceMockDeleteFromCartParams contains parameters of the cartService.DeleteFromCart
type CartServiceMockDeleteFromCartParams struct {
	userId int64
	skuId  int64
}

// CartServiceMockDeleteFromCartParamPtrs contains pointers to parameters of the cartService.DeleteFromCart
type CartServiceMockDeleteFromCartParamPtrs struct {
	userId *int64
	skuId  *int64
}

// CartServiceMockDeleteFromCartResults contains results of the cartService.DeleteFromCart
type CartServiceMockDeleteFromCartResults struct {
	err error
}

// CartServiceMockDeleteFromCartOrigins contains origins of expectations of the cartService.DeleteFromCart
type CartServiceMockDeleteFromCartExpectationOrigins struct {
	origin       string
	originUserId string
	originSkuId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDeleteFromCart *mCartServiceMockDeleteFromCart) Optional() *mCartServiceMockDeleteFromCart {
	mmDeleteFromCart.optional = true
	return mmDeleteFromCart
}

// Expect sets up expected params for cartService.DeleteFromCart
func (mmDeleteFromCart *mCartServiceMockDeleteFromCart) Expect(userId int64, skuId int64) *mCartServiceMockDeleteFromCart {
	if mmDeleteFromCart.mock.funcDeleteFromCart != nil {
		mmDeleteFromCart.mock.t.Fatalf("CartServiceMock.DeleteFromCart mock is already set by Set")
	}

	if mmDeleteFromCart.defaultExpectation == nil {
		mmDeleteFromCart.defaultExpectation = &CartServiceMockDeleteFromCartExpectation{}
	}

	if mmDeleteFromCart.defaultExpectation.paramPtrs != nil {
		mmDeleteFromCart.mock.t.Fatalf("CartServiceMock.DeleteFromCart mock is already set by ExpectParams functions")
	}

	mmDeleteFromCart.defaultExpectation.params = &CartServiceMockDeleteFromCartParams{userId, skuId}
	mmDeleteFromCart.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDeleteFromCart.expectations {
		if minimock.Equal(e.params, mmDeleteFromCart.defaultExpectation.params) {
			mmDeleteFromCart.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDeleteFromCart.defaultExpectation.params)
		}
	}

	return mmDeleteFromCart
}

// ExpectUserIdParam1 sets up expected param userId for cartService.DeleteFromCart
func (mmDeleteFromCart *mCartServiceMockDeleteFromCart) ExpectUserIdParam1(userId int64) *mCartServiceMockDeleteFromCart {
	if mmDeleteFromCart.mock.funcDeleteFromCart != nil {
		mmDeleteFromCart.mock.t.Fatalf("CartServiceMock.DeleteFromCart mock is already set by Set")
	}

	if mmDeleteFromCart.defaultExpectation == nil {
		mmDeleteFromCart.defaultExpectation = &CartServiceMockDeleteFromCartExpectation{}
	}

	if mmDeleteFromCart.defaultExpectation.params != nil {
		mmDeleteFromCart.mock.t.Fatalf("CartServiceMock.DeleteFromCart mock is already set by Expect")
	}

	if mmDeleteFromCart.defaultExpectation.paramPtrs == nil {
		mmDeleteFromCart.defaultExpectation.paramPtrs = &CartServiceMockDeleteFromCartParamPtrs{}
	}
	mmDeleteFromCart.defaultExpectation.paramPtrs.userId = &userId
	mmDeleteFromCart.defaultExpectation.expectationOrigins.originUserId = minimock.CallerInfo(1)

	return mmDeleteFromCart
}

// ExpectSkuIdParam2 sets up expected param skuId for cartService.DeleteFromCart
func (mmDeleteFromCart *mCartServiceMockDeleteFromCart) ExpectSkuIdParam2(skuId int64) *mCartServiceMockDeleteFromCart {
	if mmDeleteFromCart.mock.funcDeleteFromCart != nil {
		mmDeleteFromCart.mock.t.Fatalf("CartServiceMock.DeleteFromCart mock is already set by Set")
	}

	if mmDeleteFromCart.defaultExpectation == nil {
		mmDeleteFromCart.defaultExpectation = &CartServiceMockDeleteFromCartExpectation{}
	}

	if mmDeleteFromCart.defaultExpectation.params != nil {
		mmDeleteFromCart.mock.t.Fatalf("CartServiceMock.DeleteFromCart mock is already set by Expect")
	}

	if mmDeleteFromCart.defaultExpectation.paramPtrs == nil {
		mmDeleteFromCart.defaultExpectation.paramPtrs = &CartServiceMockDeleteFromCartParamPtrs{}
	}
	mmDeleteFromCart.defaultExpectation.paramPtrs.skuId = &skuId
	mmDeleteFromCart.defaultExpectation.expectationOrigins.originSkuId = minimock.CallerInfo(1)

	return mmDeleteFromCart
}

// Inspect accepts an inspector function that has same arguments as the cartService.DeleteFromCart
func (mmDeleteFromCart *mCartServiceMockDeleteFromCart) Inspect(f func(userId int64, skuId int64)) *mCartServiceMockDeleteFromCart {
	if mmDeleteFromCart.mock.inspectFuncDeleteFromCart != nil {
		mmDeleteFromCart.mock.t.Fatalf("Inspect function is already set for CartServiceMock.DeleteFromCart")
	}

	mmDeleteFromCart.mock.inspectFuncDeleteFromCart = f

	return mmDeleteFromCart
}

// Return sets up results that will be returned by cartService.DeleteFromCart
func (mmDeleteFromCart *mCartServiceMockDeleteFromCart) Return(err error) *CartServiceMock {
	if mmDeleteFromCart.mock.funcDeleteFromCart != nil {
		mmDeleteFromCart.mock.t.Fatalf("CartServiceMock.DeleteFromCart mock is already set by Set")
	}

	if mmDeleteFromCart.defaultExpectation == nil {
		mmDeleteFromCart.defaultExpectation = &CartServiceMockDeleteFromCartExpectation{mock: mmDeleteFromCart.mock}
	}
	mmDeleteFromCart.defaultExpectation.results = &CartServiceMockDeleteFromCartResults{err}
	mmDeleteFromCart.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDeleteFromCart.mock
}

// Set uses given function f to mock the cartService.DeleteFromCart method
func (mmDeleteFromCart *mCartServiceMockDeleteFromCart) Set(f func(userId int64, skuId int64) (err error)) *CartServiceMock {
	if mmDeleteFromCart.defaultExpectation != nil {
		mmDeleteFromCart.mock.t.Fatalf("Default expectation is already set for the cartService.DeleteFromCart method")
	}

	if len(mmDeleteFromCart.expectations) > 0 {
		mmDeleteFromCart.mock.t.Fatalf("Some expectations are already set for the cartService.DeleteFromCart method")
	}

	mmDeleteFromCart.mock.funcDeleteFromCart = f
	mmDeleteFromCart.mock.funcDeleteFromCartOrigin = minimock.CallerInfo(1)
	return mmDeleteFromCart.mock
}

// When sets expectation for the cartService.DeleteFromCart which will trigger the result defined by the following
// Then helper
func (mmDeleteFromCart *mCartServiceMockDeleteFromCart) When(userId int64, skuId int64) *CartServiceMockDeleteFromCartExpectation {
	if mmDeleteFromCart.mock.funcDeleteFromCart != nil {
		mmDeleteFromCart.mock.t.Fatalf("CartServiceMock.DeleteFromCart mock is already set by Set")
	}

	expectation := &CartServiceMockDeleteFromCartExpectation{
		mock:               mmDeleteFromCart.mock,
		params:             &CartServiceMockDeleteFromCartParams{userId, skuId},
		expectationOrigins: CartServiceMockDeleteFromCartExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDeleteFromCart.expectations = append(mmDeleteFromCart.expectations, expectation)
	return expectation
}

// Then sets up cartService.DeleteFromCart return parameters for the expectation previously defined by the When method
func (e *CartServiceMockDeleteFromCartExpectation) Then(err error) *CartServiceMock {
	e.results = &CartServiceMockDeleteFromCartResults{err}
	return e.mock
}

// Times sets number of times cartService.DeleteFromCart should be invoked
func (mmDeleteFromCart *mCartServiceMockDeleteFromCart) Times(n uint64) *mCartServiceMockDeleteFromCart {
	if n == 0 {
		mmDeleteFromCart.mock.t.Fatalf("Times of CartServiceMock.DeleteFromCart mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDeleteFromCart.expectedInvocations, n)
	mmDeleteFromCart.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDeleteFromCart
}

func (mmDeleteFromCart *mCartServiceMockDeleteFromCart) invocationsDone() bool {
	if len(mmDeleteFromCart.expectations) == 0 && mmDeleteFromCart.defaultExpectation == nil && mmDeleteFromCart.mock.funcDeleteFromCart == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDeleteFromCart.mock.afterDeleteFromCartCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDeleteFromCart.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DeleteFromCart implements mm_handler.cartService
func (mmDeleteFromCart *CartServiceMock) DeleteFromCart(userId int64, skuId int64) (err error) {
	mm_atomic.AddUint64(&mmDeleteFromCart.beforeDeleteFromCartCounter, 1)
	defer mm_atomic.AddUint64(&mmDeleteFromCart.afterDeleteFromCartCounter, 1)

	mmDeleteFromCart.t.Helper()

	if mmDeleteFromCart.inspectFuncDeleteFromCart != nil {
		mmDeleteFromCart.inspectFuncDeleteFromCart(userId, skuId)
	}

	mm_params := CartServiceMockDeleteFromCartParams{userId, skuId}

	// Record call args
	mmDeleteFromCart.DeleteFromCartMock.mutex.Lock()
	mmDeleteFromCart.DeleteFromCartMock.callArgs = append(mmDeleteFromCart.DeleteFromCartMock.callArgs, &mm_params)
	mmDeleteFromCart.DeleteFromCartMock.mutex.Unlock()

	for _, e := range mmDeleteFromCart.DeleteFromCartMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDeleteFromCart.DeleteFromCartMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDeleteFromCart.DeleteFromCartMock.defaultExpectation.Counter, 1)
		mm_want := mmDeleteFromCart.DeleteFromCartMock.defaultExpectation.params
		mm_want_ptrs := mmDeleteFromCart.DeleteFromCartMock.defaultExpectation.paramPtrs

		mm_got := CartServiceMockDeleteFromCartParams{userId, skuId}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.userId != nil && !minimock.Equal(*mm_want_ptrs.userId, mm_got.userId) {
				mmDeleteFromCart.t.Errorf("CartServiceMock.DeleteFromCart got unexpected parameter userId, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteFromCart.DeleteFromCartMock.defaultExpectation.expectationOrigins.originUserId, *mm_want_ptrs.userId, mm_got.userId, minimock.Diff(*mm_want_ptrs.userId, mm_got.userId))
			}

			if mm_want_ptrs.skuId != nil && !minimock.Equal(*mm_want_ptrs.skuId, mm_got.skuId) {
				mmDeleteFromCart.t.Errorf("CartServiceMock.DeleteFromCart got unexpected parameter skuId, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteFromCart.DeleteFromCartMock.defaultExpectation.expectationOrigins.originSkuId, *mm_want_ptrs.skuId, mm_got.skuId, minimock.Diff(*mm_want_ptrs.skuId, mm_got.skuId))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDeleteFromCart.t.Errorf("CartServiceMock.DeleteFromCart got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDeleteFromCart.DeleteFromCartMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDeleteFromCart.DeleteFromCartMock.defaultExpectation.results
		if mm_results == nil {
			mmDeleteFromCart.t.Fatal("No results are set for the CartServiceMock.DeleteFromCart")
		}
		return (*mm_results).err
	}
	if mmDeleteFromCart.funcDeleteFromCart != nil {
		return mmDeleteFromCart.funcDeleteFromCart(userId, skuId)
	}
	mmDeleteFromCart.t.Fatalf("Unexpected call to CartServiceMock.DeleteFromCart. %v %v", userId, skuId)
	return
}

// DeleteFromCartAfterCounter returns a count of finished CartServiceMock.DeleteFromCart invocations
func (mmDeleteFromCart *CartServiceMock) DeleteFromCartAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteFromCart.afterDeleteFromCartCounter)
}

// DeleteFromCartBeforeCounter returns a count of CartServiceMock.DeleteFromCart invocations
func (mmDeleteFromCart *CartServiceMock) DeleteFromCartBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteFromCart.beforeDeleteFromCartCounter)
}

// Calls returns a list of arguments used in each call to CartServiceMock.DeleteFromCart.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDeleteFromCart *mCartServiceMockDeleteFromCart) Calls() []*CartServiceMockDeleteFromCartParams {
	mmDeleteFromCart.mutex.RLock()

	argCopy := make([]*CartServiceMockDeleteFromCartParams, len(mmDeleteFromCart.callArgs))
	copy(argCopy, mmDeleteFromCart.callArgs)

	mmDeleteFromCart.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteFromCartDone returns true if the count of the DeleteFromCart invocations corresponds
// the number of defined expectations
func (m *CartServiceMock) MinimockDeleteFromCartDone() bool {
	if m.DeleteFromCartMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteFromCartMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteFromCartMock.invocationsDone()
}

// MinimockDeleteFromCartInspect logs each unmet expectation
func (m *CartServiceMock) MinimockDeleteFromCartInspect() {
	for _, e := range m.DeleteFromCartMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CartServiceMock.DeleteFromCart at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteFromCartCounter := mm_atomic.LoadUint64(&m.afterDeleteFromCartCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteFromCartMock.defaultExpectation != nil && afterDeleteFromCartCounter < 1 {
		if m.DeleteFromCartMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CartServiceMock.DeleteFromCart at\n%s", m.DeleteFromCartMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CartServiceMock.DeleteFromCart at\n%s with params: %#v", m.DeleteFromCartMock.defaultExpectation.expectationOrigins.origin, *m.DeleteFromCartMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDeleteFromCart != nil && afterDeleteFromCartCounter < 1 {
		m.t.Errorf("Expected call to CartServiceMock.DeleteFromCart at\n%s", m.funcDeleteFromCartOrigin)
	}

	if !m.DeleteFromCartMock.invocationsDone() && afterDeleteFromCartCounter > 0 {
		m.t.Errorf("Expected %d calls to CartServiceMock.DeleteFromCart at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteFromCartMock.expectedInvocations), m.DeleteFromCartMock.expectedInvocationsOrigin, afterDeleteFromCartCounter)
	}
}

type mCartServiceMockGetItems struct {
	optional           bool
	mock               *CartServiceMock
	defaultExpectation *CartServiceMockGetItemsExpectation
	expectations       []*CartServiceMockGetItemsExpectation

	callArgs []*CartServiceMockGetItemsParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CartServiceMockGetItemsExpectation specifies expectation struct of the cartService.GetItems
type CartServiceMockGetItemsExpectation struct {
	mock               *CartServiceMock
	params             *CartServiceMockGetItemsParams
	paramPtrs          *CartServiceMockGetItemsParamPtrs
	expectationOrigins CartServiceMockGetItemsExpectationOrigins
	results            *CartServiceMockGetItemsResults
	returnOrigin       string
	Counter            uint64
}

// CartServiceMockGetItemsParams contains parameters of the cartService.GetItems
type CartServiceMockGetItemsParams struct {
	userId int64
}

// CartServiceMockGetItemsParamPtrs contains pointers to parameters of the cartService.GetItems
type CartServiceMockGetItemsParamPtrs struct {
	userId *int64
}

// CartServiceMockGetItemsResults contains results of the cartService.GetItems
type CartServiceMockGetItemsResults struct {
	up1 *model.UserData
	err error
}

// CartServiceMockGetItemsOrigins contains origins of expectations of the cartService.GetItems
type CartServiceMockGetItemsExpectationOrigins struct {
	origin       string
	originUserId string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetItems *mCartServiceMockGetItems) Optional() *mCartServiceMockGetItems {
	mmGetItems.optional = true
	return mmGetItems
}

// Expect sets up expected params for cartService.GetItems
func (mmGetItems *mCartServiceMockGetItems) Expect(userId int64) *mCartServiceMockGetItems {
	if mmGetItems.mock.funcGetItems != nil {
		mmGetItems.mock.t.Fatalf("CartServiceMock.GetItems mock is already set by Set")
	}

	if mmGetItems.defaultExpectation == nil {
		mmGetItems.defaultExpectation = &CartServiceMockGetItemsExpectation{}
	}

	if mmGetItems.defaultExpectation.paramPtrs != nil {
		mmGetItems.mock.t.Fatalf("CartServiceMock.GetItems mock is already set by ExpectParams functions")
	}

	mmGetItems.defaultExpectation.params = &CartServiceMockGetItemsParams{userId}
	mmGetItems.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetItems.expectations {
		if minimock.Equal(e.params, mmGetItems.defaultExpectation.params) {
			mmGetItems.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetItems.defaultExpectation.params)
		}
	}

	return mmGetItems
}

// ExpectUserIdParam1 sets up expected param userId for cartService.GetItems
func (mmGetItems *mCartServiceMockGetItems) ExpectUserIdParam1(userId int64) *mCartServiceMockGetItems {
	if mmGetItems.mock.funcGetItems != nil {
		mmGetItems.mock.t.Fatalf("CartServiceMock.GetItems mock is already set by Set")
	}

	if mmGetItems.defaultExpectation == nil {
		mmGetItems.defaultExpectation = &CartServiceMockGetItemsExpectation{}
	}

	if mmGetItems.defaultExpectation.params != nil {
		mmGetItems.mock.t.Fatalf("CartServiceMock.GetItems mock is already set by Expect")
	}

	if mmGetItems.defaultExpectation.paramPtrs == nil {
		mmGetItems.defaultExpectation.paramPtrs = &CartServiceMockGetItemsParamPtrs{}
	}
	mmGetItems.defaultExpectation.paramPtrs.userId = &userId
	mmGetItems.defaultExpectation.expectationOrigins.originUserId = minimock.CallerInfo(1)

	return mmGetItems
}

// Inspect accepts an inspector function that has same arguments as the cartService.GetItems
func (mmGetItems *mCartServiceMockGetItems) Inspect(f func(userId int64)) *mCartServiceMockGetItems {
	if mmGetItems.mock.inspectFuncGetItems != nil {
		mmGetItems.mock.t.Fatalf("Inspect function is already set for CartServiceMock.GetItems")
	}

	mmGetItems.mock.inspectFuncGetItems = f

	return mmGetItems
}

// Return sets up results that will be returned by cartService.GetItems
func (mmGetItems *mCartServiceMockGetItems) Return(up1 *model.UserData, err error) *CartServiceMock {
	if mmGetItems.mock.funcGetItems != nil {
		mmGetItems.mock.t.Fatalf("CartServiceMock.GetItems mock is already set by Set")
	}

	if mmGetItems.defaultExpectation == nil {
		mmGetItems.defaultExpectation = &CartServiceMockGetItemsExpectation{mock: mmGetItems.mock}
	}
	mmGetItems.defaultExpectation.results = &CartServiceMockGetItemsResults{up1, err}
	mmGetItems.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetItems.mock
}

// Set uses given function f to mock the cartService.GetItems method
func (mmGetItems *mCartServiceMockGetItems) Set(f func(userId int64) (up1 *model.UserData, err error)) *CartServiceMock {
	if mmGetItems.defaultExpectation != nil {
		mmGetItems.mock.t.Fatalf("Default expectation is already set for the cartService.GetItems method")
	}

	if len(mmGetItems.expectations) > 0 {
		mmGetItems.mock.t.Fatalf("Some expectations are already set for the cartService.GetItems method")
	}

	mmGetItems.mock.funcGetItems = f
	mmGetItems.mock.funcGetItemsOrigin = minimock.CallerInfo(1)
	return mmGetItems.mock
}

// When sets expectation for the cartService.GetItems which will trigger the result defined by the following
// Then helper
func (mmGetItems *mCartServiceMockGetItems) When(userId int64) *CartServiceMockGetItemsExpectation {
	if mmGetItems.mock.funcGetItems != nil {
		mmGetItems.mock.t.Fatalf("CartServiceMock.GetItems mock is already set by Set")
	}

	expectation := &CartServiceMockGetItemsExpectation{
		mock:               mmGetItems.mock,
		params:             &CartServiceMockGetItemsParams{userId},
		expectationOrigins: CartServiceMockGetItemsExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetItems.expectations = append(mmGetItems.expectations, expectation)
	return expectation
}

// Then sets up cartService.GetItems return parameters for the expectation previously defined by the When method
func (e *CartServiceMockGetItemsExpectation) Then(up1 *model.UserData, err error) *CartServiceMock {
	e.results = &CartServiceMockGetItemsResults{up1, err}
	return e.mock
}

// Times sets number of times cartService.GetItems should be invoked
func (mmGetItems *mCartServiceMockGetItems) Times(n uint64) *mCartServiceMockGetItems {
	if n == 0 {
		mmGetItems.mock.t.Fatalf("Times of CartServiceMock.GetItems mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetItems.expectedInvocations, n)
	mmGetItems.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetItems
}

func (mmGetItems *mCartServiceMockGetItems) invocationsDone() bool {
	if len(mmGetItems.expectations) == 0 && mmGetItems.defaultExpectation == nil && mmGetItems.mock.funcGetItems == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetItems.mock.afterGetItemsCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetItems.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetItems implements mm_handler.cartService
func (mmGetItems *CartServiceMock) GetItems(userId int64) (up1 *model.UserData, err error) {
	mm_atomic.AddUint64(&mmGetItems.beforeGetItemsCounter, 1)
	defer mm_atomic.AddUint64(&mmGetItems.afterGetItemsCounter, 1)

	mmGetItems.t.Helper()

	if mmGetItems.inspectFuncGetItems != nil {
		mmGetItems.inspectFuncGetItems(userId)
	}

	mm_params := CartServiceMockGetItemsParams{userId}

	// Record call args
	mmGetItems.GetItemsMock.mutex.Lock()
	mmGetItems.GetItemsMock.callArgs = append(mmGetItems.GetItemsMock.callArgs, &mm_params)
	mmGetItems.GetItemsMock.mutex.Unlock()

	for _, e := range mmGetItems.GetItemsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.up1, e.results.err
		}
	}

	if mmGetItems.GetItemsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetItems.GetItemsMock.defaultExpectation.Counter, 1)
		mm_want := mmGetItems.GetItemsMock.defaultExpectation.params
		mm_want_ptrs := mmGetItems.GetItemsMock.defaultExpectation.paramPtrs

		mm_got := CartServiceMockGetItemsParams{userId}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.userId != nil && !minimock.Equal(*mm_want_ptrs.userId, mm_got.userId) {
				mmGetItems.t.Errorf("CartServiceMock.GetItems got unexpected parameter userId, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetItems.GetItemsMock.defaultExpectation.expectationOrigins.originUserId, *mm_want_ptrs.userId, mm_got.userId, minimock.Diff(*mm_want_ptrs.userId, mm_got.userId))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetItems.t.Errorf("CartServiceMock.GetItems got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetItems.GetItemsMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetItems.GetItemsMock.defaultExpectation.results
		if mm_results == nil {
			mmGetItems.t.Fatal("No results are set for the CartServiceMock.GetItems")
		}
		return (*mm_results).up1, (*mm_results).err
	}
	if mmGetItems.funcGetItems != nil {
		return mmGetItems.funcGetItems(userId)
	}
	mmGetItems.t.Fatalf("Unexpected call to CartServiceMock.GetItems. %v", userId)
	return
}

// GetItemsAfterCounter returns a count of finished CartServiceMock.GetItems invocations
func (mmGetItems *CartServiceMock) GetItemsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetItems.afterGetItemsCounter)
}

// GetItemsBeforeCounter returns a count of CartServiceMock.GetItems invocations
func (mmGetItems *CartServiceMock) GetItemsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetItems.beforeGetItemsCounter)
}

// Calls returns a list of arguments used in each call to CartServiceMock.GetItems.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetItems *mCartServiceMockGetItems) Calls() []*CartServiceMockGetItemsParams {
	mmGetItems.mutex.RLock()

	argCopy := make([]*CartServiceMockGetItemsParams, len(mmGetItems.callArgs))
	copy(argCopy, mmGetItems.callArgs)

	mmGetItems.mutex.RUnlock()

	return argCopy
}

// MinimockGetItemsDone returns true if the count of the GetItems invocations corresponds
// the number of defined expectations
func (m *CartServiceMock) MinimockGetItemsDone() bool {
	if m.GetItemsMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetItemsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetItemsMock.invocationsDone()
}

// MinimockGetItemsInspect logs each unmet expectation
func (m *CartServiceMock) MinimockGetItemsInspect() {
	for _, e := range m.GetItemsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CartServiceMock.GetItems at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetItemsCounter := mm_atomic.LoadUint64(&m.afterGetItemsCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetItemsMock.defaultExpectation != nil && afterGetItemsCounter < 1 {
		if m.GetItemsMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CartServiceMock.GetItems at\n%s", m.GetItemsMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CartServiceMock.GetItems at\n%s with params: %#v", m.GetItemsMock.defaultExpectation.expectationOrigins.origin, *m.GetItemsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetItems != nil && afterGetItemsCounter < 1 {
		m.t.Errorf("Expected call to CartServiceMock.GetItems at\n%s", m.funcGetItemsOrigin)
	}

	if !m.GetItemsMock.invocationsDone() && afterGetItemsCounter > 0 {
		m.t.Errorf("Expected %d calls to CartServiceMock.GetItems at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetItemsMock.expectedInvocations), m.GetItemsMock.expectedInvocationsOrigin, afterGetItemsCounter)
	}
}

type mCartServiceMockGetProduct struct {
	optional           bool
	mock               *CartServiceMock
	defaultExpectation *CartServiceMockGetProductExpectation
	expectations       []*CartServiceMockGetProductExpectation

	callArgs []*CartServiceMockGetProductParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CartServiceMockGetProductExpectation specifies expectation struct of the cartService.GetProduct
type CartServiceMockGetProductExpectation struct {
	mock               *CartServiceMock
	params             *CartServiceMockGetProductParams
	paramPtrs          *CartServiceMockGetProductParamPtrs
	expectationOrigins CartServiceMockGetProductExpectationOrigins
	results            *CartServiceMockGetProductResults
	returnOrigin       string
	Counter            uint64
}

// CartServiceMockGetProductParams contains parameters of the cartService.GetProduct
type CartServiceMockGetProductParams struct {
	productId int64
}

// CartServiceMockGetProductParamPtrs contains pointers to parameters of the cartService.GetProduct
type CartServiceMockGetProductParamPtrs struct {
	productId *int64
}

// CartServiceMockGetProductResults contains results of the cartService.GetProduct
type CartServiceMockGetProductResults struct {
	pp1 *model.Product
	err error
}

// CartServiceMockGetProductOrigins contains origins of expectations of the cartService.GetProduct
type CartServiceMockGetProductExpectationOrigins struct {
	origin          string
	originProductId string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetProduct *mCartServiceMockGetProduct) Optional() *mCartServiceMockGetProduct {
	mmGetProduct.optional = true
	return mmGetProduct
}

// Expect sets up expected params for cartService.GetProduct
func (mmGetProduct *mCartServiceMockGetProduct) Expect(productId int64) *mCartServiceMockGetProduct {
	if mmGetProduct.mock.funcGetProduct != nil {
		mmGetProduct.mock.t.Fatalf("CartServiceMock.GetProduct mock is already set by Set")
	}

	if mmGetProduct.defaultExpectation == nil {
		mmGetProduct.defaultExpectation = &CartServiceMockGetProductExpectation{}
	}

	if mmGetProduct.defaultExpectation.paramPtrs != nil {
		mmGetProduct.mock.t.Fatalf("CartServiceMock.GetProduct mock is already set by ExpectParams functions")
	}

	mmGetProduct.defaultExpectation.params = &CartServiceMockGetProductParams{productId}
	mmGetProduct.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetProduct.expectations {
		if minimock.Equal(e.params, mmGetProduct.defaultExpectation.params) {
			mmGetProduct.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetProduct.defaultExpectation.params)
		}
	}

	return mmGetProduct
}

// ExpectProductIdParam1 sets up expected param productId for cartService.GetProduct
func (mmGetProduct *mCartServiceMockGetProduct) ExpectProductIdParam1(productId int64) *mCartServiceMockGetProduct {
	if mmGetProduct.mock.funcGetProduct != nil {
		mmGetProduct.mock.t.Fatalf("CartServiceMock.GetProduct mock is already set by Set")
	}

	if mmGetProduct.defaultExpectation == nil {
		mmGetProduct.defaultExpectation = &CartServiceMockGetProductExpectation{}
	}

	if mmGetProduct.defaultExpectation.params != nil {
		mmGetProduct.mock.t.Fatalf("CartServiceMock.GetProduct mock is already set by Expect")
	}

	if mmGetProduct.defaultExpectation.paramPtrs == nil {
		mmGetProduct.defaultExpectation.paramPtrs = &CartServiceMockGetProductParamPtrs{}
	}
	mmGetProduct.defaultExpectation.paramPtrs.productId = &productId
	mmGetProduct.defaultExpectation.expectationOrigins.originProductId = minimock.CallerInfo(1)

	return mmGetProduct
}

// Inspect accepts an inspector function that has same arguments as the cartService.GetProduct
func (mmGetProduct *mCartServiceMockGetProduct) Inspect(f func(productId int64)) *mCartServiceMockGetProduct {
	if mmGetProduct.mock.inspectFuncGetProduct != nil {
		mmGetProduct.mock.t.Fatalf("Inspect function is already set for CartServiceMock.GetProduct")
	}

	mmGetProduct.mock.inspectFuncGetProduct = f

	return mmGetProduct
}

// Return sets up results that will be returned by cartService.GetProduct
func (mmGetProduct *mCartServiceMockGetProduct) Return(pp1 *model.Product, err error) *CartServiceMock {
	if mmGetProduct.mock.funcGetProduct != nil {
		mmGetProduct.mock.t.Fatalf("CartServiceMock.GetProduct mock is already set by Set")
	}

	if mmGetProduct.defaultExpectation == nil {
		mmGetProduct.defaultExpectation = &CartServiceMockGetProductExpectation{mock: mmGetProduct.mock}
	}
	mmGetProduct.defaultExpectation.results = &CartServiceMockGetProductResults{pp1, err}
	mmGetProduct.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetProduct.mock
}

// Set uses given function f to mock the cartService.GetProduct method
func (mmGetProduct *mCartServiceMockGetProduct) Set(f func(productId int64) (pp1 *model.Product, err error)) *CartServiceMock {
	if mmGetProduct.defaultExpectation != nil {
		mmGetProduct.mock.t.Fatalf("Default expectation is already set for the cartService.GetProduct method")
	}

	if len(mmGetProduct.expectations) > 0 {
		mmGetProduct.mock.t.Fatalf("Some expectations are already set for the cartService.GetProduct method")
	}

	mmGetProduct.mock.funcGetProduct = f
	mmGetProduct.mock.funcGetProductOrigin = minimock.CallerInfo(1)
	return mmGetProduct.mock
}

// When sets expectation for the cartService.GetProduct which will trigger the result defined by the following
// Then helper
func (mmGetProduct *mCartServiceMockGetProduct) When(productId int64) *CartServiceMockGetProductExpectation {
	if mmGetProduct.mock.funcGetProduct != nil {
		mmGetProduct.mock.t.Fatalf("CartServiceMock.GetProduct mock is already set by Set")
	}

	expectation := &CartServiceMockGetProductExpectation{
		mock:               mmGetProduct.mock,
		params:             &CartServiceMockGetProductParams{productId},
		expectationOrigins: CartServiceMockGetProductExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetProduct.expectations = append(mmGetProduct.expectations, expectation)
	return expectation
}

// Then sets up cartService.GetProduct return parameters for the expectation previously defined by the When method
func (e *CartServiceMockGetProductExpectation) Then(pp1 *model.Product, err error) *CartServiceMock {
	e.results = &CartServiceMockGetProductResults{pp1, err}
	return e.mock
}

// Times sets number of times cartService.GetProduct should be invoked
func (mmGetProduct *mCartServiceMockGetProduct) Times(n uint64) *mCartServiceMockGetProduct {
	if n == 0 {
		mmGetProduct.mock.t.Fatalf("Times of CartServiceMock.GetProduct mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetProduct.expectedInvocations, n)
	mmGetProduct.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetProduct
}

func (mmGetProduct *mCartServiceMockGetProduct) invocationsDone() bool {
	if len(mmGetProduct.expectations) == 0 && mmGetProduct.defaultExpectation == nil && mmGetProduct.mock.funcGetProduct == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetProduct.mock.afterGetProductCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetProduct.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetProduct implements mm_handler.cartService
func (mmGetProduct *CartServiceMock) GetProduct(productId int64) (pp1 *model.Product, err error) {
	mm_atomic.AddUint64(&mmGetProduct.beforeGetProductCounter, 1)
	defer mm_atomic.AddUint64(&mmGetProduct.afterGetProductCounter, 1)

	mmGetProduct.t.Helper()

	if mmGetProduct.inspectFuncGetProduct != nil {
		mmGetProduct.inspectFuncGetProduct(productId)
	}

	mm_params := CartServiceMockGetProductParams{productId}

	// Record call args
	mmGetProduct.GetProductMock.mutex.Lock()
	mmGetProduct.GetProductMock.callArgs = append(mmGetProduct.GetProductMock.callArgs, &mm_params)
	mmGetProduct.GetProductMock.mutex.Unlock()

	for _, e := range mmGetProduct.GetProductMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.pp1, e.results.err
		}
	}

	if mmGetProduct.GetProductMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetProduct.GetProductMock.defaultExpectation.Counter, 1)
		mm_want := mmGetProduct.GetProductMock.defaultExpectation.params
		mm_want_ptrs := mmGetProduct.GetProductMock.defaultExpectation.paramPtrs

		mm_got := CartServiceMockGetProductParams{productId}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.productId != nil && !minimock.Equal(*mm_want_ptrs.productId, mm_got.productId) {
				mmGetProduct.t.Errorf("CartServiceMock.GetProduct got unexpected parameter productId, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetProduct.GetProductMock.defaultExpectation.expectationOrigins.originProductId, *mm_want_ptrs.productId, mm_got.productId, minimock.Diff(*mm_want_ptrs.productId, mm_got.productId))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetProduct.t.Errorf("CartServiceMock.GetProduct got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetProduct.GetProductMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetProduct.GetProductMock.defaultExpectation.results
		if mm_results == nil {
			mmGetProduct.t.Fatal("No results are set for the CartServiceMock.GetProduct")
		}
		return (*mm_results).pp1, (*mm_results).err
	}
	if mmGetProduct.funcGetProduct != nil {
		return mmGetProduct.funcGetProduct(productId)
	}
	mmGetProduct.t.Fatalf("Unexpected call to CartServiceMock.GetProduct. %v", productId)
	return
}

// GetProductAfterCounter returns a count of finished CartServiceMock.GetProduct invocations
func (mmGetProduct *CartServiceMock) GetProductAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetProduct.afterGetProductCounter)
}

// GetProductBeforeCounter returns a count of CartServiceMock.GetProduct invocations
func (mmGetProduct *CartServiceMock) GetProductBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetProduct.beforeGetProductCounter)
}

// Calls returns a list of arguments used in each call to CartServiceMock.GetProduct.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetProduct *mCartServiceMockGetProduct) Calls() []*CartServiceMockGetProductParams {
	mmGetProduct.mutex.RLock()

	argCopy := make([]*CartServiceMockGetProductParams, len(mmGetProduct.callArgs))
	copy(argCopy, mmGetProduct.callArgs)

	mmGetProduct.mutex.RUnlock()

	return argCopy
}

// MinimockGetProductDone returns true if the count of the GetProduct invocations corresponds
// the number of defined expectations
func (m *CartServiceMock) MinimockGetProductDone() bool {
	if m.GetProductMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetProductMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetProductMock.invocationsDone()
}

// MinimockGetProductInspect logs each unmet expectation
func (m *CartServiceMock) MinimockGetProductInspect() {
	for _, e := range m.GetProductMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CartServiceMock.GetProduct at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetProductCounter := mm_atomic.LoadUint64(&m.afterGetProductCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetProductMock.defaultExpectation != nil && afterGetProductCounter < 1 {
		if m.GetProductMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CartServiceMock.GetProduct at\n%s", m.GetProductMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CartServiceMock.GetProduct at\n%s with params: %#v", m.GetProductMock.defaultExpectation.expectationOrigins.origin, *m.GetProductMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetProduct != nil && afterGetProductCounter < 1 {
		m.t.Errorf("Expected call to CartServiceMock.GetProduct at\n%s", m.funcGetProductOrigin)
	}

	if !m.GetProductMock.invocationsDone() && afterGetProductCounter > 0 {
		m.t.Errorf("Expected %d calls to CartServiceMock.GetProduct at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetProductMock.expectedInvocations), m.GetProductMock.expectedInvocationsOrigin, afterGetProductCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *CartServiceMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockAddItemToCartInspect()

			m.MinimockDeleteAllFromCartInspect()

			m.MinimockDeleteFromCartInspect()

			m.MinimockGetItemsInspect()

			m.MinimockGetProductInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *CartServiceMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *CartServiceMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockAddItemToCartDone() &&
		m.MinimockDeleteAllFromCartDone() &&
		m.MinimockDeleteFromCartDone() &&
		m.MinimockGetItemsDone() &&
		m.MinimockGetProductDone()
}
