// Code generated by http://github.com/gojuno/minimock (v3.4.0). DO NOT EDIT.

package mocks

//go:generate minimock -i route256/cart/internal/service.cartRepo -o cart_repo_mock.go -n CartRepoMock -p mocks

import (
	"route256/cart/internal/model"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// CartRepoMock implements mm_service.cartRepo
type CartRepoMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcAddItemToCart          func(userId int64, item *model.Item) (err error)
	funcAddItemToCartOrigin    string
	inspectFuncAddItemToCart   func(userId int64, item *model.Item)
	afterAddItemToCartCounter  uint64
	beforeAddItemToCartCounter uint64
	AddItemToCartMock          mCartRepoMockAddItemToCart

	funcDeleteAllFromCart          func(userId int64) (err error)
	funcDeleteAllFromCartOrigin    string
	inspectFuncDeleteAllFromCart   func(userId int64)
	afterDeleteAllFromCartCounter  uint64
	beforeDeleteAllFromCartCounter uint64
	DeleteAllFromCartMock          mCartRepoMockDeleteAllFromCart

	funcDeleteFromCart          func(userId int64, skuId int64) (err error)
	funcDeleteFromCartOrigin    string
	inspectFuncDeleteFromCart   func(userId int64, skuId int64)
	afterDeleteFromCartCounter  uint64
	beforeDeleteFromCartCounter uint64
	DeleteFromCartMock          mCartRepoMockDeleteFromCart

	funcGetItems          func(userId int64) (up1 *model.UserData, err error)
	funcGetItemsOrigin    string
	inspectFuncGetItems   func(userId int64)
	afterGetItemsCounter  uint64
	beforeGetItemsCounter uint64
	GetItemsMock          mCartRepoMockGetItems
}

// NewCartRepoMock returns a mock for mm_service.cartRepo
func NewCartRepoMock(t minimock.Tester) *CartRepoMock {
	m := &CartRepoMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.AddItemToCartMock = mCartRepoMockAddItemToCart{mock: m}
	m.AddItemToCartMock.callArgs = []*CartRepoMockAddItemToCartParams{}

	m.DeleteAllFromCartMock = mCartRepoMockDeleteAllFromCart{mock: m}
	m.DeleteAllFromCartMock.callArgs = []*CartRepoMockDeleteAllFromCartParams{}

	m.DeleteFromCartMock = mCartRepoMockDeleteFromCart{mock: m}
	m.DeleteFromCartMock.callArgs = []*CartRepoMockDeleteFromCartParams{}

	m.GetItemsMock = mCartRepoMockGetItems{mock: m}
	m.GetItemsMock.callArgs = []*CartRepoMockGetItemsParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mCartRepoMockAddItemToCart struct {
	optional           bool
	mock               *CartRepoMock
	defaultExpectation *CartRepoMockAddItemToCartExpectation
	expectations       []*CartRepoMockAddItemToCartExpectation

	callArgs []*CartRepoMockAddItemToCartParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CartRepoMockAddItemToCartExpectation specifies expectation struct of the cartRepo.AddItemToCart
type CartRepoMockAddItemToCartExpectation struct {
	mock               *CartRepoMock
	params             *CartRepoMockAddItemToCartParams
	paramPtrs          *CartRepoMockAddItemToCartParamPtrs
	expectationOrigins CartRepoMockAddItemToCartExpectationOrigins
	results            *CartRepoMockAddItemToCartResults
	returnOrigin       string
	Counter            uint64
}

// CartRepoMockAddItemToCartParams contains parameters of the cartRepo.AddItemToCart
type CartRepoMockAddItemToCartParams struct {
	userId int64
	item   *model.Item
}

// CartRepoMockAddItemToCartParamPtrs contains pointers to parameters of the cartRepo.AddItemToCart
type CartRepoMockAddItemToCartParamPtrs struct {
	userId *int64
	item   **model.Item
}

// CartRepoMockAddItemToCartResults contains results of the cartRepo.AddItemToCart
type CartRepoMockAddItemToCartResults struct {
	err error
}

// CartRepoMockAddItemToCartOrigins contains origins of expectations of the cartRepo.AddItemToCart
type CartRepoMockAddItemToCartExpectationOrigins struct {
	origin       string
	originUserId string
	originItem   string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmAddItemToCart *mCartRepoMockAddItemToCart) Optional() *mCartRepoMockAddItemToCart {
	mmAddItemToCart.optional = true
	return mmAddItemToCart
}

// Expect sets up expected params for cartRepo.AddItemToCart
func (mmAddItemToCart *mCartRepoMockAddItemToCart) Expect(userId int64, item *model.Item) *mCartRepoMockAddItemToCart {
	if mmAddItemToCart.mock.funcAddItemToCart != nil {
		mmAddItemToCart.mock.t.Fatalf("CartRepoMock.AddItemToCart mock is already set by Set")
	}

	if mmAddItemToCart.defaultExpectation == nil {
		mmAddItemToCart.defaultExpectation = &CartRepoMockAddItemToCartExpectation{}
	}

	if mmAddItemToCart.defaultExpectation.paramPtrs != nil {
		mmAddItemToCart.mock.t.Fatalf("CartRepoMock.AddItemToCart mock is already set by ExpectParams functions")
	}

	mmAddItemToCart.defaultExpectation.params = &CartRepoMockAddItemToCartParams{userId, item}
	mmAddItemToCart.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmAddItemToCart.expectations {
		if minimock.Equal(e.params, mmAddItemToCart.defaultExpectation.params) {
			mmAddItemToCart.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmAddItemToCart.defaultExpectation.params)
		}
	}

	return mmAddItemToCart
}

// ExpectUserIdParam1 sets up expected param userId for cartRepo.AddItemToCart
func (mmAddItemToCart *mCartRepoMockAddItemToCart) ExpectUserIdParam1(userId int64) *mCartRepoMockAddItemToCart {
	if mmAddItemToCart.mock.funcAddItemToCart != nil {
		mmAddItemToCart.mock.t.Fatalf("CartRepoMock.AddItemToCart mock is already set by Set")
	}

	if mmAddItemToCart.defaultExpectation == nil {
		mmAddItemToCart.defaultExpectation = &CartRepoMockAddItemToCartExpectation{}
	}

	if mmAddItemToCart.defaultExpectation.params != nil {
		mmAddItemToCart.mock.t.Fatalf("CartRepoMock.AddItemToCart mock is already set by Expect")
	}

	if mmAddItemToCart.defaultExpectation.paramPtrs == nil {
		mmAddItemToCart.defaultExpectation.paramPtrs = &CartRepoMockAddItemToCartParamPtrs{}
	}
	mmAddItemToCart.defaultExpectation.paramPtrs.userId = &userId
	mmAddItemToCart.defaultExpectation.expectationOrigins.originUserId = minimock.CallerInfo(1)

	return mmAddItemToCart
}

// ExpectItemParam2 sets up expected param item for cartRepo.AddItemToCart
func (mmAddItemToCart *mCartRepoMockAddItemToCart) ExpectItemParam2(item *model.Item) *mCartRepoMockAddItemToCart {
	if mmAddItemToCart.mock.funcAddItemToCart != nil {
		mmAddItemToCart.mock.t.Fatalf("CartRepoMock.AddItemToCart mock is already set by Set")
	}

	if mmAddItemToCart.defaultExpectation == nil {
		mmAddItemToCart.defaultExpectation = &CartRepoMockAddItemToCartExpectation{}
	}

	if mmAddItemToCart.defaultExpectation.params != nil {
		mmAddItemToCart.mock.t.Fatalf("CartRepoMock.AddItemToCart mock is already set by Expect")
	}

	if mmAddItemToCart.defaultExpectation.paramPtrs == nil {
		mmAddItemToCart.defaultExpectation.paramPtrs = &CartRepoMockAddItemToCartParamPtrs{}
	}
	mmAddItemToCart.defaultExpectation.paramPtrs.item = &item
	mmAddItemToCart.defaultExpectation.expectationOrigins.originItem = minimock.CallerInfo(1)

	return mmAddItemToCart
}

// Inspect accepts an inspector function that has same arguments as the cartRepo.AddItemToCart
func (mmAddItemToCart *mCartRepoMockAddItemToCart) Inspect(f func(userId int64, item *model.Item)) *mCartRepoMockAddItemToCart {
	if mmAddItemToCart.mock.inspectFuncAddItemToCart != nil {
		mmAddItemToCart.mock.t.Fatalf("Inspect function is already set for CartRepoMock.AddItemToCart")
	}

	mmAddItemToCart.mock.inspectFuncAddItemToCart = f

	return mmAddItemToCart
}

// Return sets up results that will be returned by cartRepo.AddItemToCart
func (mmAddItemToCart *mCartRepoMockAddItemToCart) Return(err error) *CartRepoMock {
	if mmAddItemToCart.mock.funcAddItemToCart != nil {
		mmAddItemToCart.mock.t.Fatalf("CartRepoMock.AddItemToCart mock is already set by Set")
	}

	if mmAddItemToCart.defaultExpectation == nil {
		mmAddItemToCart.defaultExpectation = &CartRepoMockAddItemToCartExpectation{mock: mmAddItemToCart.mock}
	}
	mmAddItemToCart.defaultExpectation.results = &CartRepoMockAddItemToCartResults{err}
	mmAddItemToCart.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmAddItemToCart.mock
}

// Set uses given function f to mock the cartRepo.AddItemToCart method
func (mmAddItemToCart *mCartRepoMockAddItemToCart) Set(f func(userId int64, item *model.Item) (err error)) *CartRepoMock {
	if mmAddItemToCart.defaultExpectation != nil {
		mmAddItemToCart.mock.t.Fatalf("Default expectation is already set for the cartRepo.AddItemToCart method")
	}

	if len(mmAddItemToCart.expectations) > 0 {
		mmAddItemToCart.mock.t.Fatalf("Some expectations are already set for the cartRepo.AddItemToCart method")
	}

	mmAddItemToCart.mock.funcAddItemToCart = f
	mmAddItemToCart.mock.funcAddItemToCartOrigin = minimock.CallerInfo(1)
	return mmAddItemToCart.mock
}

// When sets expectation for the cartRepo.AddItemToCart which will trigger the result defined by the following
// Then helper
func (mmAddItemToCart *mCartRepoMockAddItemToCart) When(userId int64, item *model.Item) *CartRepoMockAddItemToCartExpectation {
	if mmAddItemToCart.mock.funcAddItemToCart != nil {
		mmAddItemToCart.mock.t.Fatalf("CartRepoMock.AddItemToCart mock is already set by Set")
	}

	expectation := &CartRepoMockAddItemToCartExpectation{
		mock:               mmAddItemToCart.mock,
		params:             &CartRepoMockAddItemToCartParams{userId, item},
		expectationOrigins: CartRepoMockAddItemToCartExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmAddItemToCart.expectations = append(mmAddItemToCart.expectations, expectation)
	return expectation
}

// Then sets up cartRepo.AddItemToCart return parameters for the expectation previously defined by the When method
func (e *CartRepoMockAddItemToCartExpectation) Then(err error) *CartRepoMock {
	e.results = &CartRepoMockAddItemToCartResults{err}
	return e.mock
}

// Times sets number of times cartRepo.AddItemToCart should be invoked
func (mmAddItemToCart *mCartRepoMockAddItemToCart) Times(n uint64) *mCartRepoMockAddItemToCart {
	if n == 0 {
		mmAddItemToCart.mock.t.Fatalf("Times of CartRepoMock.AddItemToCart mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmAddItemToCart.expectedInvocations, n)
	mmAddItemToCart.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmAddItemToCart
}

func (mmAddItemToCart *mCartRepoMockAddItemToCart) invocationsDone() bool {
	if len(mmAddItemToCart.expectations) == 0 && mmAddItemToCart.defaultExpectation == nil && mmAddItemToCart.mock.funcAddItemToCart == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmAddItemToCart.mock.afterAddItemToCartCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmAddItemToCart.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// AddItemToCart implements mm_service.cartRepo
func (mmAddItemToCart *CartRepoMock) AddItemToCart(userId int64, item *model.Item) (err error) {
	mm_atomic.AddUint64(&mmAddItemToCart.beforeAddItemToCartCounter, 1)
	defer mm_atomic.AddUint64(&mmAddItemToCart.afterAddItemToCartCounter, 1)

	mmAddItemToCart.t.Helper()

	if mmAddItemToCart.inspectFuncAddItemToCart != nil {
		mmAddItemToCart.inspectFuncAddItemToCart(userId, item)
	}

	mm_params := CartRepoMockAddItemToCartParams{userId, item}

	// Record call args
	mmAddItemToCart.AddItemToCartMock.mutex.Lock()
	mmAddItemToCart.AddItemToCartMock.callArgs = append(mmAddItemToCart.AddItemToCartMock.callArgs, &mm_params)
	mmAddItemToCart.AddItemToCartMock.mutex.Unlock()

	for _, e := range mmAddItemToCart.AddItemToCartMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmAddItemToCart.AddItemToCartMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmAddItemToCart.AddItemToCartMock.defaultExpectation.Counter, 1)
		mm_want := mmAddItemToCart.AddItemToCartMock.defaultExpectation.params
		mm_want_ptrs := mmAddItemToCart.AddItemToCartMock.defaultExpectation.paramPtrs

		mm_got := CartRepoMockAddItemToCartParams{userId, item}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.userId != nil && !minimock.Equal(*mm_want_ptrs.userId, mm_got.userId) {
				mmAddItemToCart.t.Errorf("CartRepoMock.AddItemToCart got unexpected parameter userId, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAddItemToCart.AddItemToCartMock.defaultExpectation.expectationOrigins.originUserId, *mm_want_ptrs.userId, mm_got.userId, minimock.Diff(*mm_want_ptrs.userId, mm_got.userId))
			}

			if mm_want_ptrs.item != nil && !minimock.Equal(*mm_want_ptrs.item, mm_got.item) {
				mmAddItemToCart.t.Errorf("CartRepoMock.AddItemToCart got unexpected parameter item, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmAddItemToCart.AddItemToCartMock.defaultExpectation.expectationOrigins.originItem, *mm_want_ptrs.item, mm_got.item, minimock.Diff(*mm_want_ptrs.item, mm_got.item))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmAddItemToCart.t.Errorf("CartRepoMock.AddItemToCart got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmAddItemToCart.AddItemToCartMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmAddItemToCart.AddItemToCartMock.defaultExpectation.results
		if mm_results == nil {
			mmAddItemToCart.t.Fatal("No results are set for the CartRepoMock.AddItemToCart")
		}
		return (*mm_results).err
	}
	if mmAddItemToCart.funcAddItemToCart != nil {
		return mmAddItemToCart.funcAddItemToCart(userId, item)
	}
	mmAddItemToCart.t.Fatalf("Unexpected call to CartRepoMock.AddItemToCart. %v %v", userId, item)
	return
}

// AddItemToCartAfterCounter returns a count of finished CartRepoMock.AddItemToCart invocations
func (mmAddItemToCart *CartRepoMock) AddItemToCartAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAddItemToCart.afterAddItemToCartCounter)
}

// AddItemToCartBeforeCounter returns a count of CartRepoMock.AddItemToCart invocations
func (mmAddItemToCart *CartRepoMock) AddItemToCartBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmAddItemToCart.beforeAddItemToCartCounter)
}

// Calls returns a list of arguments used in each call to CartRepoMock.AddItemToCart.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmAddItemToCart *mCartRepoMockAddItemToCart) Calls() []*CartRepoMockAddItemToCartParams {
	mmAddItemToCart.mutex.RLock()

	argCopy := make([]*CartRepoMockAddItemToCartParams, len(mmAddItemToCart.callArgs))
	copy(argCopy, mmAddItemToCart.callArgs)

	mmAddItemToCart.mutex.RUnlock()

	return argCopy
}

// MinimockAddItemToCartDone returns true if the count of the AddItemToCart invocations corresponds
// the number of defined expectations
func (m *CartRepoMock) MinimockAddItemToCartDone() bool {
	if m.AddItemToCartMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.AddItemToCartMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.AddItemToCartMock.invocationsDone()
}

// MinimockAddItemToCartInspect logs each unmet expectation
func (m *CartRepoMock) MinimockAddItemToCartInspect() {
	for _, e := range m.AddItemToCartMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CartRepoMock.AddItemToCart at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterAddItemToCartCounter := mm_atomic.LoadUint64(&m.afterAddItemToCartCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.AddItemToCartMock.defaultExpectation != nil && afterAddItemToCartCounter < 1 {
		if m.AddItemToCartMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CartRepoMock.AddItemToCart at\n%s", m.AddItemToCartMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CartRepoMock.AddItemToCart at\n%s with params: %#v", m.AddItemToCartMock.defaultExpectation.expectationOrigins.origin, *m.AddItemToCartMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcAddItemToCart != nil && afterAddItemToCartCounter < 1 {
		m.t.Errorf("Expected call to CartRepoMock.AddItemToCart at\n%s", m.funcAddItemToCartOrigin)
	}

	if !m.AddItemToCartMock.invocationsDone() && afterAddItemToCartCounter > 0 {
		m.t.Errorf("Expected %d calls to CartRepoMock.AddItemToCart at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.AddItemToCartMock.expectedInvocations), m.AddItemToCartMock.expectedInvocationsOrigin, afterAddItemToCartCounter)
	}
}

type mCartRepoMockDeleteAllFromCart struct {
	optional           bool
	mock               *CartRepoMock
	defaultExpectation *CartRepoMockDeleteAllFromCartExpectation
	expectations       []*CartRepoMockDeleteAllFromCartExpectation

	callArgs []*CartRepoMockDeleteAllFromCartParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CartRepoMockDeleteAllFromCartExpectation specifies expectation struct of the cartRepo.DeleteAllFromCart
type CartRepoMockDeleteAllFromCartExpectation struct {
	mock               *CartRepoMock
	params             *CartRepoMockDeleteAllFromCartParams
	paramPtrs          *CartRepoMockDeleteAllFromCartParamPtrs
	expectationOrigins CartRepoMockDeleteAllFromCartExpectationOrigins
	results            *CartRepoMockDeleteAllFromCartResults
	returnOrigin       string
	Counter            uint64
}

// CartRepoMockDeleteAllFromCartParams contains parameters of the cartRepo.DeleteAllFromCart
type CartRepoMockDeleteAllFromCartParams struct {
	userId int64
}

// CartRepoMockDeleteAllFromCartParamPtrs contains pointers to parameters of the cartRepo.DeleteAllFromCart
type CartRepoMockDeleteAllFromCartParamPtrs struct {
	userId *int64
}

// CartRepoMockDeleteAllFromCartResults contains results of the cartRepo.DeleteAllFromCart
type CartRepoMockDeleteAllFromCartResults struct {
	err error
}

// CartRepoMockDeleteAllFromCartOrigins contains origins of expectations of the cartRepo.DeleteAllFromCart
type CartRepoMockDeleteAllFromCartExpectationOrigins struct {
	origin       string
	originUserId string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDeleteAllFromCart *mCartRepoMockDeleteAllFromCart) Optional() *mCartRepoMockDeleteAllFromCart {
	mmDeleteAllFromCart.optional = true
	return mmDeleteAllFromCart
}

// Expect sets up expected params for cartRepo.DeleteAllFromCart
func (mmDeleteAllFromCart *mCartRepoMockDeleteAllFromCart) Expect(userId int64) *mCartRepoMockDeleteAllFromCart {
	if mmDeleteAllFromCart.mock.funcDeleteAllFromCart != nil {
		mmDeleteAllFromCart.mock.t.Fatalf("CartRepoMock.DeleteAllFromCart mock is already set by Set")
	}

	if mmDeleteAllFromCart.defaultExpectation == nil {
		mmDeleteAllFromCart.defaultExpectation = &CartRepoMockDeleteAllFromCartExpectation{}
	}

	if mmDeleteAllFromCart.defaultExpectation.paramPtrs != nil {
		mmDeleteAllFromCart.mock.t.Fatalf("CartRepoMock.DeleteAllFromCart mock is already set by ExpectParams functions")
	}

	mmDeleteAllFromCart.defaultExpectation.params = &CartRepoMockDeleteAllFromCartParams{userId}
	mmDeleteAllFromCart.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDeleteAllFromCart.expectations {
		if minimock.Equal(e.params, mmDeleteAllFromCart.defaultExpectation.params) {
			mmDeleteAllFromCart.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDeleteAllFromCart.defaultExpectation.params)
		}
	}

	return mmDeleteAllFromCart
}

// ExpectUserIdParam1 sets up expected param userId for cartRepo.DeleteAllFromCart
func (mmDeleteAllFromCart *mCartRepoMockDeleteAllFromCart) ExpectUserIdParam1(userId int64) *mCartRepoMockDeleteAllFromCart {
	if mmDeleteAllFromCart.mock.funcDeleteAllFromCart != nil {
		mmDeleteAllFromCart.mock.t.Fatalf("CartRepoMock.DeleteAllFromCart mock is already set by Set")
	}

	if mmDeleteAllFromCart.defaultExpectation == nil {
		mmDeleteAllFromCart.defaultExpectation = &CartRepoMockDeleteAllFromCartExpectation{}
	}

	if mmDeleteAllFromCart.defaultExpectation.params != nil {
		mmDeleteAllFromCart.mock.t.Fatalf("CartRepoMock.DeleteAllFromCart mock is already set by Expect")
	}

	if mmDeleteAllFromCart.defaultExpectation.paramPtrs == nil {
		mmDeleteAllFromCart.defaultExpectation.paramPtrs = &CartRepoMockDeleteAllFromCartParamPtrs{}
	}
	mmDeleteAllFromCart.defaultExpectation.paramPtrs.userId = &userId
	mmDeleteAllFromCart.defaultExpectation.expectationOrigins.originUserId = minimock.CallerInfo(1)

	return mmDeleteAllFromCart
}

// Inspect accepts an inspector function that has same arguments as the cartRepo.DeleteAllFromCart
func (mmDeleteAllFromCart *mCartRepoMockDeleteAllFromCart) Inspect(f func(userId int64)) *mCartRepoMockDeleteAllFromCart {
	if mmDeleteAllFromCart.mock.inspectFuncDeleteAllFromCart != nil {
		mmDeleteAllFromCart.mock.t.Fatalf("Inspect function is already set for CartRepoMock.DeleteAllFromCart")
	}

	mmDeleteAllFromCart.mock.inspectFuncDeleteAllFromCart = f

	return mmDeleteAllFromCart
}

// Return sets up results that will be returned by cartRepo.DeleteAllFromCart
func (mmDeleteAllFromCart *mCartRepoMockDeleteAllFromCart) Return(err error) *CartRepoMock {
	if mmDeleteAllFromCart.mock.funcDeleteAllFromCart != nil {
		mmDeleteAllFromCart.mock.t.Fatalf("CartRepoMock.DeleteAllFromCart mock is already set by Set")
	}

	if mmDeleteAllFromCart.defaultExpectation == nil {
		mmDeleteAllFromCart.defaultExpectation = &CartRepoMockDeleteAllFromCartExpectation{mock: mmDeleteAllFromCart.mock}
	}
	mmDeleteAllFromCart.defaultExpectation.results = &CartRepoMockDeleteAllFromCartResults{err}
	mmDeleteAllFromCart.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDeleteAllFromCart.mock
}

// Set uses given function f to mock the cartRepo.DeleteAllFromCart method
func (mmDeleteAllFromCart *mCartRepoMockDeleteAllFromCart) Set(f func(userId int64) (err error)) *CartRepoMock {
	if mmDeleteAllFromCart.defaultExpectation != nil {
		mmDeleteAllFromCart.mock.t.Fatalf("Default expectation is already set for the cartRepo.DeleteAllFromCart method")
	}

	if len(mmDeleteAllFromCart.expectations) > 0 {
		mmDeleteAllFromCart.mock.t.Fatalf("Some expectations are already set for the cartRepo.DeleteAllFromCart method")
	}

	mmDeleteAllFromCart.mock.funcDeleteAllFromCart = f
	mmDeleteAllFromCart.mock.funcDeleteAllFromCartOrigin = minimock.CallerInfo(1)
	return mmDeleteAllFromCart.mock
}

// When sets expectation for the cartRepo.DeleteAllFromCart which will trigger the result defined by the following
// Then helper
func (mmDeleteAllFromCart *mCartRepoMockDeleteAllFromCart) When(userId int64) *CartRepoMockDeleteAllFromCartExpectation {
	if mmDeleteAllFromCart.mock.funcDeleteAllFromCart != nil {
		mmDeleteAllFromCart.mock.t.Fatalf("CartRepoMock.DeleteAllFromCart mock is already set by Set")
	}

	expectation := &CartRepoMockDeleteAllFromCartExpectation{
		mock:               mmDeleteAllFromCart.mock,
		params:             &CartRepoMockDeleteAllFromCartParams{userId},
		expectationOrigins: CartRepoMockDeleteAllFromCartExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDeleteAllFromCart.expectations = append(mmDeleteAllFromCart.expectations, expectation)
	return expectation
}

// Then sets up cartRepo.DeleteAllFromCart return parameters for the expectation previously defined by the When method
func (e *CartRepoMockDeleteAllFromCartExpectation) Then(err error) *CartRepoMock {
	e.results = &CartRepoMockDeleteAllFromCartResults{err}
	return e.mock
}

// Times sets number of times cartRepo.DeleteAllFromCart should be invoked
func (mmDeleteAllFromCart *mCartRepoMockDeleteAllFromCart) Times(n uint64) *mCartRepoMockDeleteAllFromCart {
	if n == 0 {
		mmDeleteAllFromCart.mock.t.Fatalf("Times of CartRepoMock.DeleteAllFromCart mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDeleteAllFromCart.expectedInvocations, n)
	mmDeleteAllFromCart.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDeleteAllFromCart
}

func (mmDeleteAllFromCart *mCartRepoMockDeleteAllFromCart) invocationsDone() bool {
	if len(mmDeleteAllFromCart.expectations) == 0 && mmDeleteAllFromCart.defaultExpectation == nil && mmDeleteAllFromCart.mock.funcDeleteAllFromCart == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDeleteAllFromCart.mock.afterDeleteAllFromCartCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDeleteAllFromCart.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DeleteAllFromCart implements mm_service.cartRepo
func (mmDeleteAllFromCart *CartRepoMock) DeleteAllFromCart(userId int64) (err error) {
	mm_atomic.AddUint64(&mmDeleteAllFromCart.beforeDeleteAllFromCartCounter, 1)
	defer mm_atomic.AddUint64(&mmDeleteAllFromCart.afterDeleteAllFromCartCounter, 1)

	mmDeleteAllFromCart.t.Helper()

	if mmDeleteAllFromCart.inspectFuncDeleteAllFromCart != nil {
		mmDeleteAllFromCart.inspectFuncDeleteAllFromCart(userId)
	}

	mm_params := CartRepoMockDeleteAllFromCartParams{userId}

	// Record call args
	mmDeleteAllFromCart.DeleteAllFromCartMock.mutex.Lock()
	mmDeleteAllFromCart.DeleteAllFromCartMock.callArgs = append(mmDeleteAllFromCart.DeleteAllFromCartMock.callArgs, &mm_params)
	mmDeleteAllFromCart.DeleteAllFromCartMock.mutex.Unlock()

	for _, e := range mmDeleteAllFromCart.DeleteAllFromCartMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDeleteAllFromCart.DeleteAllFromCartMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDeleteAllFromCart.DeleteAllFromCartMock.defaultExpectation.Counter, 1)
		mm_want := mmDeleteAllFromCart.DeleteAllFromCartMock.defaultExpectation.params
		mm_want_ptrs := mmDeleteAllFromCart.DeleteAllFromCartMock.defaultExpectation.paramPtrs

		mm_got := CartRepoMockDeleteAllFromCartParams{userId}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.userId != nil && !minimock.Equal(*mm_want_ptrs.userId, mm_got.userId) {
				mmDeleteAllFromCart.t.Errorf("CartRepoMock.DeleteAllFromCart got unexpected parameter userId, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteAllFromCart.DeleteAllFromCartMock.defaultExpectation.expectationOrigins.originUserId, *mm_want_ptrs.userId, mm_got.userId, minimock.Diff(*mm_want_ptrs.userId, mm_got.userId))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDeleteAllFromCart.t.Errorf("CartRepoMock.DeleteAllFromCart got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDeleteAllFromCart.DeleteAllFromCartMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDeleteAllFromCart.DeleteAllFromCartMock.defaultExpectation.results
		if mm_results == nil {
			mmDeleteAllFromCart.t.Fatal("No results are set for the CartRepoMock.DeleteAllFromCart")
		}
		return (*mm_results).err
	}
	if mmDeleteAllFromCart.funcDeleteAllFromCart != nil {
		return mmDeleteAllFromCart.funcDeleteAllFromCart(userId)
	}
	mmDeleteAllFromCart.t.Fatalf("Unexpected call to CartRepoMock.DeleteAllFromCart. %v", userId)
	return
}

// DeleteAllFromCartAfterCounter returns a count of finished CartRepoMock.DeleteAllFromCart invocations
func (mmDeleteAllFromCart *CartRepoMock) DeleteAllFromCartAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteAllFromCart.afterDeleteAllFromCartCounter)
}

// DeleteAllFromCartBeforeCounter returns a count of CartRepoMock.DeleteAllFromCart invocations
func (mmDeleteAllFromCart *CartRepoMock) DeleteAllFromCartBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteAllFromCart.beforeDeleteAllFromCartCounter)
}

// Calls returns a list of arguments used in each call to CartRepoMock.DeleteAllFromCart.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDeleteAllFromCart *mCartRepoMockDeleteAllFromCart) Calls() []*CartRepoMockDeleteAllFromCartParams {
	mmDeleteAllFromCart.mutex.RLock()

	argCopy := make([]*CartRepoMockDeleteAllFromCartParams, len(mmDeleteAllFromCart.callArgs))
	copy(argCopy, mmDeleteAllFromCart.callArgs)

	mmDeleteAllFromCart.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteAllFromCartDone returns true if the count of the DeleteAllFromCart invocations corresponds
// the number of defined expectations
func (m *CartRepoMock) MinimockDeleteAllFromCartDone() bool {
	if m.DeleteAllFromCartMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteAllFromCartMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteAllFromCartMock.invocationsDone()
}

// MinimockDeleteAllFromCartInspect logs each unmet expectation
func (m *CartRepoMock) MinimockDeleteAllFromCartInspect() {
	for _, e := range m.DeleteAllFromCartMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CartRepoMock.DeleteAllFromCart at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteAllFromCartCounter := mm_atomic.LoadUint64(&m.afterDeleteAllFromCartCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteAllFromCartMock.defaultExpectation != nil && afterDeleteAllFromCartCounter < 1 {
		if m.DeleteAllFromCartMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CartRepoMock.DeleteAllFromCart at\n%s", m.DeleteAllFromCartMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CartRepoMock.DeleteAllFromCart at\n%s with params: %#v", m.DeleteAllFromCartMock.defaultExpectation.expectationOrigins.origin, *m.DeleteAllFromCartMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDeleteAllFromCart != nil && afterDeleteAllFromCartCounter < 1 {
		m.t.Errorf("Expected call to CartRepoMock.DeleteAllFromCart at\n%s", m.funcDeleteAllFromCartOrigin)
	}

	if !m.DeleteAllFromCartMock.invocationsDone() && afterDeleteAllFromCartCounter > 0 {
		m.t.Errorf("Expected %d calls to CartRepoMock.DeleteAllFromCart at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteAllFromCartMock.expectedInvocations), m.DeleteAllFromCartMock.expectedInvocationsOrigin, afterDeleteAllFromCartCounter)
	}
}

type mCartRepoMockDeleteFromCart struct {
	optional           bool
	mock               *CartRepoMock
	defaultExpectation *CartRepoMockDeleteFromCartExpectation
	expectations       []*CartRepoMockDeleteFromCartExpectation

	callArgs []*CartRepoMockDeleteFromCartParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CartRepoMockDeleteFromCartExpectation specifies expectation struct of the cartRepo.DeleteFromCart
type CartRepoMockDeleteFromCartExpectation struct {
	mock               *CartRepoMock
	params             *CartRepoMockDeleteFromCartParams
	paramPtrs          *CartRepoMockDeleteFromCartParamPtrs
	expectationOrigins CartRepoMockDeleteFromCartExpectationOrigins
	results            *CartRepoMockDeleteFromCartResults
	returnOrigin       string
	Counter            uint64
}

// CartRepoMockDeleteFromCartParams contains parameters of the cartRepo.DeleteFromCart
type CartRepoMockDeleteFromCartParams struct {
	userId int64
	skuId  int64
}

// CartRepoMockDeleteFromCartParamPtrs contains pointers to parameters of the cartRepo.DeleteFromCart
type CartRepoMockDeleteFromCartParamPtrs struct {
	userId *int64
	skuId  *int64
}

// CartRepoMockDeleteFromCartResults contains results of the cartRepo.DeleteFromCart
type CartRepoMockDeleteFromCartResults struct {
	err error
}

// CartRepoMockDeleteFromCartOrigins contains origins of expectations of the cartRepo.DeleteFromCart
type CartRepoMockDeleteFromCartExpectationOrigins struct {
	origin       string
	originUserId string
	originSkuId  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmDeleteFromCart *mCartRepoMockDeleteFromCart) Optional() *mCartRepoMockDeleteFromCart {
	mmDeleteFromCart.optional = true
	return mmDeleteFromCart
}

// Expect sets up expected params for cartRepo.DeleteFromCart
func (mmDeleteFromCart *mCartRepoMockDeleteFromCart) Expect(userId int64, skuId int64) *mCartRepoMockDeleteFromCart {
	if mmDeleteFromCart.mock.funcDeleteFromCart != nil {
		mmDeleteFromCart.mock.t.Fatalf("CartRepoMock.DeleteFromCart mock is already set by Set")
	}

	if mmDeleteFromCart.defaultExpectation == nil {
		mmDeleteFromCart.defaultExpectation = &CartRepoMockDeleteFromCartExpectation{}
	}

	if mmDeleteFromCart.defaultExpectation.paramPtrs != nil {
		mmDeleteFromCart.mock.t.Fatalf("CartRepoMock.DeleteFromCart mock is already set by ExpectParams functions")
	}

	mmDeleteFromCart.defaultExpectation.params = &CartRepoMockDeleteFromCartParams{userId, skuId}
	mmDeleteFromCart.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmDeleteFromCart.expectations {
		if minimock.Equal(e.params, mmDeleteFromCart.defaultExpectation.params) {
			mmDeleteFromCart.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmDeleteFromCart.defaultExpectation.params)
		}
	}

	return mmDeleteFromCart
}

// ExpectUserIdParam1 sets up expected param userId for cartRepo.DeleteFromCart
func (mmDeleteFromCart *mCartRepoMockDeleteFromCart) ExpectUserIdParam1(userId int64) *mCartRepoMockDeleteFromCart {
	if mmDeleteFromCart.mock.funcDeleteFromCart != nil {
		mmDeleteFromCart.mock.t.Fatalf("CartRepoMock.DeleteFromCart mock is already set by Set")
	}

	if mmDeleteFromCart.defaultExpectation == nil {
		mmDeleteFromCart.defaultExpectation = &CartRepoMockDeleteFromCartExpectation{}
	}

	if mmDeleteFromCart.defaultExpectation.params != nil {
		mmDeleteFromCart.mock.t.Fatalf("CartRepoMock.DeleteFromCart mock is already set by Expect")
	}

	if mmDeleteFromCart.defaultExpectation.paramPtrs == nil {
		mmDeleteFromCart.defaultExpectation.paramPtrs = &CartRepoMockDeleteFromCartParamPtrs{}
	}
	mmDeleteFromCart.defaultExpectation.paramPtrs.userId = &userId
	mmDeleteFromCart.defaultExpectation.expectationOrigins.originUserId = minimock.CallerInfo(1)

	return mmDeleteFromCart
}

// ExpectSkuIdParam2 sets up expected param skuId for cartRepo.DeleteFromCart
func (mmDeleteFromCart *mCartRepoMockDeleteFromCart) ExpectSkuIdParam2(skuId int64) *mCartRepoMockDeleteFromCart {
	if mmDeleteFromCart.mock.funcDeleteFromCart != nil {
		mmDeleteFromCart.mock.t.Fatalf("CartRepoMock.DeleteFromCart mock is already set by Set")
	}

	if mmDeleteFromCart.defaultExpectation == nil {
		mmDeleteFromCart.defaultExpectation = &CartRepoMockDeleteFromCartExpectation{}
	}

	if mmDeleteFromCart.defaultExpectation.params != nil {
		mmDeleteFromCart.mock.t.Fatalf("CartRepoMock.DeleteFromCart mock is already set by Expect")
	}

	if mmDeleteFromCart.defaultExpectation.paramPtrs == nil {
		mmDeleteFromCart.defaultExpectation.paramPtrs = &CartRepoMockDeleteFromCartParamPtrs{}
	}
	mmDeleteFromCart.defaultExpectation.paramPtrs.skuId = &skuId
	mmDeleteFromCart.defaultExpectation.expectationOrigins.originSkuId = minimock.CallerInfo(1)

	return mmDeleteFromCart
}

// Inspect accepts an inspector function that has same arguments as the cartRepo.DeleteFromCart
func (mmDeleteFromCart *mCartRepoMockDeleteFromCart) Inspect(f func(userId int64, skuId int64)) *mCartRepoMockDeleteFromCart {
	if mmDeleteFromCart.mock.inspectFuncDeleteFromCart != nil {
		mmDeleteFromCart.mock.t.Fatalf("Inspect function is already set for CartRepoMock.DeleteFromCart")
	}

	mmDeleteFromCart.mock.inspectFuncDeleteFromCart = f

	return mmDeleteFromCart
}

// Return sets up results that will be returned by cartRepo.DeleteFromCart
func (mmDeleteFromCart *mCartRepoMockDeleteFromCart) Return(err error) *CartRepoMock {
	if mmDeleteFromCart.mock.funcDeleteFromCart != nil {
		mmDeleteFromCart.mock.t.Fatalf("CartRepoMock.DeleteFromCart mock is already set by Set")
	}

	if mmDeleteFromCart.defaultExpectation == nil {
		mmDeleteFromCart.defaultExpectation = &CartRepoMockDeleteFromCartExpectation{mock: mmDeleteFromCart.mock}
	}
	mmDeleteFromCart.defaultExpectation.results = &CartRepoMockDeleteFromCartResults{err}
	mmDeleteFromCart.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmDeleteFromCart.mock
}

// Set uses given function f to mock the cartRepo.DeleteFromCart method
func (mmDeleteFromCart *mCartRepoMockDeleteFromCart) Set(f func(userId int64, skuId int64) (err error)) *CartRepoMock {
	if mmDeleteFromCart.defaultExpectation != nil {
		mmDeleteFromCart.mock.t.Fatalf("Default expectation is already set for the cartRepo.DeleteFromCart method")
	}

	if len(mmDeleteFromCart.expectations) > 0 {
		mmDeleteFromCart.mock.t.Fatalf("Some expectations are already set for the cartRepo.DeleteFromCart method")
	}

	mmDeleteFromCart.mock.funcDeleteFromCart = f
	mmDeleteFromCart.mock.funcDeleteFromCartOrigin = minimock.CallerInfo(1)
	return mmDeleteFromCart.mock
}

// When sets expectation for the cartRepo.DeleteFromCart which will trigger the result defined by the following
// Then helper
func (mmDeleteFromCart *mCartRepoMockDeleteFromCart) When(userId int64, skuId int64) *CartRepoMockDeleteFromCartExpectation {
	if mmDeleteFromCart.mock.funcDeleteFromCart != nil {
		mmDeleteFromCart.mock.t.Fatalf("CartRepoMock.DeleteFromCart mock is already set by Set")
	}

	expectation := &CartRepoMockDeleteFromCartExpectation{
		mock:               mmDeleteFromCart.mock,
		params:             &CartRepoMockDeleteFromCartParams{userId, skuId},
		expectationOrigins: CartRepoMockDeleteFromCartExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmDeleteFromCart.expectations = append(mmDeleteFromCart.expectations, expectation)
	return expectation
}

// Then sets up cartRepo.DeleteFromCart return parameters for the expectation previously defined by the When method
func (e *CartRepoMockDeleteFromCartExpectation) Then(err error) *CartRepoMock {
	e.results = &CartRepoMockDeleteFromCartResults{err}
	return e.mock
}

// Times sets number of times cartRepo.DeleteFromCart should be invoked
func (mmDeleteFromCart *mCartRepoMockDeleteFromCart) Times(n uint64) *mCartRepoMockDeleteFromCart {
	if n == 0 {
		mmDeleteFromCart.mock.t.Fatalf("Times of CartRepoMock.DeleteFromCart mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmDeleteFromCart.expectedInvocations, n)
	mmDeleteFromCart.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmDeleteFromCart
}

func (mmDeleteFromCart *mCartRepoMockDeleteFromCart) invocationsDone() bool {
	if len(mmDeleteFromCart.expectations) == 0 && mmDeleteFromCart.defaultExpectation == nil && mmDeleteFromCart.mock.funcDeleteFromCart == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmDeleteFromCart.mock.afterDeleteFromCartCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmDeleteFromCart.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// DeleteFromCart implements mm_service.cartRepo
func (mmDeleteFromCart *CartRepoMock) DeleteFromCart(userId int64, skuId int64) (err error) {
	mm_atomic.AddUint64(&mmDeleteFromCart.beforeDeleteFromCartCounter, 1)
	defer mm_atomic.AddUint64(&mmDeleteFromCart.afterDeleteFromCartCounter, 1)

	mmDeleteFromCart.t.Helper()

	if mmDeleteFromCart.inspectFuncDeleteFromCart != nil {
		mmDeleteFromCart.inspectFuncDeleteFromCart(userId, skuId)
	}

	mm_params := CartRepoMockDeleteFromCartParams{userId, skuId}

	// Record call args
	mmDeleteFromCart.DeleteFromCartMock.mutex.Lock()
	mmDeleteFromCart.DeleteFromCartMock.callArgs = append(mmDeleteFromCart.DeleteFromCartMock.callArgs, &mm_params)
	mmDeleteFromCart.DeleteFromCartMock.mutex.Unlock()

	for _, e := range mmDeleteFromCart.DeleteFromCartMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmDeleteFromCart.DeleteFromCartMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmDeleteFromCart.DeleteFromCartMock.defaultExpectation.Counter, 1)
		mm_want := mmDeleteFromCart.DeleteFromCartMock.defaultExpectation.params
		mm_want_ptrs := mmDeleteFromCart.DeleteFromCartMock.defaultExpectation.paramPtrs

		mm_got := CartRepoMockDeleteFromCartParams{userId, skuId}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.userId != nil && !minimock.Equal(*mm_want_ptrs.userId, mm_got.userId) {
				mmDeleteFromCart.t.Errorf("CartRepoMock.DeleteFromCart got unexpected parameter userId, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteFromCart.DeleteFromCartMock.defaultExpectation.expectationOrigins.originUserId, *mm_want_ptrs.userId, mm_got.userId, minimock.Diff(*mm_want_ptrs.userId, mm_got.userId))
			}

			if mm_want_ptrs.skuId != nil && !minimock.Equal(*mm_want_ptrs.skuId, mm_got.skuId) {
				mmDeleteFromCart.t.Errorf("CartRepoMock.DeleteFromCart got unexpected parameter skuId, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmDeleteFromCart.DeleteFromCartMock.defaultExpectation.expectationOrigins.originSkuId, *mm_want_ptrs.skuId, mm_got.skuId, minimock.Diff(*mm_want_ptrs.skuId, mm_got.skuId))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmDeleteFromCart.t.Errorf("CartRepoMock.DeleteFromCart got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmDeleteFromCart.DeleteFromCartMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmDeleteFromCart.DeleteFromCartMock.defaultExpectation.results
		if mm_results == nil {
			mmDeleteFromCart.t.Fatal("No results are set for the CartRepoMock.DeleteFromCart")
		}
		return (*mm_results).err
	}
	if mmDeleteFromCart.funcDeleteFromCart != nil {
		return mmDeleteFromCart.funcDeleteFromCart(userId, skuId)
	}
	mmDeleteFromCart.t.Fatalf("Unexpected call to CartRepoMock.DeleteFromCart. %v %v", userId, skuId)
	return
}

// DeleteFromCartAfterCounter returns a count of finished CartRepoMock.DeleteFromCart invocations
func (mmDeleteFromCart *CartRepoMock) DeleteFromCartAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteFromCart.afterDeleteFromCartCounter)
}

// DeleteFromCartBeforeCounter returns a count of CartRepoMock.DeleteFromCart invocations
func (mmDeleteFromCart *CartRepoMock) DeleteFromCartBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmDeleteFromCart.beforeDeleteFromCartCounter)
}

// Calls returns a list of arguments used in each call to CartRepoMock.DeleteFromCart.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmDeleteFromCart *mCartRepoMockDeleteFromCart) Calls() []*CartRepoMockDeleteFromCartParams {
	mmDeleteFromCart.mutex.RLock()

	argCopy := make([]*CartRepoMockDeleteFromCartParams, len(mmDeleteFromCart.callArgs))
	copy(argCopy, mmDeleteFromCart.callArgs)

	mmDeleteFromCart.mutex.RUnlock()

	return argCopy
}

// MinimockDeleteFromCartDone returns true if the count of the DeleteFromCart invocations corresponds
// the number of defined expectations
func (m *CartRepoMock) MinimockDeleteFromCartDone() bool {
	if m.DeleteFromCartMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.DeleteFromCartMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.DeleteFromCartMock.invocationsDone()
}

// MinimockDeleteFromCartInspect logs each unmet expectation
func (m *CartRepoMock) MinimockDeleteFromCartInspect() {
	for _, e := range m.DeleteFromCartMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CartRepoMock.DeleteFromCart at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterDeleteFromCartCounter := mm_atomic.LoadUint64(&m.afterDeleteFromCartCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.DeleteFromCartMock.defaultExpectation != nil && afterDeleteFromCartCounter < 1 {
		if m.DeleteFromCartMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CartRepoMock.DeleteFromCart at\n%s", m.DeleteFromCartMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CartRepoMock.DeleteFromCart at\n%s with params: %#v", m.DeleteFromCartMock.defaultExpectation.expectationOrigins.origin, *m.DeleteFromCartMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcDeleteFromCart != nil && afterDeleteFromCartCounter < 1 {
		m.t.Errorf("Expected call to CartRepoMock.DeleteFromCart at\n%s", m.funcDeleteFromCartOrigin)
	}

	if !m.DeleteFromCartMock.invocationsDone() && afterDeleteFromCartCounter > 0 {
		m.t.Errorf("Expected %d calls to CartRepoMock.DeleteFromCart at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.DeleteFromCartMock.expectedInvocations), m.DeleteFromCartMock.expectedInvocationsOrigin, afterDeleteFromCartCounter)
	}
}

type mCartRepoMockGetItems struct {
	optional           bool
	mock               *CartRepoMock
	defaultExpectation *CartRepoMockGetItemsExpectation
	expectations       []*CartRepoMockGetItemsExpectation

	callArgs []*CartRepoMockGetItemsParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// CartRepoMockGetItemsExpectation specifies expectation struct of the cartRepo.GetItems
type CartRepoMockGetItemsExpectation struct {
	mock               *CartRepoMock
	params             *CartRepoMockGetItemsParams
	paramPtrs          *CartRepoMockGetItemsParamPtrs
	expectationOrigins CartRepoMockGetItemsExpectationOrigins
	results            *CartRepoMockGetItemsResults
	returnOrigin       string
	Counter            uint64
}

// CartRepoMockGetItemsParams contains parameters of the cartRepo.GetItems
type CartRepoMockGetItemsParams struct {
	userId int64
}

// CartRepoMockGetItemsParamPtrs contains pointers to parameters of the cartRepo.GetItems
type CartRepoMockGetItemsParamPtrs struct {
	userId *int64
}

// CartRepoMockGetItemsResults contains results of the cartRepo.GetItems
type CartRepoMockGetItemsResults struct {
	up1 *model.UserData
	err error
}

// CartRepoMockGetItemsOrigins contains origins of expectations of the cartRepo.GetItems
type CartRepoMockGetItemsExpectationOrigins struct {
	origin       string
	originUserId string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetItems *mCartRepoMockGetItems) Optional() *mCartRepoMockGetItems {
	mmGetItems.optional = true
	return mmGetItems
}

// Expect sets up expected params for cartRepo.GetItems
func (mmGetItems *mCartRepoMockGetItems) Expect(userId int64) *mCartRepoMockGetItems {
	if mmGetItems.mock.funcGetItems != nil {
		mmGetItems.mock.t.Fatalf("CartRepoMock.GetItems mock is already set by Set")
	}

	if mmGetItems.defaultExpectation == nil {
		mmGetItems.defaultExpectation = &CartRepoMockGetItemsExpectation{}
	}

	if mmGetItems.defaultExpectation.paramPtrs != nil {
		mmGetItems.mock.t.Fatalf("CartRepoMock.GetItems mock is already set by ExpectParams functions")
	}

	mmGetItems.defaultExpectation.params = &CartRepoMockGetItemsParams{userId}
	mmGetItems.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetItems.expectations {
		if minimock.Equal(e.params, mmGetItems.defaultExpectation.params) {
			mmGetItems.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetItems.defaultExpectation.params)
		}
	}

	return mmGetItems
}

// ExpectUserIdParam1 sets up expected param userId for cartRepo.GetItems
func (mmGetItems *mCartRepoMockGetItems) ExpectUserIdParam1(userId int64) *mCartRepoMockGetItems {
	if mmGetItems.mock.funcGetItems != nil {
		mmGetItems.mock.t.Fatalf("CartRepoMock.GetItems mock is already set by Set")
	}

	if mmGetItems.defaultExpectation == nil {
		mmGetItems.defaultExpectation = &CartRepoMockGetItemsExpectation{}
	}

	if mmGetItems.defaultExpectation.params != nil {
		mmGetItems.mock.t.Fatalf("CartRepoMock.GetItems mock is already set by Expect")
	}

	if mmGetItems.defaultExpectation.paramPtrs == nil {
		mmGetItems.defaultExpectation.paramPtrs = &CartRepoMockGetItemsParamPtrs{}
	}
	mmGetItems.defaultExpectation.paramPtrs.userId = &userId
	mmGetItems.defaultExpectation.expectationOrigins.originUserId = minimock.CallerInfo(1)

	return mmGetItems
}

// Inspect accepts an inspector function that has same arguments as the cartRepo.GetItems
func (mmGetItems *mCartRepoMockGetItems) Inspect(f func(userId int64)) *mCartRepoMockGetItems {
	if mmGetItems.mock.inspectFuncGetItems != nil {
		mmGetItems.mock.t.Fatalf("Inspect function is already set for CartRepoMock.GetItems")
	}

	mmGetItems.mock.inspectFuncGetItems = f

	return mmGetItems
}

// Return sets up results that will be returned by cartRepo.GetItems
func (mmGetItems *mCartRepoMockGetItems) Return(up1 *model.UserData, err error) *CartRepoMock {
	if mmGetItems.mock.funcGetItems != nil {
		mmGetItems.mock.t.Fatalf("CartRepoMock.GetItems mock is already set by Set")
	}

	if mmGetItems.defaultExpectation == nil {
		mmGetItems.defaultExpectation = &CartRepoMockGetItemsExpectation{mock: mmGetItems.mock}
	}
	mmGetItems.defaultExpectation.results = &CartRepoMockGetItemsResults{up1, err}
	mmGetItems.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetItems.mock
}

// Set uses given function f to mock the cartRepo.GetItems method
func (mmGetItems *mCartRepoMockGetItems) Set(f func(userId int64) (up1 *model.UserData, err error)) *CartRepoMock {
	if mmGetItems.defaultExpectation != nil {
		mmGetItems.mock.t.Fatalf("Default expectation is already set for the cartRepo.GetItems method")
	}

	if len(mmGetItems.expectations) > 0 {
		mmGetItems.mock.t.Fatalf("Some expectations are already set for the cartRepo.GetItems method")
	}

	mmGetItems.mock.funcGetItems = f
	mmGetItems.mock.funcGetItemsOrigin = minimock.CallerInfo(1)
	return mmGetItems.mock
}

// When sets expectation for the cartRepo.GetItems which will trigger the result defined by the following
// Then helper
func (mmGetItems *mCartRepoMockGetItems) When(userId int64) *CartRepoMockGetItemsExpectation {
	if mmGetItems.mock.funcGetItems != nil {
		mmGetItems.mock.t.Fatalf("CartRepoMock.GetItems mock is already set by Set")
	}

	expectation := &CartRepoMockGetItemsExpectation{
		mock:               mmGetItems.mock,
		params:             &CartRepoMockGetItemsParams{userId},
		expectationOrigins: CartRepoMockGetItemsExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetItems.expectations = append(mmGetItems.expectations, expectation)
	return expectation
}

// Then sets up cartRepo.GetItems return parameters for the expectation previously defined by the When method
func (e *CartRepoMockGetItemsExpectation) Then(up1 *model.UserData, err error) *CartRepoMock {
	e.results = &CartRepoMockGetItemsResults{up1, err}
	return e.mock
}

// Times sets number of times cartRepo.GetItems should be invoked
func (mmGetItems *mCartRepoMockGetItems) Times(n uint64) *mCartRepoMockGetItems {
	if n == 0 {
		mmGetItems.mock.t.Fatalf("Times of CartRepoMock.GetItems mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetItems.expectedInvocations, n)
	mmGetItems.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetItems
}

func (mmGetItems *mCartRepoMockGetItems) invocationsDone() bool {
	if len(mmGetItems.expectations) == 0 && mmGetItems.defaultExpectation == nil && mmGetItems.mock.funcGetItems == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetItems.mock.afterGetItemsCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetItems.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetItems implements mm_service.cartRepo
func (mmGetItems *CartRepoMock) GetItems(userId int64) (up1 *model.UserData, err error) {
	mm_atomic.AddUint64(&mmGetItems.beforeGetItemsCounter, 1)
	defer mm_atomic.AddUint64(&mmGetItems.afterGetItemsCounter, 1)

	mmGetItems.t.Helper()

	if mmGetItems.inspectFuncGetItems != nil {
		mmGetItems.inspectFuncGetItems(userId)
	}

	mm_params := CartRepoMockGetItemsParams{userId}

	// Record call args
	mmGetItems.GetItemsMock.mutex.Lock()
	mmGetItems.GetItemsMock.callArgs = append(mmGetItems.GetItemsMock.callArgs, &mm_params)
	mmGetItems.GetItemsMock.mutex.Unlock()

	for _, e := range mmGetItems.GetItemsMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.up1, e.results.err
		}
	}

	if mmGetItems.GetItemsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetItems.GetItemsMock.defaultExpectation.Counter, 1)
		mm_want := mmGetItems.GetItemsMock.defaultExpectation.params
		mm_want_ptrs := mmGetItems.GetItemsMock.defaultExpectation.paramPtrs

		mm_got := CartRepoMockGetItemsParams{userId}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.userId != nil && !minimock.Equal(*mm_want_ptrs.userId, mm_got.userId) {
				mmGetItems.t.Errorf("CartRepoMock.GetItems got unexpected parameter userId, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetItems.GetItemsMock.defaultExpectation.expectationOrigins.originUserId, *mm_want_ptrs.userId, mm_got.userId, minimock.Diff(*mm_want_ptrs.userId, mm_got.userId))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetItems.t.Errorf("CartRepoMock.GetItems got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetItems.GetItemsMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetItems.GetItemsMock.defaultExpectation.results
		if mm_results == nil {
			mmGetItems.t.Fatal("No results are set for the CartRepoMock.GetItems")
		}
		return (*mm_results).up1, (*mm_results).err
	}
	if mmGetItems.funcGetItems != nil {
		return mmGetItems.funcGetItems(userId)
	}
	mmGetItems.t.Fatalf("Unexpected call to CartRepoMock.GetItems. %v", userId)
	return
}

// GetItemsAfterCounter returns a count of finished CartRepoMock.GetItems invocations
func (mmGetItems *CartRepoMock) GetItemsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetItems.afterGetItemsCounter)
}

// GetItemsBeforeCounter returns a count of CartRepoMock.GetItems invocations
func (mmGetItems *CartRepoMock) GetItemsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetItems.beforeGetItemsCounter)
}

// Calls returns a list of arguments used in each call to CartRepoMock.GetItems.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetItems *mCartRepoMockGetItems) Calls() []*CartRepoMockGetItemsParams {
	mmGetItems.mutex.RLock()

	argCopy := make([]*CartRepoMockGetItemsParams, len(mmGetItems.callArgs))
	copy(argCopy, mmGetItems.callArgs)

	mmGetItems.mutex.RUnlock()

	return argCopy
}

// MinimockGetItemsDone returns true if the count of the GetItems invocations corresponds
// the number of defined expectations
func (m *CartRepoMock) MinimockGetItemsDone() bool {
	if m.GetItemsMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetItemsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetItemsMock.invocationsDone()
}

// MinimockGetItemsInspect logs each unmet expectation
func (m *CartRepoMock) MinimockGetItemsInspect() {
	for _, e := range m.GetItemsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to CartRepoMock.GetItems at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetItemsCounter := mm_atomic.LoadUint64(&m.afterGetItemsCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetItemsMock.defaultExpectation != nil && afterGetItemsCounter < 1 {
		if m.GetItemsMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to CartRepoMock.GetItems at\n%s", m.GetItemsMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to CartRepoMock.GetItems at\n%s with params: %#v", m.GetItemsMock.defaultExpectation.expectationOrigins.origin, *m.GetItemsMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetItems != nil && afterGetItemsCounter < 1 {
		m.t.Errorf("Expected call to CartRepoMock.GetItems at\n%s", m.funcGetItemsOrigin)
	}

	if !m.GetItemsMock.invocationsDone() && afterGetItemsCounter > 0 {
		m.t.Errorf("Expected %d calls to CartRepoMock.GetItems at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetItemsMock.expectedInvocations), m.GetItemsMock.expectedInvocationsOrigin, afterGetItemsCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *CartRepoMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockAddItemToCartInspect()

			m.MinimockDeleteAllFromCartInspect()

			m.MinimockDeleteFromCartInspect()

			m.MinimockGetItemsInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *CartRepoMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *CartRepoMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockAddItemToCartDone() &&
		m.MinimockDeleteAllFromCartDone() &&
		m.MinimockDeleteFromCartDone() &&
		m.MinimockGetItemsDone()
}
