// Code generated by http://github.com/gojuno/minimock (v3.4.0). DO NOT EDIT.

package mocks

//go:generate minimock -i route256/cart/internal/service.lomsCli -o loms_client_mock.go -n LomsClientMock -p mocks

import (
	"context"
	"route256/cart/internal/model"
	proto "route256/cart/vendor-proto/route256/loms"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// LomsClientMock implements mm_service.lomsCli
type LomsClientMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCancelOrder          func(ctx context.Context, orderId int64) (err error)
	funcCancelOrderOrigin    string
	inspectFuncCancelOrder   func(ctx context.Context, orderId int64)
	afterCancelOrderCounter  uint64
	beforeCancelOrderCounter uint64
	CancelOrderMock          mLomsClientMockCancelOrder

	funcCreateOrder          func(ctx context.Context, userId int64, items []model.OrderItem) (i1 int64, err error)
	funcCreateOrderOrigin    string
	inspectFuncCreateOrder   func(ctx context.Context, userId int64, items []model.OrderItem)
	afterCreateOrderCounter  uint64
	beforeCreateOrderCounter uint64
	CreateOrderMock          mLomsClientMockCreateOrder

	funcGetById          func(ctx context.Context, orderId int64) (gp1 *proto.GetByIdResponse, err error)
	funcGetByIdOrigin    string
	inspectFuncGetById   func(ctx context.Context, orderId int64)
	afterGetByIdCounter  uint64
	beforeGetByIdCounter uint64
	GetByIdMock          mLomsClientMockGetById

	funcGetStockInfos          func(ctx context.Context, skuIds []int64) (gp1 *proto.GetStockInfoResponse, err error)
	funcGetStockInfosOrigin    string
	inspectFuncGetStockInfos   func(ctx context.Context, skuIds []int64)
	afterGetStockInfosCounter  uint64
	beforeGetStockInfosCounter uint64
	GetStockInfosMock          mLomsClientMockGetStockInfos

	funcPayOrder          func(ctx context.Context, orderId int64) (err error)
	funcPayOrderOrigin    string
	inspectFuncPayOrder   func(ctx context.Context, orderId int64)
	afterPayOrderCounter  uint64
	beforePayOrderCounter uint64
	PayOrderMock          mLomsClientMockPayOrder
}

// NewLomsClientMock returns a mock for mm_service.lomsCli
func NewLomsClientMock(t minimock.Tester) *LomsClientMock {
	m := &LomsClientMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CancelOrderMock = mLomsClientMockCancelOrder{mock: m}
	m.CancelOrderMock.callArgs = []*LomsClientMockCancelOrderParams{}

	m.CreateOrderMock = mLomsClientMockCreateOrder{mock: m}
	m.CreateOrderMock.callArgs = []*LomsClientMockCreateOrderParams{}

	m.GetByIdMock = mLomsClientMockGetById{mock: m}
	m.GetByIdMock.callArgs = []*LomsClientMockGetByIdParams{}

	m.GetStockInfosMock = mLomsClientMockGetStockInfos{mock: m}
	m.GetStockInfosMock.callArgs = []*LomsClientMockGetStockInfosParams{}

	m.PayOrderMock = mLomsClientMockPayOrder{mock: m}
	m.PayOrderMock.callArgs = []*LomsClientMockPayOrderParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mLomsClientMockCancelOrder struct {
	optional           bool
	mock               *LomsClientMock
	defaultExpectation *LomsClientMockCancelOrderExpectation
	expectations       []*LomsClientMockCancelOrderExpectation

	callArgs []*LomsClientMockCancelOrderParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LomsClientMockCancelOrderExpectation specifies expectation struct of the lomsCli.CancelOrder
type LomsClientMockCancelOrderExpectation struct {
	mock               *LomsClientMock
	params             *LomsClientMockCancelOrderParams
	paramPtrs          *LomsClientMockCancelOrderParamPtrs
	expectationOrigins LomsClientMockCancelOrderExpectationOrigins
	results            *LomsClientMockCancelOrderResults
	returnOrigin       string
	Counter            uint64
}

// LomsClientMockCancelOrderParams contains parameters of the lomsCli.CancelOrder
type LomsClientMockCancelOrderParams struct {
	ctx     context.Context
	orderId int64
}

// LomsClientMockCancelOrderParamPtrs contains pointers to parameters of the lomsCli.CancelOrder
type LomsClientMockCancelOrderParamPtrs struct {
	ctx     *context.Context
	orderId *int64
}

// LomsClientMockCancelOrderResults contains results of the lomsCli.CancelOrder
type LomsClientMockCancelOrderResults struct {
	err error
}

// LomsClientMockCancelOrderOrigins contains origins of expectations of the lomsCli.CancelOrder
type LomsClientMockCancelOrderExpectationOrigins struct {
	origin        string
	originCtx     string
	originOrderId string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCancelOrder *mLomsClientMockCancelOrder) Optional() *mLomsClientMockCancelOrder {
	mmCancelOrder.optional = true
	return mmCancelOrder
}

// Expect sets up expected params for lomsCli.CancelOrder
func (mmCancelOrder *mLomsClientMockCancelOrder) Expect(ctx context.Context, orderId int64) *mLomsClientMockCancelOrder {
	if mmCancelOrder.mock.funcCancelOrder != nil {
		mmCancelOrder.mock.t.Fatalf("LomsClientMock.CancelOrder mock is already set by Set")
	}

	if mmCancelOrder.defaultExpectation == nil {
		mmCancelOrder.defaultExpectation = &LomsClientMockCancelOrderExpectation{}
	}

	if mmCancelOrder.defaultExpectation.paramPtrs != nil {
		mmCancelOrder.mock.t.Fatalf("LomsClientMock.CancelOrder mock is already set by ExpectParams functions")
	}

	mmCancelOrder.defaultExpectation.params = &LomsClientMockCancelOrderParams{ctx, orderId}
	mmCancelOrder.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCancelOrder.expectations {
		if minimock.Equal(e.params, mmCancelOrder.defaultExpectation.params) {
			mmCancelOrder.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCancelOrder.defaultExpectation.params)
		}
	}

	return mmCancelOrder
}

// ExpectCtxParam1 sets up expected param ctx for lomsCli.CancelOrder
func (mmCancelOrder *mLomsClientMockCancelOrder) ExpectCtxParam1(ctx context.Context) *mLomsClientMockCancelOrder {
	if mmCancelOrder.mock.funcCancelOrder != nil {
		mmCancelOrder.mock.t.Fatalf("LomsClientMock.CancelOrder mock is already set by Set")
	}

	if mmCancelOrder.defaultExpectation == nil {
		mmCancelOrder.defaultExpectation = &LomsClientMockCancelOrderExpectation{}
	}

	if mmCancelOrder.defaultExpectation.params != nil {
		mmCancelOrder.mock.t.Fatalf("LomsClientMock.CancelOrder mock is already set by Expect")
	}

	if mmCancelOrder.defaultExpectation.paramPtrs == nil {
		mmCancelOrder.defaultExpectation.paramPtrs = &LomsClientMockCancelOrderParamPtrs{}
	}
	mmCancelOrder.defaultExpectation.paramPtrs.ctx = &ctx
	mmCancelOrder.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCancelOrder
}

// ExpectOrderIdParam2 sets up expected param orderId for lomsCli.CancelOrder
func (mmCancelOrder *mLomsClientMockCancelOrder) ExpectOrderIdParam2(orderId int64) *mLomsClientMockCancelOrder {
	if mmCancelOrder.mock.funcCancelOrder != nil {
		mmCancelOrder.mock.t.Fatalf("LomsClientMock.CancelOrder mock is already set by Set")
	}

	if mmCancelOrder.defaultExpectation == nil {
		mmCancelOrder.defaultExpectation = &LomsClientMockCancelOrderExpectation{}
	}

	if mmCancelOrder.defaultExpectation.params != nil {
		mmCancelOrder.mock.t.Fatalf("LomsClientMock.CancelOrder mock is already set by Expect")
	}

	if mmCancelOrder.defaultExpectation.paramPtrs == nil {
		mmCancelOrder.defaultExpectation.paramPtrs = &LomsClientMockCancelOrderParamPtrs{}
	}
	mmCancelOrder.defaultExpectation.paramPtrs.orderId = &orderId
	mmCancelOrder.defaultExpectation.expectationOrigins.originOrderId = minimock.CallerInfo(1)

	return mmCancelOrder
}

// Inspect accepts an inspector function that has same arguments as the lomsCli.CancelOrder
func (mmCancelOrder *mLomsClientMockCancelOrder) Inspect(f func(ctx context.Context, orderId int64)) *mLomsClientMockCancelOrder {
	if mmCancelOrder.mock.inspectFuncCancelOrder != nil {
		mmCancelOrder.mock.t.Fatalf("Inspect function is already set for LomsClientMock.CancelOrder")
	}

	mmCancelOrder.mock.inspectFuncCancelOrder = f

	return mmCancelOrder
}

// Return sets up results that will be returned by lomsCli.CancelOrder
func (mmCancelOrder *mLomsClientMockCancelOrder) Return(err error) *LomsClientMock {
	if mmCancelOrder.mock.funcCancelOrder != nil {
		mmCancelOrder.mock.t.Fatalf("LomsClientMock.CancelOrder mock is already set by Set")
	}

	if mmCancelOrder.defaultExpectation == nil {
		mmCancelOrder.defaultExpectation = &LomsClientMockCancelOrderExpectation{mock: mmCancelOrder.mock}
	}
	mmCancelOrder.defaultExpectation.results = &LomsClientMockCancelOrderResults{err}
	mmCancelOrder.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCancelOrder.mock
}

// Set uses given function f to mock the lomsCli.CancelOrder method
func (mmCancelOrder *mLomsClientMockCancelOrder) Set(f func(ctx context.Context, orderId int64) (err error)) *LomsClientMock {
	if mmCancelOrder.defaultExpectation != nil {
		mmCancelOrder.mock.t.Fatalf("Default expectation is already set for the lomsCli.CancelOrder method")
	}

	if len(mmCancelOrder.expectations) > 0 {
		mmCancelOrder.mock.t.Fatalf("Some expectations are already set for the lomsCli.CancelOrder method")
	}

	mmCancelOrder.mock.funcCancelOrder = f
	mmCancelOrder.mock.funcCancelOrderOrigin = minimock.CallerInfo(1)
	return mmCancelOrder.mock
}

// When sets expectation for the lomsCli.CancelOrder which will trigger the result defined by the following
// Then helper
func (mmCancelOrder *mLomsClientMockCancelOrder) When(ctx context.Context, orderId int64) *LomsClientMockCancelOrderExpectation {
	if mmCancelOrder.mock.funcCancelOrder != nil {
		mmCancelOrder.mock.t.Fatalf("LomsClientMock.CancelOrder mock is already set by Set")
	}

	expectation := &LomsClientMockCancelOrderExpectation{
		mock:               mmCancelOrder.mock,
		params:             &LomsClientMockCancelOrderParams{ctx, orderId},
		expectationOrigins: LomsClientMockCancelOrderExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCancelOrder.expectations = append(mmCancelOrder.expectations, expectation)
	return expectation
}

// Then sets up lomsCli.CancelOrder return parameters for the expectation previously defined by the When method
func (e *LomsClientMockCancelOrderExpectation) Then(err error) *LomsClientMock {
	e.results = &LomsClientMockCancelOrderResults{err}
	return e.mock
}

// Times sets number of times lomsCli.CancelOrder should be invoked
func (mmCancelOrder *mLomsClientMockCancelOrder) Times(n uint64) *mLomsClientMockCancelOrder {
	if n == 0 {
		mmCancelOrder.mock.t.Fatalf("Times of LomsClientMock.CancelOrder mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCancelOrder.expectedInvocations, n)
	mmCancelOrder.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCancelOrder
}

func (mmCancelOrder *mLomsClientMockCancelOrder) invocationsDone() bool {
	if len(mmCancelOrder.expectations) == 0 && mmCancelOrder.defaultExpectation == nil && mmCancelOrder.mock.funcCancelOrder == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCancelOrder.mock.afterCancelOrderCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCancelOrder.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CancelOrder implements mm_service.lomsCli
func (mmCancelOrder *LomsClientMock) CancelOrder(ctx context.Context, orderId int64) (err error) {
	mm_atomic.AddUint64(&mmCancelOrder.beforeCancelOrderCounter, 1)
	defer mm_atomic.AddUint64(&mmCancelOrder.afterCancelOrderCounter, 1)

	mmCancelOrder.t.Helper()

	if mmCancelOrder.inspectFuncCancelOrder != nil {
		mmCancelOrder.inspectFuncCancelOrder(ctx, orderId)
	}

	mm_params := LomsClientMockCancelOrderParams{ctx, orderId}

	// Record call args
	mmCancelOrder.CancelOrderMock.mutex.Lock()
	mmCancelOrder.CancelOrderMock.callArgs = append(mmCancelOrder.CancelOrderMock.callArgs, &mm_params)
	mmCancelOrder.CancelOrderMock.mutex.Unlock()

	for _, e := range mmCancelOrder.CancelOrderMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmCancelOrder.CancelOrderMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCancelOrder.CancelOrderMock.defaultExpectation.Counter, 1)
		mm_want := mmCancelOrder.CancelOrderMock.defaultExpectation.params
		mm_want_ptrs := mmCancelOrder.CancelOrderMock.defaultExpectation.paramPtrs

		mm_got := LomsClientMockCancelOrderParams{ctx, orderId}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCancelOrder.t.Errorf("LomsClientMock.CancelOrder got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCancelOrder.CancelOrderMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.orderId != nil && !minimock.Equal(*mm_want_ptrs.orderId, mm_got.orderId) {
				mmCancelOrder.t.Errorf("LomsClientMock.CancelOrder got unexpected parameter orderId, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCancelOrder.CancelOrderMock.defaultExpectation.expectationOrigins.originOrderId, *mm_want_ptrs.orderId, mm_got.orderId, minimock.Diff(*mm_want_ptrs.orderId, mm_got.orderId))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCancelOrder.t.Errorf("LomsClientMock.CancelOrder got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCancelOrder.CancelOrderMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCancelOrder.CancelOrderMock.defaultExpectation.results
		if mm_results == nil {
			mmCancelOrder.t.Fatal("No results are set for the LomsClientMock.CancelOrder")
		}
		return (*mm_results).err
	}
	if mmCancelOrder.funcCancelOrder != nil {
		return mmCancelOrder.funcCancelOrder(ctx, orderId)
	}
	mmCancelOrder.t.Fatalf("Unexpected call to LomsClientMock.CancelOrder. %v %v", ctx, orderId)
	return
}

// CancelOrderAfterCounter returns a count of finished LomsClientMock.CancelOrder invocations
func (mmCancelOrder *LomsClientMock) CancelOrderAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCancelOrder.afterCancelOrderCounter)
}

// CancelOrderBeforeCounter returns a count of LomsClientMock.CancelOrder invocations
func (mmCancelOrder *LomsClientMock) CancelOrderBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCancelOrder.beforeCancelOrderCounter)
}

// Calls returns a list of arguments used in each call to LomsClientMock.CancelOrder.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCancelOrder *mLomsClientMockCancelOrder) Calls() []*LomsClientMockCancelOrderParams {
	mmCancelOrder.mutex.RLock()

	argCopy := make([]*LomsClientMockCancelOrderParams, len(mmCancelOrder.callArgs))
	copy(argCopy, mmCancelOrder.callArgs)

	mmCancelOrder.mutex.RUnlock()

	return argCopy
}

// MinimockCancelOrderDone returns true if the count of the CancelOrder invocations corresponds
// the number of defined expectations
func (m *LomsClientMock) MinimockCancelOrderDone() bool {
	if m.CancelOrderMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CancelOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CancelOrderMock.invocationsDone()
}

// MinimockCancelOrderInspect logs each unmet expectation
func (m *LomsClientMock) MinimockCancelOrderInspect() {
	for _, e := range m.CancelOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LomsClientMock.CancelOrder at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCancelOrderCounter := mm_atomic.LoadUint64(&m.afterCancelOrderCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CancelOrderMock.defaultExpectation != nil && afterCancelOrderCounter < 1 {
		if m.CancelOrderMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LomsClientMock.CancelOrder at\n%s", m.CancelOrderMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LomsClientMock.CancelOrder at\n%s with params: %#v", m.CancelOrderMock.defaultExpectation.expectationOrigins.origin, *m.CancelOrderMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCancelOrder != nil && afterCancelOrderCounter < 1 {
		m.t.Errorf("Expected call to LomsClientMock.CancelOrder at\n%s", m.funcCancelOrderOrigin)
	}

	if !m.CancelOrderMock.invocationsDone() && afterCancelOrderCounter > 0 {
		m.t.Errorf("Expected %d calls to LomsClientMock.CancelOrder at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CancelOrderMock.expectedInvocations), m.CancelOrderMock.expectedInvocationsOrigin, afterCancelOrderCounter)
	}
}

type mLomsClientMockCreateOrder struct {
	optional           bool
	mock               *LomsClientMock
	defaultExpectation *LomsClientMockCreateOrderExpectation
	expectations       []*LomsClientMockCreateOrderExpectation

	callArgs []*LomsClientMockCreateOrderParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LomsClientMockCreateOrderExpectation specifies expectation struct of the lomsCli.CreateOrder
type LomsClientMockCreateOrderExpectation struct {
	mock               *LomsClientMock
	params             *LomsClientMockCreateOrderParams
	paramPtrs          *LomsClientMockCreateOrderParamPtrs
	expectationOrigins LomsClientMockCreateOrderExpectationOrigins
	results            *LomsClientMockCreateOrderResults
	returnOrigin       string
	Counter            uint64
}

// LomsClientMockCreateOrderParams contains parameters of the lomsCli.CreateOrder
type LomsClientMockCreateOrderParams struct {
	ctx    context.Context
	userId int64
	items  []model.OrderItem
}

// LomsClientMockCreateOrderParamPtrs contains pointers to parameters of the lomsCli.CreateOrder
type LomsClientMockCreateOrderParamPtrs struct {
	ctx    *context.Context
	userId *int64
	items  *[]model.OrderItem
}

// LomsClientMockCreateOrderResults contains results of the lomsCli.CreateOrder
type LomsClientMockCreateOrderResults struct {
	i1  int64
	err error
}

// LomsClientMockCreateOrderOrigins contains origins of expectations of the lomsCli.CreateOrder
type LomsClientMockCreateOrderExpectationOrigins struct {
	origin       string
	originCtx    string
	originUserId string
	originItems  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateOrder *mLomsClientMockCreateOrder) Optional() *mLomsClientMockCreateOrder {
	mmCreateOrder.optional = true
	return mmCreateOrder
}

// Expect sets up expected params for lomsCli.CreateOrder
func (mmCreateOrder *mLomsClientMockCreateOrder) Expect(ctx context.Context, userId int64, items []model.OrderItem) *mLomsClientMockCreateOrder {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LomsClientMock.CreateOrder mock is already set by Set")
	}

	if mmCreateOrder.defaultExpectation == nil {
		mmCreateOrder.defaultExpectation = &LomsClientMockCreateOrderExpectation{}
	}

	if mmCreateOrder.defaultExpectation.paramPtrs != nil {
		mmCreateOrder.mock.t.Fatalf("LomsClientMock.CreateOrder mock is already set by ExpectParams functions")
	}

	mmCreateOrder.defaultExpectation.params = &LomsClientMockCreateOrderParams{ctx, userId, items}
	mmCreateOrder.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateOrder.expectations {
		if minimock.Equal(e.params, mmCreateOrder.defaultExpectation.params) {
			mmCreateOrder.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateOrder.defaultExpectation.params)
		}
	}

	return mmCreateOrder
}

// ExpectCtxParam1 sets up expected param ctx for lomsCli.CreateOrder
func (mmCreateOrder *mLomsClientMockCreateOrder) ExpectCtxParam1(ctx context.Context) *mLomsClientMockCreateOrder {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LomsClientMock.CreateOrder mock is already set by Set")
	}

	if mmCreateOrder.defaultExpectation == nil {
		mmCreateOrder.defaultExpectation = &LomsClientMockCreateOrderExpectation{}
	}

	if mmCreateOrder.defaultExpectation.params != nil {
		mmCreateOrder.mock.t.Fatalf("LomsClientMock.CreateOrder mock is already set by Expect")
	}

	if mmCreateOrder.defaultExpectation.paramPtrs == nil {
		mmCreateOrder.defaultExpectation.paramPtrs = &LomsClientMockCreateOrderParamPtrs{}
	}
	mmCreateOrder.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreateOrder.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreateOrder
}

// ExpectUserIdParam2 sets up expected param userId for lomsCli.CreateOrder
func (mmCreateOrder *mLomsClientMockCreateOrder) ExpectUserIdParam2(userId int64) *mLomsClientMockCreateOrder {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LomsClientMock.CreateOrder mock is already set by Set")
	}

	if mmCreateOrder.defaultExpectation == nil {
		mmCreateOrder.defaultExpectation = &LomsClientMockCreateOrderExpectation{}
	}

	if mmCreateOrder.defaultExpectation.params != nil {
		mmCreateOrder.mock.t.Fatalf("LomsClientMock.CreateOrder mock is already set by Expect")
	}

	if mmCreateOrder.defaultExpectation.paramPtrs == nil {
		mmCreateOrder.defaultExpectation.paramPtrs = &LomsClientMockCreateOrderParamPtrs{}
	}
	mmCreateOrder.defaultExpectation.paramPtrs.userId = &userId
	mmCreateOrder.defaultExpectation.expectationOrigins.originUserId = minimock.CallerInfo(1)

	return mmCreateOrder
}

// ExpectItemsParam3 sets up expected param items for lomsCli.CreateOrder
func (mmCreateOrder *mLomsClientMockCreateOrder) ExpectItemsParam3(items []model.OrderItem) *mLomsClientMockCreateOrder {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LomsClientMock.CreateOrder mock is already set by Set")
	}

	if mmCreateOrder.defaultExpectation == nil {
		mmCreateOrder.defaultExpectation = &LomsClientMockCreateOrderExpectation{}
	}

	if mmCreateOrder.defaultExpectation.params != nil {
		mmCreateOrder.mock.t.Fatalf("LomsClientMock.CreateOrder mock is already set by Expect")
	}

	if mmCreateOrder.defaultExpectation.paramPtrs == nil {
		mmCreateOrder.defaultExpectation.paramPtrs = &LomsClientMockCreateOrderParamPtrs{}
	}
	mmCreateOrder.defaultExpectation.paramPtrs.items = &items
	mmCreateOrder.defaultExpectation.expectationOrigins.originItems = minimock.CallerInfo(1)

	return mmCreateOrder
}

// Inspect accepts an inspector function that has same arguments as the lomsCli.CreateOrder
func (mmCreateOrder *mLomsClientMockCreateOrder) Inspect(f func(ctx context.Context, userId int64, items []model.OrderItem)) *mLomsClientMockCreateOrder {
	if mmCreateOrder.mock.inspectFuncCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("Inspect function is already set for LomsClientMock.CreateOrder")
	}

	mmCreateOrder.mock.inspectFuncCreateOrder = f

	return mmCreateOrder
}

// Return sets up results that will be returned by lomsCli.CreateOrder
func (mmCreateOrder *mLomsClientMockCreateOrder) Return(i1 int64, err error) *LomsClientMock {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LomsClientMock.CreateOrder mock is already set by Set")
	}

	if mmCreateOrder.defaultExpectation == nil {
		mmCreateOrder.defaultExpectation = &LomsClientMockCreateOrderExpectation{mock: mmCreateOrder.mock}
	}
	mmCreateOrder.defaultExpectation.results = &LomsClientMockCreateOrderResults{i1, err}
	mmCreateOrder.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateOrder.mock
}

// Set uses given function f to mock the lomsCli.CreateOrder method
func (mmCreateOrder *mLomsClientMockCreateOrder) Set(f func(ctx context.Context, userId int64, items []model.OrderItem) (i1 int64, err error)) *LomsClientMock {
	if mmCreateOrder.defaultExpectation != nil {
		mmCreateOrder.mock.t.Fatalf("Default expectation is already set for the lomsCli.CreateOrder method")
	}

	if len(mmCreateOrder.expectations) > 0 {
		mmCreateOrder.mock.t.Fatalf("Some expectations are already set for the lomsCli.CreateOrder method")
	}

	mmCreateOrder.mock.funcCreateOrder = f
	mmCreateOrder.mock.funcCreateOrderOrigin = minimock.CallerInfo(1)
	return mmCreateOrder.mock
}

// When sets expectation for the lomsCli.CreateOrder which will trigger the result defined by the following
// Then helper
func (mmCreateOrder *mLomsClientMockCreateOrder) When(ctx context.Context, userId int64, items []model.OrderItem) *LomsClientMockCreateOrderExpectation {
	if mmCreateOrder.mock.funcCreateOrder != nil {
		mmCreateOrder.mock.t.Fatalf("LomsClientMock.CreateOrder mock is already set by Set")
	}

	expectation := &LomsClientMockCreateOrderExpectation{
		mock:               mmCreateOrder.mock,
		params:             &LomsClientMockCreateOrderParams{ctx, userId, items},
		expectationOrigins: LomsClientMockCreateOrderExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateOrder.expectations = append(mmCreateOrder.expectations, expectation)
	return expectation
}

// Then sets up lomsCli.CreateOrder return parameters for the expectation previously defined by the When method
func (e *LomsClientMockCreateOrderExpectation) Then(i1 int64, err error) *LomsClientMock {
	e.results = &LomsClientMockCreateOrderResults{i1, err}
	return e.mock
}

// Times sets number of times lomsCli.CreateOrder should be invoked
func (mmCreateOrder *mLomsClientMockCreateOrder) Times(n uint64) *mLomsClientMockCreateOrder {
	if n == 0 {
		mmCreateOrder.mock.t.Fatalf("Times of LomsClientMock.CreateOrder mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateOrder.expectedInvocations, n)
	mmCreateOrder.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateOrder
}

func (mmCreateOrder *mLomsClientMockCreateOrder) invocationsDone() bool {
	if len(mmCreateOrder.expectations) == 0 && mmCreateOrder.defaultExpectation == nil && mmCreateOrder.mock.funcCreateOrder == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateOrder.mock.afterCreateOrderCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateOrder.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateOrder implements mm_service.lomsCli
func (mmCreateOrder *LomsClientMock) CreateOrder(ctx context.Context, userId int64, items []model.OrderItem) (i1 int64, err error) {
	mm_atomic.AddUint64(&mmCreateOrder.beforeCreateOrderCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateOrder.afterCreateOrderCounter, 1)

	mmCreateOrder.t.Helper()

	if mmCreateOrder.inspectFuncCreateOrder != nil {
		mmCreateOrder.inspectFuncCreateOrder(ctx, userId, items)
	}

	mm_params := LomsClientMockCreateOrderParams{ctx, userId, items}

	// Record call args
	mmCreateOrder.CreateOrderMock.mutex.Lock()
	mmCreateOrder.CreateOrderMock.callArgs = append(mmCreateOrder.CreateOrderMock.callArgs, &mm_params)
	mmCreateOrder.CreateOrderMock.mutex.Unlock()

	for _, e := range mmCreateOrder.CreateOrderMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmCreateOrder.CreateOrderMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateOrder.CreateOrderMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateOrder.CreateOrderMock.defaultExpectation.params
		mm_want_ptrs := mmCreateOrder.CreateOrderMock.defaultExpectation.paramPtrs

		mm_got := LomsClientMockCreateOrderParams{ctx, userId, items}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreateOrder.t.Errorf("LomsClientMock.CreateOrder got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateOrder.CreateOrderMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.userId != nil && !minimock.Equal(*mm_want_ptrs.userId, mm_got.userId) {
				mmCreateOrder.t.Errorf("LomsClientMock.CreateOrder got unexpected parameter userId, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateOrder.CreateOrderMock.defaultExpectation.expectationOrigins.originUserId, *mm_want_ptrs.userId, mm_got.userId, minimock.Diff(*mm_want_ptrs.userId, mm_got.userId))
			}

			if mm_want_ptrs.items != nil && !minimock.Equal(*mm_want_ptrs.items, mm_got.items) {
				mmCreateOrder.t.Errorf("LomsClientMock.CreateOrder got unexpected parameter items, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateOrder.CreateOrderMock.defaultExpectation.expectationOrigins.originItems, *mm_want_ptrs.items, mm_got.items, minimock.Diff(*mm_want_ptrs.items, mm_got.items))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateOrder.t.Errorf("LomsClientMock.CreateOrder got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateOrder.CreateOrderMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateOrder.CreateOrderMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateOrder.t.Fatal("No results are set for the LomsClientMock.CreateOrder")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmCreateOrder.funcCreateOrder != nil {
		return mmCreateOrder.funcCreateOrder(ctx, userId, items)
	}
	mmCreateOrder.t.Fatalf("Unexpected call to LomsClientMock.CreateOrder. %v %v %v", ctx, userId, items)
	return
}

// CreateOrderAfterCounter returns a count of finished LomsClientMock.CreateOrder invocations
func (mmCreateOrder *LomsClientMock) CreateOrderAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateOrder.afterCreateOrderCounter)
}

// CreateOrderBeforeCounter returns a count of LomsClientMock.CreateOrder invocations
func (mmCreateOrder *LomsClientMock) CreateOrderBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateOrder.beforeCreateOrderCounter)
}

// Calls returns a list of arguments used in each call to LomsClientMock.CreateOrder.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateOrder *mLomsClientMockCreateOrder) Calls() []*LomsClientMockCreateOrderParams {
	mmCreateOrder.mutex.RLock()

	argCopy := make([]*LomsClientMockCreateOrderParams, len(mmCreateOrder.callArgs))
	copy(argCopy, mmCreateOrder.callArgs)

	mmCreateOrder.mutex.RUnlock()

	return argCopy
}

// MinimockCreateOrderDone returns true if the count of the CreateOrder invocations corresponds
// the number of defined expectations
func (m *LomsClientMock) MinimockCreateOrderDone() bool {
	if m.CreateOrderMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateOrderMock.invocationsDone()
}

// MinimockCreateOrderInspect logs each unmet expectation
func (m *LomsClientMock) MinimockCreateOrderInspect() {
	for _, e := range m.CreateOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LomsClientMock.CreateOrder at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateOrderCounter := mm_atomic.LoadUint64(&m.afterCreateOrderCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateOrderMock.defaultExpectation != nil && afterCreateOrderCounter < 1 {
		if m.CreateOrderMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LomsClientMock.CreateOrder at\n%s", m.CreateOrderMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LomsClientMock.CreateOrder at\n%s with params: %#v", m.CreateOrderMock.defaultExpectation.expectationOrigins.origin, *m.CreateOrderMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateOrder != nil && afterCreateOrderCounter < 1 {
		m.t.Errorf("Expected call to LomsClientMock.CreateOrder at\n%s", m.funcCreateOrderOrigin)
	}

	if !m.CreateOrderMock.invocationsDone() && afterCreateOrderCounter > 0 {
		m.t.Errorf("Expected %d calls to LomsClientMock.CreateOrder at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateOrderMock.expectedInvocations), m.CreateOrderMock.expectedInvocationsOrigin, afterCreateOrderCounter)
	}
}

type mLomsClientMockGetById struct {
	optional           bool
	mock               *LomsClientMock
	defaultExpectation *LomsClientMockGetByIdExpectation
	expectations       []*LomsClientMockGetByIdExpectation

	callArgs []*LomsClientMockGetByIdParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LomsClientMockGetByIdExpectation specifies expectation struct of the lomsCli.GetById
type LomsClientMockGetByIdExpectation struct {
	mock               *LomsClientMock
	params             *LomsClientMockGetByIdParams
	paramPtrs          *LomsClientMockGetByIdParamPtrs
	expectationOrigins LomsClientMockGetByIdExpectationOrigins
	results            *LomsClientMockGetByIdResults
	returnOrigin       string
	Counter            uint64
}

// LomsClientMockGetByIdParams contains parameters of the lomsCli.GetById
type LomsClientMockGetByIdParams struct {
	ctx     context.Context
	orderId int64
}

// LomsClientMockGetByIdParamPtrs contains pointers to parameters of the lomsCli.GetById
type LomsClientMockGetByIdParamPtrs struct {
	ctx     *context.Context
	orderId *int64
}

// LomsClientMockGetByIdResults contains results of the lomsCli.GetById
type LomsClientMockGetByIdResults struct {
	gp1 *proto.GetByIdResponse
	err error
}

// LomsClientMockGetByIdOrigins contains origins of expectations of the lomsCli.GetById
type LomsClientMockGetByIdExpectationOrigins struct {
	origin        string
	originCtx     string
	originOrderId string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetById *mLomsClientMockGetById) Optional() *mLomsClientMockGetById {
	mmGetById.optional = true
	return mmGetById
}

// Expect sets up expected params for lomsCli.GetById
func (mmGetById *mLomsClientMockGetById) Expect(ctx context.Context, orderId int64) *mLomsClientMockGetById {
	if mmGetById.mock.funcGetById != nil {
		mmGetById.mock.t.Fatalf("LomsClientMock.GetById mock is already set by Set")
	}

	if mmGetById.defaultExpectation == nil {
		mmGetById.defaultExpectation = &LomsClientMockGetByIdExpectation{}
	}

	if mmGetById.defaultExpectation.paramPtrs != nil {
		mmGetById.mock.t.Fatalf("LomsClientMock.GetById mock is already set by ExpectParams functions")
	}

	mmGetById.defaultExpectation.params = &LomsClientMockGetByIdParams{ctx, orderId}
	mmGetById.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetById.expectations {
		if minimock.Equal(e.params, mmGetById.defaultExpectation.params) {
			mmGetById.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetById.defaultExpectation.params)
		}
	}

	return mmGetById
}

// ExpectCtxParam1 sets up expected param ctx for lomsCli.GetById
func (mmGetById *mLomsClientMockGetById) ExpectCtxParam1(ctx context.Context) *mLomsClientMockGetById {
	if mmGetById.mock.funcGetById != nil {
		mmGetById.mock.t.Fatalf("LomsClientMock.GetById mock is already set by Set")
	}

	if mmGetById.defaultExpectation == nil {
		mmGetById.defaultExpectation = &LomsClientMockGetByIdExpectation{}
	}

	if mmGetById.defaultExpectation.params != nil {
		mmGetById.mock.t.Fatalf("LomsClientMock.GetById mock is already set by Expect")
	}

	if mmGetById.defaultExpectation.paramPtrs == nil {
		mmGetById.defaultExpectation.paramPtrs = &LomsClientMockGetByIdParamPtrs{}
	}
	mmGetById.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetById.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetById
}

// ExpectOrderIdParam2 sets up expected param orderId for lomsCli.GetById
func (mmGetById *mLomsClientMockGetById) ExpectOrderIdParam2(orderId int64) *mLomsClientMockGetById {
	if mmGetById.mock.funcGetById != nil {
		mmGetById.mock.t.Fatalf("LomsClientMock.GetById mock is already set by Set")
	}

	if mmGetById.defaultExpectation == nil {
		mmGetById.defaultExpectation = &LomsClientMockGetByIdExpectation{}
	}

	if mmGetById.defaultExpectation.params != nil {
		mmGetById.mock.t.Fatalf("LomsClientMock.GetById mock is already set by Expect")
	}

	if mmGetById.defaultExpectation.paramPtrs == nil {
		mmGetById.defaultExpectation.paramPtrs = &LomsClientMockGetByIdParamPtrs{}
	}
	mmGetById.defaultExpectation.paramPtrs.orderId = &orderId
	mmGetById.defaultExpectation.expectationOrigins.originOrderId = minimock.CallerInfo(1)

	return mmGetById
}

// Inspect accepts an inspector function that has same arguments as the lomsCli.GetById
func (mmGetById *mLomsClientMockGetById) Inspect(f func(ctx context.Context, orderId int64)) *mLomsClientMockGetById {
	if mmGetById.mock.inspectFuncGetById != nil {
		mmGetById.mock.t.Fatalf("Inspect function is already set for LomsClientMock.GetById")
	}

	mmGetById.mock.inspectFuncGetById = f

	return mmGetById
}

// Return sets up results that will be returned by lomsCli.GetById
func (mmGetById *mLomsClientMockGetById) Return(gp1 *proto.GetByIdResponse, err error) *LomsClientMock {
	if mmGetById.mock.funcGetById != nil {
		mmGetById.mock.t.Fatalf("LomsClientMock.GetById mock is already set by Set")
	}

	if mmGetById.defaultExpectation == nil {
		mmGetById.defaultExpectation = &LomsClientMockGetByIdExpectation{mock: mmGetById.mock}
	}
	mmGetById.defaultExpectation.results = &LomsClientMockGetByIdResults{gp1, err}
	mmGetById.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetById.mock
}

// Set uses given function f to mock the lomsCli.GetById method
func (mmGetById *mLomsClientMockGetById) Set(f func(ctx context.Context, orderId int64) (gp1 *proto.GetByIdResponse, err error)) *LomsClientMock {
	if mmGetById.defaultExpectation != nil {
		mmGetById.mock.t.Fatalf("Default expectation is already set for the lomsCli.GetById method")
	}

	if len(mmGetById.expectations) > 0 {
		mmGetById.mock.t.Fatalf("Some expectations are already set for the lomsCli.GetById method")
	}

	mmGetById.mock.funcGetById = f
	mmGetById.mock.funcGetByIdOrigin = minimock.CallerInfo(1)
	return mmGetById.mock
}

// When sets expectation for the lomsCli.GetById which will trigger the result defined by the following
// Then helper
func (mmGetById *mLomsClientMockGetById) When(ctx context.Context, orderId int64) *LomsClientMockGetByIdExpectation {
	if mmGetById.mock.funcGetById != nil {
		mmGetById.mock.t.Fatalf("LomsClientMock.GetById mock is already set by Set")
	}

	expectation := &LomsClientMockGetByIdExpectation{
		mock:               mmGetById.mock,
		params:             &LomsClientMockGetByIdParams{ctx, orderId},
		expectationOrigins: LomsClientMockGetByIdExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetById.expectations = append(mmGetById.expectations, expectation)
	return expectation
}

// Then sets up lomsCli.GetById return parameters for the expectation previously defined by the When method
func (e *LomsClientMockGetByIdExpectation) Then(gp1 *proto.GetByIdResponse, err error) *LomsClientMock {
	e.results = &LomsClientMockGetByIdResults{gp1, err}
	return e.mock
}

// Times sets number of times lomsCli.GetById should be invoked
func (mmGetById *mLomsClientMockGetById) Times(n uint64) *mLomsClientMockGetById {
	if n == 0 {
		mmGetById.mock.t.Fatalf("Times of LomsClientMock.GetById mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetById.expectedInvocations, n)
	mmGetById.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetById
}

func (mmGetById *mLomsClientMockGetById) invocationsDone() bool {
	if len(mmGetById.expectations) == 0 && mmGetById.defaultExpectation == nil && mmGetById.mock.funcGetById == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetById.mock.afterGetByIdCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetById.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetById implements mm_service.lomsCli
func (mmGetById *LomsClientMock) GetById(ctx context.Context, orderId int64) (gp1 *proto.GetByIdResponse, err error) {
	mm_atomic.AddUint64(&mmGetById.beforeGetByIdCounter, 1)
	defer mm_atomic.AddUint64(&mmGetById.afterGetByIdCounter, 1)

	mmGetById.t.Helper()

	if mmGetById.inspectFuncGetById != nil {
		mmGetById.inspectFuncGetById(ctx, orderId)
	}

	mm_params := LomsClientMockGetByIdParams{ctx, orderId}

	// Record call args
	mmGetById.GetByIdMock.mutex.Lock()
	mmGetById.GetByIdMock.callArgs = append(mmGetById.GetByIdMock.callArgs, &mm_params)
	mmGetById.GetByIdMock.mutex.Unlock()

	for _, e := range mmGetById.GetByIdMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.gp1, e.results.err
		}
	}

	if mmGetById.GetByIdMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetById.GetByIdMock.defaultExpectation.Counter, 1)
		mm_want := mmGetById.GetByIdMock.defaultExpectation.params
		mm_want_ptrs := mmGetById.GetByIdMock.defaultExpectation.paramPtrs

		mm_got := LomsClientMockGetByIdParams{ctx, orderId}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetById.t.Errorf("LomsClientMock.GetById got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetById.GetByIdMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.orderId != nil && !minimock.Equal(*mm_want_ptrs.orderId, mm_got.orderId) {
				mmGetById.t.Errorf("LomsClientMock.GetById got unexpected parameter orderId, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetById.GetByIdMock.defaultExpectation.expectationOrigins.originOrderId, *mm_want_ptrs.orderId, mm_got.orderId, minimock.Diff(*mm_want_ptrs.orderId, mm_got.orderId))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetById.t.Errorf("LomsClientMock.GetById got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetById.GetByIdMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetById.GetByIdMock.defaultExpectation.results
		if mm_results == nil {
			mmGetById.t.Fatal("No results are set for the LomsClientMock.GetById")
		}
		return (*mm_results).gp1, (*mm_results).err
	}
	if mmGetById.funcGetById != nil {
		return mmGetById.funcGetById(ctx, orderId)
	}
	mmGetById.t.Fatalf("Unexpected call to LomsClientMock.GetById. %v %v", ctx, orderId)
	return
}

// GetByIdAfterCounter returns a count of finished LomsClientMock.GetById invocations
func (mmGetById *LomsClientMock) GetByIdAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetById.afterGetByIdCounter)
}

// GetByIdBeforeCounter returns a count of LomsClientMock.GetById invocations
func (mmGetById *LomsClientMock) GetByIdBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetById.beforeGetByIdCounter)
}

// Calls returns a list of arguments used in each call to LomsClientMock.GetById.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetById *mLomsClientMockGetById) Calls() []*LomsClientMockGetByIdParams {
	mmGetById.mutex.RLock()

	argCopy := make([]*LomsClientMockGetByIdParams, len(mmGetById.callArgs))
	copy(argCopy, mmGetById.callArgs)

	mmGetById.mutex.RUnlock()

	return argCopy
}

// MinimockGetByIdDone returns true if the count of the GetById invocations corresponds
// the number of defined expectations
func (m *LomsClientMock) MinimockGetByIdDone() bool {
	if m.GetByIdMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetByIdMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetByIdMock.invocationsDone()
}

// MinimockGetByIdInspect logs each unmet expectation
func (m *LomsClientMock) MinimockGetByIdInspect() {
	for _, e := range m.GetByIdMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LomsClientMock.GetById at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetByIdCounter := mm_atomic.LoadUint64(&m.afterGetByIdCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetByIdMock.defaultExpectation != nil && afterGetByIdCounter < 1 {
		if m.GetByIdMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LomsClientMock.GetById at\n%s", m.GetByIdMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LomsClientMock.GetById at\n%s with params: %#v", m.GetByIdMock.defaultExpectation.expectationOrigins.origin, *m.GetByIdMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetById != nil && afterGetByIdCounter < 1 {
		m.t.Errorf("Expected call to LomsClientMock.GetById at\n%s", m.funcGetByIdOrigin)
	}

	if !m.GetByIdMock.invocationsDone() && afterGetByIdCounter > 0 {
		m.t.Errorf("Expected %d calls to LomsClientMock.GetById at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetByIdMock.expectedInvocations), m.GetByIdMock.expectedInvocationsOrigin, afterGetByIdCounter)
	}
}

type mLomsClientMockGetStockInfos struct {
	optional           bool
	mock               *LomsClientMock
	defaultExpectation *LomsClientMockGetStockInfosExpectation
	expectations       []*LomsClientMockGetStockInfosExpectation

	callArgs []*LomsClientMockGetStockInfosParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LomsClientMockGetStockInfosExpectation specifies expectation struct of the lomsCli.GetStockInfos
type LomsClientMockGetStockInfosExpectation struct {
	mock               *LomsClientMock
	params             *LomsClientMockGetStockInfosParams
	paramPtrs          *LomsClientMockGetStockInfosParamPtrs
	expectationOrigins LomsClientMockGetStockInfosExpectationOrigins
	results            *LomsClientMockGetStockInfosResults
	returnOrigin       string
	Counter            uint64
}

// LomsClientMockGetStockInfosParams contains parameters of the lomsCli.GetStockInfos
type LomsClientMockGetStockInfosParams struct {
	ctx    context.Context
	skuIds []int64
}

// LomsClientMockGetStockInfosParamPtrs contains pointers to parameters of the lomsCli.GetStockInfos
type LomsClientMockGetStockInfosParamPtrs struct {
	ctx    *context.Context
	skuIds *[]int64
}

// LomsClientMockGetStockInfosResults contains results of the lomsCli.GetStockInfos
type LomsClientMockGetStockInfosResults struct {
	gp1 *proto.GetStockInfoResponse
	err error
}

// LomsClientMockGetStockInfosOrigins contains origins of expectations of the lomsCli.GetStockInfos
type LomsClientMockGetStockInfosExpectationOrigins struct {
	origin       string
	originCtx    string
	originSkuIds string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetStockInfos *mLomsClientMockGetStockInfos) Optional() *mLomsClientMockGetStockInfos {
	mmGetStockInfos.optional = true
	return mmGetStockInfos
}

// Expect sets up expected params for lomsCli.GetStockInfos
func (mmGetStockInfos *mLomsClientMockGetStockInfos) Expect(ctx context.Context, skuIds []int64) *mLomsClientMockGetStockInfos {
	if mmGetStockInfos.mock.funcGetStockInfos != nil {
		mmGetStockInfos.mock.t.Fatalf("LomsClientMock.GetStockInfos mock is already set by Set")
	}

	if mmGetStockInfos.defaultExpectation == nil {
		mmGetStockInfos.defaultExpectation = &LomsClientMockGetStockInfosExpectation{}
	}

	if mmGetStockInfos.defaultExpectation.paramPtrs != nil {
		mmGetStockInfos.mock.t.Fatalf("LomsClientMock.GetStockInfos mock is already set by ExpectParams functions")
	}

	mmGetStockInfos.defaultExpectation.params = &LomsClientMockGetStockInfosParams{ctx, skuIds}
	mmGetStockInfos.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetStockInfos.expectations {
		if minimock.Equal(e.params, mmGetStockInfos.defaultExpectation.params) {
			mmGetStockInfos.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetStockInfos.defaultExpectation.params)
		}
	}

	return mmGetStockInfos
}

// ExpectCtxParam1 sets up expected param ctx for lomsCli.GetStockInfos
func (mmGetStockInfos *mLomsClientMockGetStockInfos) ExpectCtxParam1(ctx context.Context) *mLomsClientMockGetStockInfos {
	if mmGetStockInfos.mock.funcGetStockInfos != nil {
		mmGetStockInfos.mock.t.Fatalf("LomsClientMock.GetStockInfos mock is already set by Set")
	}

	if mmGetStockInfos.defaultExpectation == nil {
		mmGetStockInfos.defaultExpectation = &LomsClientMockGetStockInfosExpectation{}
	}

	if mmGetStockInfos.defaultExpectation.params != nil {
		mmGetStockInfos.mock.t.Fatalf("LomsClientMock.GetStockInfos mock is already set by Expect")
	}

	if mmGetStockInfos.defaultExpectation.paramPtrs == nil {
		mmGetStockInfos.defaultExpectation.paramPtrs = &LomsClientMockGetStockInfosParamPtrs{}
	}
	mmGetStockInfos.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetStockInfos.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetStockInfos
}

// ExpectSkuIdsParam2 sets up expected param skuIds for lomsCli.GetStockInfos
func (mmGetStockInfos *mLomsClientMockGetStockInfos) ExpectSkuIdsParam2(skuIds []int64) *mLomsClientMockGetStockInfos {
	if mmGetStockInfos.mock.funcGetStockInfos != nil {
		mmGetStockInfos.mock.t.Fatalf("LomsClientMock.GetStockInfos mock is already set by Set")
	}

	if mmGetStockInfos.defaultExpectation == nil {
		mmGetStockInfos.defaultExpectation = &LomsClientMockGetStockInfosExpectation{}
	}

	if mmGetStockInfos.defaultExpectation.params != nil {
		mmGetStockInfos.mock.t.Fatalf("LomsClientMock.GetStockInfos mock is already set by Expect")
	}

	if mmGetStockInfos.defaultExpectation.paramPtrs == nil {
		mmGetStockInfos.defaultExpectation.paramPtrs = &LomsClientMockGetStockInfosParamPtrs{}
	}
	mmGetStockInfos.defaultExpectation.paramPtrs.skuIds = &skuIds
	mmGetStockInfos.defaultExpectation.expectationOrigins.originSkuIds = minimock.CallerInfo(1)

	return mmGetStockInfos
}

// Inspect accepts an inspector function that has same arguments as the lomsCli.GetStockInfos
func (mmGetStockInfos *mLomsClientMockGetStockInfos) Inspect(f func(ctx context.Context, skuIds []int64)) *mLomsClientMockGetStockInfos {
	if mmGetStockInfos.mock.inspectFuncGetStockInfos != nil {
		mmGetStockInfos.mock.t.Fatalf("Inspect function is already set for LomsClientMock.GetStockInfos")
	}

	mmGetStockInfos.mock.inspectFuncGetStockInfos = f

	return mmGetStockInfos
}

// Return sets up results that will be returned by lomsCli.GetStockInfos
func (mmGetStockInfos *mLomsClientMockGetStockInfos) Return(gp1 *proto.GetStockInfoResponse, err error) *LomsClientMock {
	if mmGetStockInfos.mock.funcGetStockInfos != nil {
		mmGetStockInfos.mock.t.Fatalf("LomsClientMock.GetStockInfos mock is already set by Set")
	}

	if mmGetStockInfos.defaultExpectation == nil {
		mmGetStockInfos.defaultExpectation = &LomsClientMockGetStockInfosExpectation{mock: mmGetStockInfos.mock}
	}
	mmGetStockInfos.defaultExpectation.results = &LomsClientMockGetStockInfosResults{gp1, err}
	mmGetStockInfos.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetStockInfos.mock
}

// Set uses given function f to mock the lomsCli.GetStockInfos method
func (mmGetStockInfos *mLomsClientMockGetStockInfos) Set(f func(ctx context.Context, skuIds []int64) (gp1 *proto.GetStockInfoResponse, err error)) *LomsClientMock {
	if mmGetStockInfos.defaultExpectation != nil {
		mmGetStockInfos.mock.t.Fatalf("Default expectation is already set for the lomsCli.GetStockInfos method")
	}

	if len(mmGetStockInfos.expectations) > 0 {
		mmGetStockInfos.mock.t.Fatalf("Some expectations are already set for the lomsCli.GetStockInfos method")
	}

	mmGetStockInfos.mock.funcGetStockInfos = f
	mmGetStockInfos.mock.funcGetStockInfosOrigin = minimock.CallerInfo(1)
	return mmGetStockInfos.mock
}

// When sets expectation for the lomsCli.GetStockInfos which will trigger the result defined by the following
// Then helper
func (mmGetStockInfos *mLomsClientMockGetStockInfos) When(ctx context.Context, skuIds []int64) *LomsClientMockGetStockInfosExpectation {
	if mmGetStockInfos.mock.funcGetStockInfos != nil {
		mmGetStockInfos.mock.t.Fatalf("LomsClientMock.GetStockInfos mock is already set by Set")
	}

	expectation := &LomsClientMockGetStockInfosExpectation{
		mock:               mmGetStockInfos.mock,
		params:             &LomsClientMockGetStockInfosParams{ctx, skuIds},
		expectationOrigins: LomsClientMockGetStockInfosExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetStockInfos.expectations = append(mmGetStockInfos.expectations, expectation)
	return expectation
}

// Then sets up lomsCli.GetStockInfos return parameters for the expectation previously defined by the When method
func (e *LomsClientMockGetStockInfosExpectation) Then(gp1 *proto.GetStockInfoResponse, err error) *LomsClientMock {
	e.results = &LomsClientMockGetStockInfosResults{gp1, err}
	return e.mock
}

// Times sets number of times lomsCli.GetStockInfos should be invoked
func (mmGetStockInfos *mLomsClientMockGetStockInfos) Times(n uint64) *mLomsClientMockGetStockInfos {
	if n == 0 {
		mmGetStockInfos.mock.t.Fatalf("Times of LomsClientMock.GetStockInfos mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetStockInfos.expectedInvocations, n)
	mmGetStockInfos.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetStockInfos
}

func (mmGetStockInfos *mLomsClientMockGetStockInfos) invocationsDone() bool {
	if len(mmGetStockInfos.expectations) == 0 && mmGetStockInfos.defaultExpectation == nil && mmGetStockInfos.mock.funcGetStockInfos == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetStockInfos.mock.afterGetStockInfosCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetStockInfos.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetStockInfos implements mm_service.lomsCli
func (mmGetStockInfos *LomsClientMock) GetStockInfos(ctx context.Context, skuIds []int64) (gp1 *proto.GetStockInfoResponse, err error) {
	mm_atomic.AddUint64(&mmGetStockInfos.beforeGetStockInfosCounter, 1)
	defer mm_atomic.AddUint64(&mmGetStockInfos.afterGetStockInfosCounter, 1)

	mmGetStockInfos.t.Helper()

	if mmGetStockInfos.inspectFuncGetStockInfos != nil {
		mmGetStockInfos.inspectFuncGetStockInfos(ctx, skuIds)
	}

	mm_params := LomsClientMockGetStockInfosParams{ctx, skuIds}

	// Record call args
	mmGetStockInfos.GetStockInfosMock.mutex.Lock()
	mmGetStockInfos.GetStockInfosMock.callArgs = append(mmGetStockInfos.GetStockInfosMock.callArgs, &mm_params)
	mmGetStockInfos.GetStockInfosMock.mutex.Unlock()

	for _, e := range mmGetStockInfos.GetStockInfosMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.gp1, e.results.err
		}
	}

	if mmGetStockInfos.GetStockInfosMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetStockInfos.GetStockInfosMock.defaultExpectation.Counter, 1)
		mm_want := mmGetStockInfos.GetStockInfosMock.defaultExpectation.params
		mm_want_ptrs := mmGetStockInfos.GetStockInfosMock.defaultExpectation.paramPtrs

		mm_got := LomsClientMockGetStockInfosParams{ctx, skuIds}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetStockInfos.t.Errorf("LomsClientMock.GetStockInfos got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetStockInfos.GetStockInfosMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.skuIds != nil && !minimock.Equal(*mm_want_ptrs.skuIds, mm_got.skuIds) {
				mmGetStockInfos.t.Errorf("LomsClientMock.GetStockInfos got unexpected parameter skuIds, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetStockInfos.GetStockInfosMock.defaultExpectation.expectationOrigins.originSkuIds, *mm_want_ptrs.skuIds, mm_got.skuIds, minimock.Diff(*mm_want_ptrs.skuIds, mm_got.skuIds))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetStockInfos.t.Errorf("LomsClientMock.GetStockInfos got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetStockInfos.GetStockInfosMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetStockInfos.GetStockInfosMock.defaultExpectation.results
		if mm_results == nil {
			mmGetStockInfos.t.Fatal("No results are set for the LomsClientMock.GetStockInfos")
		}
		return (*mm_results).gp1, (*mm_results).err
	}
	if mmGetStockInfos.funcGetStockInfos != nil {
		return mmGetStockInfos.funcGetStockInfos(ctx, skuIds)
	}
	mmGetStockInfos.t.Fatalf("Unexpected call to LomsClientMock.GetStockInfos. %v %v", ctx, skuIds)
	return
}

// GetStockInfosAfterCounter returns a count of finished LomsClientMock.GetStockInfos invocations
func (mmGetStockInfos *LomsClientMock) GetStockInfosAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetStockInfos.afterGetStockInfosCounter)
}

// GetStockInfosBeforeCounter returns a count of LomsClientMock.GetStockInfos invocations
func (mmGetStockInfos *LomsClientMock) GetStockInfosBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetStockInfos.beforeGetStockInfosCounter)
}

// Calls returns a list of arguments used in each call to LomsClientMock.GetStockInfos.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetStockInfos *mLomsClientMockGetStockInfos) Calls() []*LomsClientMockGetStockInfosParams {
	mmGetStockInfos.mutex.RLock()

	argCopy := make([]*LomsClientMockGetStockInfosParams, len(mmGetStockInfos.callArgs))
	copy(argCopy, mmGetStockInfos.callArgs)

	mmGetStockInfos.mutex.RUnlock()

	return argCopy
}

// MinimockGetStockInfosDone returns true if the count of the GetStockInfos invocations corresponds
// the number of defined expectations
func (m *LomsClientMock) MinimockGetStockInfosDone() bool {
	if m.GetStockInfosMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetStockInfosMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetStockInfosMock.invocationsDone()
}

// MinimockGetStockInfosInspect logs each unmet expectation
func (m *LomsClientMock) MinimockGetStockInfosInspect() {
	for _, e := range m.GetStockInfosMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LomsClientMock.GetStockInfos at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetStockInfosCounter := mm_atomic.LoadUint64(&m.afterGetStockInfosCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetStockInfosMock.defaultExpectation != nil && afterGetStockInfosCounter < 1 {
		if m.GetStockInfosMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LomsClientMock.GetStockInfos at\n%s", m.GetStockInfosMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LomsClientMock.GetStockInfos at\n%s with params: %#v", m.GetStockInfosMock.defaultExpectation.expectationOrigins.origin, *m.GetStockInfosMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetStockInfos != nil && afterGetStockInfosCounter < 1 {
		m.t.Errorf("Expected call to LomsClientMock.GetStockInfos at\n%s", m.funcGetStockInfosOrigin)
	}

	if !m.GetStockInfosMock.invocationsDone() && afterGetStockInfosCounter > 0 {
		m.t.Errorf("Expected %d calls to LomsClientMock.GetStockInfos at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetStockInfosMock.expectedInvocations), m.GetStockInfosMock.expectedInvocationsOrigin, afterGetStockInfosCounter)
	}
}

type mLomsClientMockPayOrder struct {
	optional           bool
	mock               *LomsClientMock
	defaultExpectation *LomsClientMockPayOrderExpectation
	expectations       []*LomsClientMockPayOrderExpectation

	callArgs []*LomsClientMockPayOrderParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LomsClientMockPayOrderExpectation specifies expectation struct of the lomsCli.PayOrder
type LomsClientMockPayOrderExpectation struct {
	mock               *LomsClientMock
	params             *LomsClientMockPayOrderParams
	paramPtrs          *LomsClientMockPayOrderParamPtrs
	expectationOrigins LomsClientMockPayOrderExpectationOrigins
	results            *LomsClientMockPayOrderResults
	returnOrigin       string
	Counter            uint64
}

// LomsClientMockPayOrderParams contains parameters of the lomsCli.PayOrder
type LomsClientMockPayOrderParams struct {
	ctx     context.Context
	orderId int64
}

// LomsClientMockPayOrderParamPtrs contains pointers to parameters of the lomsCli.PayOrder
type LomsClientMockPayOrderParamPtrs struct {
	ctx     *context.Context
	orderId *int64
}

// LomsClientMockPayOrderResults contains results of the lomsCli.PayOrder
type LomsClientMockPayOrderResults struct {
	err error
}

// LomsClientMockPayOrderOrigins contains origins of expectations of the lomsCli.PayOrder
type LomsClientMockPayOrderExpectationOrigins struct {
	origin        string
	originCtx     string
	originOrderId string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmPayOrder *mLomsClientMockPayOrder) Optional() *mLomsClientMockPayOrder {
	mmPayOrder.optional = true
	return mmPayOrder
}

// Expect sets up expected params for lomsCli.PayOrder
func (mmPayOrder *mLomsClientMockPayOrder) Expect(ctx context.Context, orderId int64) *mLomsClientMockPayOrder {
	if mmPayOrder.mock.funcPayOrder != nil {
		mmPayOrder.mock.t.Fatalf("LomsClientMock.PayOrder mock is already set by Set")
	}

	if mmPayOrder.defaultExpectation == nil {
		mmPayOrder.defaultExpectation = &LomsClientMockPayOrderExpectation{}
	}

	if mmPayOrder.defaultExpectation.paramPtrs != nil {
		mmPayOrder.mock.t.Fatalf("LomsClientMock.PayOrder mock is already set by ExpectParams functions")
	}

	mmPayOrder.defaultExpectation.params = &LomsClientMockPayOrderParams{ctx, orderId}
	mmPayOrder.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmPayOrder.expectations {
		if minimock.Equal(e.params, mmPayOrder.defaultExpectation.params) {
			mmPayOrder.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmPayOrder.defaultExpectation.params)
		}
	}

	return mmPayOrder
}

// ExpectCtxParam1 sets up expected param ctx for lomsCli.PayOrder
func (mmPayOrder *mLomsClientMockPayOrder) ExpectCtxParam1(ctx context.Context) *mLomsClientMockPayOrder {
	if mmPayOrder.mock.funcPayOrder != nil {
		mmPayOrder.mock.t.Fatalf("LomsClientMock.PayOrder mock is already set by Set")
	}

	if mmPayOrder.defaultExpectation == nil {
		mmPayOrder.defaultExpectation = &LomsClientMockPayOrderExpectation{}
	}

	if mmPayOrder.defaultExpectation.params != nil {
		mmPayOrder.mock.t.Fatalf("LomsClientMock.PayOrder mock is already set by Expect")
	}

	if mmPayOrder.defaultExpectation.paramPtrs == nil {
		mmPayOrder.defaultExpectation.paramPtrs = &LomsClientMockPayOrderParamPtrs{}
	}
	mmPayOrder.defaultExpectation.paramPtrs.ctx = &ctx
	mmPayOrder.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmPayOrder
}

// ExpectOrderIdParam2 sets up expected param orderId for lomsCli.PayOrder
func (mmPayOrder *mLomsClientMockPayOrder) ExpectOrderIdParam2(orderId int64) *mLomsClientMockPayOrder {
	if mmPayOrder.mock.funcPayOrder != nil {
		mmPayOrder.mock.t.Fatalf("LomsClientMock.PayOrder mock is already set by Set")
	}

	if mmPayOrder.defaultExpectation == nil {
		mmPayOrder.defaultExpectation = &LomsClientMockPayOrderExpectation{}
	}

	if mmPayOrder.defaultExpectation.params != nil {
		mmPayOrder.mock.t.Fatalf("LomsClientMock.PayOrder mock is already set by Expect")
	}

	if mmPayOrder.defaultExpectation.paramPtrs == nil {
		mmPayOrder.defaultExpectation.paramPtrs = &LomsClientMockPayOrderParamPtrs{}
	}
	mmPayOrder.defaultExpectation.paramPtrs.orderId = &orderId
	mmPayOrder.defaultExpectation.expectationOrigins.originOrderId = minimock.CallerInfo(1)

	return mmPayOrder
}

// Inspect accepts an inspector function that has same arguments as the lomsCli.PayOrder
func (mmPayOrder *mLomsClientMockPayOrder) Inspect(f func(ctx context.Context, orderId int64)) *mLomsClientMockPayOrder {
	if mmPayOrder.mock.inspectFuncPayOrder != nil {
		mmPayOrder.mock.t.Fatalf("Inspect function is already set for LomsClientMock.PayOrder")
	}

	mmPayOrder.mock.inspectFuncPayOrder = f

	return mmPayOrder
}

// Return sets up results that will be returned by lomsCli.PayOrder
func (mmPayOrder *mLomsClientMockPayOrder) Return(err error) *LomsClientMock {
	if mmPayOrder.mock.funcPayOrder != nil {
		mmPayOrder.mock.t.Fatalf("LomsClientMock.PayOrder mock is already set by Set")
	}

	if mmPayOrder.defaultExpectation == nil {
		mmPayOrder.defaultExpectation = &LomsClientMockPayOrderExpectation{mock: mmPayOrder.mock}
	}
	mmPayOrder.defaultExpectation.results = &LomsClientMockPayOrderResults{err}
	mmPayOrder.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmPayOrder.mock
}

// Set uses given function f to mock the lomsCli.PayOrder method
func (mmPayOrder *mLomsClientMockPayOrder) Set(f func(ctx context.Context, orderId int64) (err error)) *LomsClientMock {
	if mmPayOrder.defaultExpectation != nil {
		mmPayOrder.mock.t.Fatalf("Default expectation is already set for the lomsCli.PayOrder method")
	}

	if len(mmPayOrder.expectations) > 0 {
		mmPayOrder.mock.t.Fatalf("Some expectations are already set for the lomsCli.PayOrder method")
	}

	mmPayOrder.mock.funcPayOrder = f
	mmPayOrder.mock.funcPayOrderOrigin = minimock.CallerInfo(1)
	return mmPayOrder.mock
}

// When sets expectation for the lomsCli.PayOrder which will trigger the result defined by the following
// Then helper
func (mmPayOrder *mLomsClientMockPayOrder) When(ctx context.Context, orderId int64) *LomsClientMockPayOrderExpectation {
	if mmPayOrder.mock.funcPayOrder != nil {
		mmPayOrder.mock.t.Fatalf("LomsClientMock.PayOrder mock is already set by Set")
	}

	expectation := &LomsClientMockPayOrderExpectation{
		mock:               mmPayOrder.mock,
		params:             &LomsClientMockPayOrderParams{ctx, orderId},
		expectationOrigins: LomsClientMockPayOrderExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmPayOrder.expectations = append(mmPayOrder.expectations, expectation)
	return expectation
}

// Then sets up lomsCli.PayOrder return parameters for the expectation previously defined by the When method
func (e *LomsClientMockPayOrderExpectation) Then(err error) *LomsClientMock {
	e.results = &LomsClientMockPayOrderResults{err}
	return e.mock
}

// Times sets number of times lomsCli.PayOrder should be invoked
func (mmPayOrder *mLomsClientMockPayOrder) Times(n uint64) *mLomsClientMockPayOrder {
	if n == 0 {
		mmPayOrder.mock.t.Fatalf("Times of LomsClientMock.PayOrder mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmPayOrder.expectedInvocations, n)
	mmPayOrder.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmPayOrder
}

func (mmPayOrder *mLomsClientMockPayOrder) invocationsDone() bool {
	if len(mmPayOrder.expectations) == 0 && mmPayOrder.defaultExpectation == nil && mmPayOrder.mock.funcPayOrder == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmPayOrder.mock.afterPayOrderCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmPayOrder.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// PayOrder implements mm_service.lomsCli
func (mmPayOrder *LomsClientMock) PayOrder(ctx context.Context, orderId int64) (err error) {
	mm_atomic.AddUint64(&mmPayOrder.beforePayOrderCounter, 1)
	defer mm_atomic.AddUint64(&mmPayOrder.afterPayOrderCounter, 1)

	mmPayOrder.t.Helper()

	if mmPayOrder.inspectFuncPayOrder != nil {
		mmPayOrder.inspectFuncPayOrder(ctx, orderId)
	}

	mm_params := LomsClientMockPayOrderParams{ctx, orderId}

	// Record call args
	mmPayOrder.PayOrderMock.mutex.Lock()
	mmPayOrder.PayOrderMock.callArgs = append(mmPayOrder.PayOrderMock.callArgs, &mm_params)
	mmPayOrder.PayOrderMock.mutex.Unlock()

	for _, e := range mmPayOrder.PayOrderMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.err
		}
	}

	if mmPayOrder.PayOrderMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmPayOrder.PayOrderMock.defaultExpectation.Counter, 1)
		mm_want := mmPayOrder.PayOrderMock.defaultExpectation.params
		mm_want_ptrs := mmPayOrder.PayOrderMock.defaultExpectation.paramPtrs

		mm_got := LomsClientMockPayOrderParams{ctx, orderId}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmPayOrder.t.Errorf("LomsClientMock.PayOrder got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmPayOrder.PayOrderMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.orderId != nil && !minimock.Equal(*mm_want_ptrs.orderId, mm_got.orderId) {
				mmPayOrder.t.Errorf("LomsClientMock.PayOrder got unexpected parameter orderId, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmPayOrder.PayOrderMock.defaultExpectation.expectationOrigins.originOrderId, *mm_want_ptrs.orderId, mm_got.orderId, minimock.Diff(*mm_want_ptrs.orderId, mm_got.orderId))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmPayOrder.t.Errorf("LomsClientMock.PayOrder got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmPayOrder.PayOrderMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmPayOrder.PayOrderMock.defaultExpectation.results
		if mm_results == nil {
			mmPayOrder.t.Fatal("No results are set for the LomsClientMock.PayOrder")
		}
		return (*mm_results).err
	}
	if mmPayOrder.funcPayOrder != nil {
		return mmPayOrder.funcPayOrder(ctx, orderId)
	}
	mmPayOrder.t.Fatalf("Unexpected call to LomsClientMock.PayOrder. %v %v", ctx, orderId)
	return
}

// PayOrderAfterCounter returns a count of finished LomsClientMock.PayOrder invocations
func (mmPayOrder *LomsClientMock) PayOrderAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPayOrder.afterPayOrderCounter)
}

// PayOrderBeforeCounter returns a count of LomsClientMock.PayOrder invocations
func (mmPayOrder *LomsClientMock) PayOrderBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmPayOrder.beforePayOrderCounter)
}

// Calls returns a list of arguments used in each call to LomsClientMock.PayOrder.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmPayOrder *mLomsClientMockPayOrder) Calls() []*LomsClientMockPayOrderParams {
	mmPayOrder.mutex.RLock()

	argCopy := make([]*LomsClientMockPayOrderParams, len(mmPayOrder.callArgs))
	copy(argCopy, mmPayOrder.callArgs)

	mmPayOrder.mutex.RUnlock()

	return argCopy
}

// MinimockPayOrderDone returns true if the count of the PayOrder invocations corresponds
// the number of defined expectations
func (m *LomsClientMock) MinimockPayOrderDone() bool {
	if m.PayOrderMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.PayOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.PayOrderMock.invocationsDone()
}

// MinimockPayOrderInspect logs each unmet expectation
func (m *LomsClientMock) MinimockPayOrderInspect() {
	for _, e := range m.PayOrderMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LomsClientMock.PayOrder at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterPayOrderCounter := mm_atomic.LoadUint64(&m.afterPayOrderCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.PayOrderMock.defaultExpectation != nil && afterPayOrderCounter < 1 {
		if m.PayOrderMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LomsClientMock.PayOrder at\n%s", m.PayOrderMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LomsClientMock.PayOrder at\n%s with params: %#v", m.PayOrderMock.defaultExpectation.expectationOrigins.origin, *m.PayOrderMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcPayOrder != nil && afterPayOrderCounter < 1 {
		m.t.Errorf("Expected call to LomsClientMock.PayOrder at\n%s", m.funcPayOrderOrigin)
	}

	if !m.PayOrderMock.invocationsDone() && afterPayOrderCounter > 0 {
		m.t.Errorf("Expected %d calls to LomsClientMock.PayOrder at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.PayOrderMock.expectedInvocations), m.PayOrderMock.expectedInvocationsOrigin, afterPayOrderCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *LomsClientMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCancelOrderInspect()

			m.MinimockCreateOrderInspect()

			m.MinimockGetByIdInspect()

			m.MinimockGetStockInfosInspect()

			m.MinimockPayOrderInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *LomsClientMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *LomsClientMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCancelOrderDone() &&
		m.MinimockCreateOrderDone() &&
		m.MinimockGetByIdDone() &&
		m.MinimockGetStockInfosDone() &&
		m.MinimockPayOrderDone()
}
